### ISSUE TITLE
Thing types should have a "listed" flag

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#1073]
With bindings having more and more thing types (newest addition Z-Wave with 100+), it does not make sense to list them all on the "manually add thing" wizard.
Instead, we should have a few more generic thing types being offered there and keep the specific ones only for the auto-discovery and inbox.
I think it should be feasible to simply add a new boolean flag "listed" to the thing type definition and have the UIs filter out the ones that are not meant to be "publicly presented".

**Comment by sjka** [comment]
shall we really make it *listed* explicitly or *hidden*? I'd consider a conscious listing the better way, but on the other hand so far *listed* actually is the default and therefore we'd require all bindings to change their thing types in order to stay listed. Therefore it's an incompatible change, though relevant only for the PaperUI...

**Comment by cdjackson** [comment]
I'd be happy to have listed attribute that defaults to *true*.  For Z-Wave, I'd quite like to hide 99% of the things to stop people adding them manually. Given the Z-Wave things are generated from a database it's REALLY easy for me to add 'listed=false' (or whatever is chosen) to them all.

**Comment by kaikreuzer** [comment]
I don't care too much about what is the default. We can throw a dice ;-)
I agree that default=true is the less intrusive change as it keeps backward compatibility, so I am fine to go with that.

**Comment by sjka** [comment]
alea iacta est: I will implement the listed flag defaulting to "true" :-)
