### ISSUE TITLE
PaperUI: Setup Wizard > Refresh: Remove old results

### ISSUE THREAD

**Issue by davidgraeff** [eclipse/smarthome#1119]
At the moment there is no way remove all old search results of discovery runs.
If you have a lot of old results in the dicovery list, it is very tedious to click the remove icon, confirm, scroll, do the same again for every entry.

I see 3 possible solutions:
* Add a remove all / hide all button.
* Remove old results if the user clicks the "Refresh" icon on the top left.
* Make entries "selectable" and add batch actions.

For mobile plattforms left/right swipeable items would be convenient for fast removal/hiding.

**Comment by kaikreuzer** [comment]
The question is: Why do you have at all "old" results?
In general, the discovery service implementations are responsible for cleaning up by themselves, so I do not see this to be solved in the UI.
Discovery results can have a time to live, so that they are automatically removed as well. So please identify the binding, which does not properly clean up and enter issues for these bindings!
