### ISSUE TITLE
Avoid magic numbers in REST documentation

### ISSUE THREAD

**Issue by tomhoefer** [eclipse/smarthome#1154]
Having the REST swagger documentation available is very nice. However currently the documentation bases on numeric values ("magic numbers") to express the response codes, e. g.
```
@POST
@Consumes(MediaType.APPLICATION_JSON)
@ApiOperation(value = "Adds a new thing to the registry.")
@ApiResponses(value = { 
    @ApiResponse(code = 200, message = "OK"),
    @ApiResponse(code = 400, message = "No binding can create the thing.") })
public Response create(
    @HeaderParam(HttpHeaders.ACCEPT_LANGUAGE) 
    @ApiParam(value = "language") String language,
    @ApiParam(value = "thing data", required = true) ThingDTO thingBean) {
....
```
I would like to extend the RESTResource interface with Response codes:
```
public interface RESTResource {
    public static final int OK = 200;
    public static final int BAD_REQUEST = 400;
    ...
}
```
As a result the swagger documentation would look like:
```
@POST
    @Consumes(MediaType.APPLICATION_JSON)
    @ApiOperation(value = "Adds a new thing to the registry.")
    @ApiResponses(value = { @ApiResponse(code = OK, message = "OK"),
            @ApiResponse(code = BAD_REQUEST, message = "No binding can create the thing.") })
    public Response create(@HeaderParam(HttpHeaders.ACCEPT_LANGUAGE) @ApiParam(value = "language") String language,
            @ApiParam(value = "thing data", required = true) ThingDTO thingBean) {
```
Since each RESTResource implements this interface no additional dependency is required (even no static import). Additionally the tracking of response codes is much easier....

What is your opinion?

**Comment by maggu2810** [comment]
I will always prefer constants variable instead of magic numbers.
For the response code I don't know if this does matter, because OK will always be 200, BAD REQUEST will always be ...
I don't think we will ever change OK to something different then 200.

But if you would like to change that, it is okay from my side.
* ./bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/proxy/ProxyServlet.java
* ./bundles/io/org.eclipse.smarthome.io.net/src/main/java/org/eclipse/smarthome/io/net/http/HttpUtil.java
* ./bundles/io/org.eclipse.smarthome.io.net.test/src/test/java/org/eclipse/smarthome/io/net/http/HttpUtilTest.java
* ./extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/src/main/java/org/eclipse/smarthome/binding/fsinternetradio/internal/radio/FrontierSiliconRadioConnection.java
imports "org.apache.commons.httpclient" that contains such definitions (https://hc.apache.org/httpclient-3.x/apidocs/org/apache/commons/httpclient/HttpStatus.html).

But (WRT https://www.eclipse.org/forums/index.php/t/1069192/) I assume we do not want to use this dependency anymore (perhaps we should move forward to drop them).

**Comment by maggu2810** [comment]
FYI: The httpcomponents contains them, too.
http://hc.apache.org/httpcomponents-core-ga/httpcore/apidocs/org/apache/http/HttpStatus.html

**Comment by kaikreuzer** [comment]
I also would not consider these magic, since they very clearly refer to the HTTP specification and their meaning is therefore clear in the code (therefore there is no magic).
For people knowing the response codes, the code is imho easier readable with numbers. This is also how all available Swagger examples do it.

So I do not really see a good reason for changing it.

**Comment by tomhoefer** [comment]
Fine for me...
