### ISSUE TITLE
Status Translation does not work properly

### ISSUE THREAD

**Issue by shorty707** [eclipse/smarthome#1157]
For my zwave items reporting ON OFF there should be a translation to eg. open / close by default
this does not work properly

please see esp. post 2 and 6 in the following. according to chris the dev of the zwave binding the issue is likely within ESH and not the binding
https://community.openhab.org/t/map-transform-for-zwave-items/8349

( https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.zwave/ESH-INF/thing/_channels.xml#L206

**Comment by triller-telekom** [comment]
The status translation is working fine, but the problem here is that the zwave binding was/is reporting ON/Off instead of the expected Open/Closed. This is due to the fact that the zwave channel was/is reporting state updates for type `Switch` which is On/Off and not type ´Contact` which is Open/Closed.

That discussion needs https://github.com/eclipse/smarthome/issues/583 so bindings get some information about what is linked to them and how so they can provide the status in a proper way.

Since this issue is about the translation, I think we can close it and continue in #583 with the other topic.

@kaikreuzer @sjka Can you please close this issue?

**Comment by sjka** [comment]
Well, isn't the question actually whether `OnOffType.getStateAs()` should support translation to `OpenClosedType` (and vice versa) or not?

I can only speculate about the reasons, but I'd assume the unclear semantics (i.e. does OPEN mean ON or OFF? Depends on the context...) is the reason why this is not supported. @kaikreuzer right?

**Comment by kaikreuzer** [comment]
Yes, the unclear semantics were the main reason to have a Contact item in the first place - there simply is no "correct" mapping, whatever is chosen might be misleading in some situations. Therefore, bindings should directly use the Contact type if they want to provide open/closed information.
