### ISSUE TITLE
autoupdate

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#1194]
I am a little bit indecisive about the autoupdate bundle.

If I understand it correctly it updates the state of an item if a command is received (and it is assignable).
If the bundle is activated all items are updated (default = true).
Someone could implement an AutoUpdateBindingConfigProvider to prevent that for special items.

If I use an UI and send a command to an item, the thing handler for the thing that channels are linked to that item receive that command.
Now it is up to the binding to execute the command (perhaps delegate something to the device) and if a channel is updated, the binding calls updateState.
The framework will update all linked items.

Is that correct?

If e.g. the command is dropped by the binding and so no state is updated, the item that is linked to the channel does not contain the correct state.

What is the use case of the autoupdate bundle? For demos and items that are not linked to channels?
But in this case I would prefer a default of false and someone could activate that for some bundles.
* autoupdate = inactive, no provider needs to prevent an item update
* autoupdate = active, you need a provider that deactivates its for all but some items

Perhaps someone could give me some more informations about that bundle.

**Comment by kaikreuzer** [comment]
Yes, your summary is more or less correct.
Having it default=true makes sense, because otherwise your unbound items would not work (i.e. a switch in the UI would never show the right state).
It also makes sense for uni-directional bindings, which cannot provide any feedback on state changes.

Note https://github.com/eclipse/smarthome/issues/595 - in this context, we can discuss that by default the auto-update should be set to off for a channel and that a binding can decide for certain channels that it should be turned on. Does that make sense to you?

P.S.: Isn't the forum a better place for such questions?

**Comment by maggu2810** [comment]
> P.S.: Isn't the forum a better place for such questions?

Will add a topic there this evening.

**Comment by kaikreuzer** [comment]
Does this mean I didn't answer your question in total?

**Comment by maggu2810** [comment]
I don't know, perhaps.
Depends on if I understand your answer correctly :wink:
Topic continues here: https://www.eclipse.org/forums/index.php/t/1075677/
