### ISSUE TITLE
Yahoo Binding - Yahoo weather API now uses OAUTH

### ISSUE THREAD

**Issue by individualist** [eclipse/smarthome#1273]
According to https://developer.yahoo.com/weather/, Yahoo has begun requiring OAuth 1 for their weather data source, resulting in a HTTP 401 response with the content:

```
<yahoo:error xmlns:yahoo="http://www.yahooapis.com/v1/base.rng" xml:lang="en-US" yahoo:uri="http://yahoo.com">
  <yahoo:description>
    Please provide valid credentials. OAuth oauth_problem="OST_OAUTH_PARAMETER_ABSENT_ERROR", realm="yahooapis.com"
  </yahoo:description>
  <yahoo:detail>
    Please provide valid credentials. OAuth oauth_problem="OST_OAUTH_PARAMETER_ABSENT_ERROR", realm="yahooapis.com"
  </yahoo:detail>
</yahoo:error>
```

In, fact, while looking into this, I wondered if the RSS feed http://weather.yahooapis.com/forecastrss should be used at all, considering the API at  https://query.yahooapis.com/ allows queries which can be written to use lookup woeid by City or Latitude/Longitude

**Comment by watou** [comment]
Despite that note at https://developer.yahoo.com/weather/, [this query](https://query.yahooapis.com/v1/public/yql?format=json&q=SELECT%20*%20FROM%20weather.forecast%20WHERE%20u=%27c%27%20AND%20woeid%20=%20%27638242%27) continues to work without OAuth credentials (for some reason).  And unless Yahoo! has since reinstated it, they took away the ability to convert lat,long into a `woeid` several weeks ago.

**Comment by kaikreuzer** [comment]
Thanks for the hint, @watou. I have adapted the binding in #1275 accordingly.
Let's hope that Yahoo keeps this url working without authentication.

**Comment by MohitPuri1996** [comment]
Have you Found solution for this ,i stucked in the same well,pls help me
