### ISSUE TITLE
Confusing behavior in PaperUI when deleting thing which was added via .things file in conf folder

### ISSUE THREAD

**Issue by satish-nikam** [eclipse/smarthome#1341]
When we use .things files in config folder, the PaperUI shows such things, but it shows Edit and Delete button. When we click delete, the status of such thing is changed to "REMOVED" and apparently there is no easy way to revert it back. 

Does it make sense to remove Edit/Delete option for such things and provide message indicating corresponding thing can be edited only by editing .thing file?

**Comment by kaikreuzer** [comment]
Having the status switched to REMOVED (isn't it "REMOVING"?) is clearly not right.
It should not be possible to remove things that are defined statically in a file.

Unfortunately, the UI currently cannot determine whether a Thing is editable/deletable - it only learns when trying to update/delete it. We will have to work out how to solve this. There is a similar discussion at https://www.eclipse.org/forums/index.php?t=msg&th=1072808&goto=1718043&#msg_1718043, unfortunately without a clear result yet.

**Comment by sjka** [comment]
The ThingResource would reject such a removal attempt for non-managed things with a 409 CONFLICT response, leaving it ONLINE. 
However, the UI currently still uses the ThingSetupManagerResource, which simply does not care. So #1013 is going to fix it. Question is: is it worth to still fix the ThingSetupManager? IMHO it's not...

**Comment by kaikreuzer** [comment]
I agree, we can wait for #1013.

**Comment by triller-telekom** [comment]
Since #1013 has been merged since quite a while I just tried the following use cases:

1. Edit a thing which was created via a .things file
- Result is a quick "Thing updated" popup, followed by a "409 CONFLICT" response and the thing is not changed

2. Delete a thing which was created via a .things file
- Result is a "409 CONFLICT" response and the thing is not deleted.

So I guess this is working as expected.

@kaikreuzer: Can you please close this issue?
