### ISSUE TITLE
UpnpDiscoveryPaticipant showing devices which are not online

### ISSUE THREAD

**Issue by shry15harsh** [eclipse/smarthome#1390]
In `DiscoveryResult createResult(RemoteDevice device)` I am getting devices which are not reachable. For example, even if I switch off Philips Hue Bridge, it discovers it.
I used cling workbench to check if I could find the Hue Bridge (may be because of some sort of cache), but it did not show it instantaneously which was the right behavior I expected.

Is this some kind of TTL in Upnp Discovery?

**Comment by kaikreuzer** [comment]
According to the UPnP spec there is a cache control for annoucements saying that the TTL "should be greater than or equal to 1800 seconds (30 minutes)."

So if you keep your system running and the hue bridge is still in the inbox after - let's say - an hour, I would say that it is a bug in ESH. Otherwise, it is fully compliant to the spec.

**Comment by shry15harsh** [comment]
If that is the case, then it's fine.
