### ISSUE TITLE
Right behavior of getByTags(Set<String> tags) method

### ISSUE THREAD

**Issue by danchom** [eclipse/smarthome#1413]
ModuleTypeRegistry has a method Collection<T> getByTags(Set<String> tags), which returns all the moduleTypes which have been tagged with one of the tags in the filter.
For example:
modulType1 has tags: tag1, tag2
modulType2 has tags: tag1
At the moment getByTags(Set<String> {"tag1"}) will return collection of moduleType1 and moduleType2. The same result will be returned by getByTags(Set<String> {"tag1", "tag2"}) because they both are tagged as "tag1"

Isn't be better if the method getByTags(Set<String> {"tag1", "tag2"}) returns only module types which have been tagged with both tag1 and tag2?
in that way:
getByTags(Set<String> {"tag1"}) will return collection of moduleType1 and moduleType2. - because they satisfied condition to be tagged as "tag1"
getByTags(Set<String> {"tag1", "tag2"}) will returns only  moduleType2 because only it has tags  "tag1" and "tag2"

The same can be applied to RuleRegistry and TemplateRegistry

**Comment by kaikreuzer** [comment]
Yes, makes sense to me.

**Comment by danchom** [comment]
On the other hand if you have a module type is tagged as Celsius  and other which is tagged Kelvin 
I can expect from the getByTag(Set {"Celsius", "Kelvin", "Temperature"}")  to return all the types related to temperature to be returned, but the method will not return anything because there isn't a rule tagged with all the tags. 
The question is what will be more usable, to interpret tags as AND or OR

**Comment by kaikreuzer** [comment]
I think in your case you should only query for the tag "Temperature" and all is fine.

The underlying question of your use case is rather on how we could support hierarchies within tags. This is very much related to https://github.com/eclipse/smarthome/issues/1093 - I think for a start we can live with a "flat list" of tags, but sooner or later we will have to deal with hierarchies as well (so that you can query "all temperature related" module types, independent of whether they deal with Celsius, Fahrenheit or Kelvin).

**Comment by kaikreuzer** [comment]
Implemented with #1456
