### ISSUE TITLE
Proposal for improvements of Automation engine API

### ISSUE THREAD

**Issue by danchom** [eclipse/smarthome#1483]
1) Replace ModuleTypeRegistry.getAll(Class) with following method:  getTriggers(), getTriggers(Locale), getConditions(), getConditions(Locale) and getActions(), getActions(Locale)
--  same for TemplateRegistry
2) Change parameter of getByTags(Set<String> tags) mehtod -> getByTags(String[] tags) - It is simple to use i.e. getByTags(String[]{"tag1", "tag2"}). This change has to be applied to  RuleRegistry, ModuleTypeRegistry and TemplateRegistry.
3) RuleRegistry: getStatus(String ruleUID); -> getStatusInfo(String ruleUID) - the return object is StatusInfo object not just a Status object.
4) Check rule's constructors. Remove configuration description and configuration from rule without template. Check all constructors.
5) Check if it is suitable to set name and tags of rule without update the rule. In this way the rule resolutio will be skipped.
6) Add ruleId into RuleStatusInfo object. The receivers must know what was the source of this status info object. At the moment this relation is done in RuleStatusInfoEvent, but IMHO it has to be part of RuleStatusInfo object. (see RuleStatusInfoEvent)

**Comment by kaikreuzer** [comment]
1) makes sense, fine with me
2) I'd prefer to go for var args, i.e. providing an additional covenience method getByTags("tag1", "tag2") and have the method implementation convert that in a set.
3) Agreed. We might also want to add a getStatus which then returns a RuleStatus.
4) This is discussed in #1508 
5) It imho makes sense to skip re-resolution of the rule in this case, but I would refrain from changing any APIs for it - from a REST perspective, we could still simply send the complete rule json and only the rule registry would then internally do a diff, notice that only the name/tags have changed, update the rule accordingly and NOT trigger a re-resolution.
6) This does not make much sense to me. A "Status" object should not have a reference back to the entity it belongs to. The consumer should know the context of such an object through other means, either because it called getStatus for some entity or because it receives an event for an entity that contains the status (so the event is a kind of wrapper that contains the information that you ask for).
