### ISSUE TITLE
Unable to tag item belonging to thing created dynamically (using discovery method)

### ISSUE THREAD

**Issue by satish-nikam** [eclipse/smarthome#1571]
I recently upgraded to latest ESH and noticed that I cannot tag an item belonging to thing created dynamically using discovery method. This was working earlier (around 2 months back), but now it returns METHOD_NOT_ALLOWED. I tried to debug and noticed that it is not part of managedItemProvider and fails the following check in org.eclipse.smarthome.io.rest.core.item.ItemResource.java file.

            if (managedItemProvider.get(memberItemName) == null) {
                return Response.status(Status.METHOD_NOT_ALLOWED).build();
            }

Is this because of recent refactoring? Is this intentional? I guess tagging should be allowed for both managed and unmanaged items.

**Comment by maggu2810** [comment]
Hm, perhaps that related to the changes done in #1288

**Comment by kaikreuzer** [comment]
> This was working earlier

No, it was also the case that only managed items were taggable, the only difference now is that through #1288 no items are created for you in the database anymore - so you need to create the items yourself in order to be able to tag them (in Paper UI, go to Services->Linking and disable the "simple mode). I'll try to document this soon...

**Comment by satish-nikam** [comment]
oh..thanks for info. I will try creating item myself and then tag.
