### ISSUE TITLE
Sonos Things are shown ONLINE although not on the network

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#1631]
It seems that the Sonos thing handler sets the status to ONLINE on initialization, even if the device is not reachable (or not even on the network).
I would expect it to be OFFLINE instead.

**Comment by R-Edelhoff** [comment]
Yes i can reproduce the issue with following steps:
- Sonos player will be paired while reachable in network -> State of created thing is ONLINE
- Restart the runtime and disconnect the Sonos device afterwards
- When the runtime is back again the state of the thing is still ONLINE 

The rootcause for this issue is that the polling runnable (where the thing state is periodically updated)
will not be scheduled when the ThingHandler gets initialized. This happens because the UpnpIOParticipant (which is the ZonePlayerHandler in this case) is not registered to the UpnpIOService at this time and the "isRegistered()" check prevents the handler to schedule the runnable during initialization.

However the "isRegistered()" is not required at this point because the UpnpIOParticipant will anyway be registered (if not already done) when using the UpnpIOService in the following calls of "addSubscription()" and "*.invokeAction()". Hence we can remove this check which is fixing the issue and does not create any regression as i have tested as well.

I will not going to set the thing status to OFFLINE after initialization because the Thing state will appear as OFFLINE for 60s after pairing the device which is confusing. We rather need to make sure that the polling runnable will always be scheduled to enforce a thing status update within max. 60s.
