### ISSUE TITLE
JSON Editor

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#1638]
At least for the rule modules we are using JSON files.

As there are already some on JSON files, I would like to ask if there is a preferred Eclipse IDE extension that supports formatting etc.

I have found this ones:
* https://marketplace.eclipse.org/content/json-editor-plugin
* https://marketplace.eclipse.org/content/json-tools

If we can choice one, I assume it is okay to add it to the setup file, so everyone can use the same one with the same formatter settings.

**Comment by kaikreuzer** [comment]
I don't have any strong opinion on which one to choose, but having a JSON editor in the IDE would indeed be nice.

From the download stats, the json-editor-plugin seems to be the one getting more attention recently.

**Comment by kaikreuzer** [comment]
I think this issue is obsolete.
I saw a nice presentation by @ibuziuk yesterday at an Eclipse DemoCamp, where he showed the new features of JSDT in Neon - one of it is a JSON editor, see https://www.eclipse.org/webtools/releases/3.8.0/NewAndNoteworthy/sourceediting.php.

As the IDE setup is now updated to Neon, this is already part of our IDE and the editor shows up nicely for me :-)
