### ISSUE TITLE
Provide access to Thing status in textual (DSL) rules

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#1654]
In rules it is often desirable to access the status of a Thing - currently, this information is not yet available.
We should add a function to access this information within the (old) Xtext DSL rules.

**Comment by kceiw** [comment]
Hi @kaikreuzer . Can you point me how to start? I would like to implement it in spare time. I look at the document https://www.eclipse.org/smarthome/documentation. But still I am not sure how to do.

**Comment by kaikreuzer** [comment]
Hi @kceiw Unfortunately, this isn't too trivial - you should have some understanding of Xtext/Xtend/Xbase.

FTR, this is the place where item names are made available and resolvable within scripts/rules:
https://github.com/eclipse/smarthome/blob/master/bundles/model/org.eclipse.smarthome.model.script/src/org/eclipse/smarthome/model/script/jvmmodel/ScriptJvmModelInferrer.xtend

And the classes in https://github.com/eclipse/smarthome/tree/master/bundles/model/org.eclipse.smarthome.model.script/src/org/eclipse/smarthome/model/script/scoping bring implicit java package imports, command and state types and the action methods.

Somewhere along these places the Things would need to be added. We probably should first discuss the syntax of what we want to achieve. Probably, adding an action could be the simplest solution in the end, although I think we would also want a new rule trigger type.

**Comment by kceiw** [comment]
Thanks @kaikreuzer .
There is a big learning curve. I'm ramping up the code base and trying to understand ESH's design. It could take much time for me to work on this. Anybody with more experience is welcome to work on it. However, I'm still interested in working on it, for satisfy my own requirement.

I'm not quite understand about "the Things need to be added". My understanding is that the status is an attribute of the Thing. Why do we need to add Things?
And for me, I'm using OH1's syntax (is there a new one?). So something like
```
when
    Thing DoorSensor changed from ONLINE to DEAD
then
    ...
end

```

It seems more like a condition than an action. Do you mean that setting state DEAD is an action in the rule system, and that'll trigger whatever in between then and end to be executed? Please correct me if I misunderstand.

**Comment by kceiw** [comment]
Hi @kaikreuzer,
After reading the code, I think we could
(assuming we're using the syntax "Thing DoorSensor changed from ONLINE to OFFLINE)
1. Have RuleEngineImpl listen to/handle ThingStatusInfoChangedEvent. I also assume OFFLINE means disconnect. Otherwise, we need to create a new ThingStatusInfo for Thing.
RuleEngineImple will execute the rule.
2. Create a new EventTrigger, for example, ThingStatusEventTrigger.
3. Need to extend the syntax in Rules.xtext.
4. Expand RulesJvmModelInferrer to handle the new EventTrigger.
5. Create a new state (ONLINE/OFFLINE) and add that to StateAndCommandProvider. And also add missing parts to org.eclipse.smarthome.model.script.scroping, for example, implicit package imports.

That's what I think what needs to be done to have a rule run when Thing goes OFFLINE.
If at the other hand, we want to get Thing status in all rules' actions (regardless their triggers), we don't need to do most of the above, but create a new ActionService to expose the things status (assuming this is what you mean by "adding an action"). But can we get any item state in any scripts? We may be able to use a similar syntax. And how do we expose those item state? Is it via some kind of ActionService? But I don't find any one. 

Please let me know if I am missing anything.

**Comment by sjka** [comment]
As far as I can see, #3001 added trigger and and an action service to access the thing status at any location. So to me it looks like this issue was resolved, or did I miss anything?

**Comment by gersilex** [comment]
It is resolved indeed, thanks.

Simon Kaufmann <notifications@github.com> schrieb am Fr., 30. Juni 2017,
21:14:

**Comment by kaikreuzer** [comment]
The only part that is missing is [to add it to the documentation](https://github.com/eclipse/smarthome/pull/3001#issuecomment-309302955).
