### ISSUE TITLE
ItemThingLinkRegistry removal in 0.8.0

### ISSUE THREAD

**Issue by IOOOTAlan** [eclipse/smarthome#1707]
Greetings,

first, apologies if this in not the right place to ask for this kind of information, but I couldn't find a more proper place to ask for it.
Our code-base depends on the aforementioned class to retrieve all Items linked to a `Thing` using the `getLinkedItems` method. The method was already marked as deprecated, but now the whole class is nowhere to be found, so our code cannot compile with the latest 0.8.0 release.
Is there a new way to access that kind of information?

**Comment by kaikreuzer** [comment]
Apologies for removing the method :-)
But it simply didn't make a lot of sense to link items to Things, since it is more or less duplicate information then.
So instead, you would now simply request the Thing and see its channels, which have the set of linked items attached to them (talking here about the REST API).
If you want to do that in Java code, you will have to iterate yourself over the channels and get ask the ItemChannelLinkRegistry for the linked items. Very similar to what EnrichedThingDTO is doing in the REST API.

Btw, the right place to discuss such things is https://www.eclipse.org/forums/index.php/f/271/.

Best regards,
Kai

**Comment by IOOOTAlan** [comment]
Thank you very much for the pointers!
