### ISSUE TITLE
LocaleProvider: Use always default locale for getLocale operation as long as no locale has been configured

### ISSUE THREAD

**Issue by tomhoefer** [eclipse/smarthome#1720]
Currently the newly introduced ```org.eclipse.smarthome.core.internal.i18n.LocaleProviderImpl``` initializes its locale attribute at instantiation and sets it to the Java default locale. 

I would prefer if we never initialize the locale attribute with a default locale. For this reason the ``` getLocale``` operation should return the default locale if the attribute has not been configured.

**Comment by kaikreuzer** [comment]
This would allow to use Locale.setDefault() during runtime (e.g. during test execution) and still have this taken into account by the LocaleProviderImpl.

Does that make sense to you, @maggu2810?

**Comment by maggu2810** [comment]
I already changed the default locale in some tests (e.g. using CM), so it is also possible without that change.
I don't know if it make sense remove the control of the locale from the LocaleProvider just to make some tests simpler (need to think about).
I assume if Locale.setDefault() is working, it is used again.
And last but not least, the Locale.setDefault() will work only as long as there is no configuration injected. If this is the case, the default locale is not used anymore.

There are different other options already used in tests:
* use a dummy locale provider: https://github.com/eclipse/smarthome/pull/1519/files#diff-b9568b6c033125c705409fc01f182596R92
* using config admin (a utilitity method could be added to OSGiTest): https://github.com/eclipse/smarthome/pull/1519/files#diff-7021705a958584a49d233e651600c62bR105
* using modified function directly: https://github.com/eclipse/smarthome/pull/1519/files#diff-cf9fa8322d398233b268d27f048a4e3bR67

**Comment by kaikreuzer** [comment]
I think you didn't fully get the suggestion here, this is not about tests.

The issue is this line: https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/internal/i18n/LocaleProviderImpl.java#L32

You are setting the locale (that the LocaleProviderImpl will return if no configuration is set) to the default locale at system start. The question is if this is really the best behavior? From my pov, it would be more sensible to specify "LocaleProvider.getLocale()" returns the current system locale, if no specific configuration is set. Currently, the specification is instead "returns the current system locale at startup time, if no specific configuration is set".

**Comment by maggu2810** [comment]
> I think you didn't fully get the suggestion here, this is not about tests.

This has been realized by me. 
That is the reason I written:

> And last but not least, the Locale.setDefault() will work only as long as there is no configuration injected. If this is the case, the default locale is not used anymore.

If it returns the default locale a LocaleProvider.getLocale() will return all the time the value that could be changed by Locale.setDefault(). But this does only work as long as no configuration admin is used. If someone sets the locale configuration the Locale.setDefault() will not be work anymore.

That is the reason, I am using it just for initialization on the very beginning and do not use it on runtime anymore, because the locale provider service should be configured to change the locale and not the underlying JVM (at runtime).

**Comment by maggu2810** [comment]
The reason for the LocaleProvider has also been to not use Locale.setDefault(), because it will change the locale for all non-ESH bundles that are using Locale.getDefault(). And as ESH is not aware of all the other bundles a product using the ESH framework is running in its OSGi framework, I would prefer if the ESH-framework does not touch the default locale.

**Comment by tomhoefer** [comment]
I think if someone uses the configuration to set the locale he will be aware of that the LocaleProvider will not provide the default locale any longer.

I still prefer that the LocaleProvider should not initialize its locale with the default locale.

**Comment by kaikreuzer** [comment]
> because the locale provider service should be configured to change the locale

This would mean that you mandatorily ask for it to be used - but currently, it only requires the configuration optionally (which is imho fine). And the behavior of what locale is provided if no config is available, is currently not specified. And as mentioned above, I think the specification "returns the system default locale" makes most sense.

**Comment by maggu2810** [comment]
I have to search for the discussion before I start the implementation of the service, but IIRC I want to do it because I don't want to use Locale.setDefault with all its side effects for the other bundles anymore. Perhaps I miss-interpret your reply, but I thought you are fine, that we introduced the locale provider and do not rely on setDefault anymore.
If we now add the non-initialized method again, then because someone wants to use it (Locale.setDefault). And I assume if Locale.setDefault is working it is sometime used in the framework again.

**Comment by kaikreuzer** [comment]
So what is your suggestion for the specification on how LocaleProvider.getLocale() behaves, if no configuration is provided?

**Comment by maggu2810** [comment]
That the one I refer to:
https://github.com/eclipse/smarthome/issues/1516#issuecomment-219557992

**Comment by kaikreuzer** [comment]
Your argument is:

> Using setDefault or my proposal doesn't make a bit different, but the example (#1519) allows a separate language for the ESH framework

So with the LocaleProvider you have achieved that purpose (having a separate language for JVM and ESH). I do not see any valid reason to say at the same time that Locale.setDefault is evil and must not be allowed to be used.

**Comment by maggu2810** [comment]
If Locale.setDefault() is used by the ESH framework e.g. some core bundle, didn't it break the separate language for the ESH framework and the remaining bundles in the OSGi framework.

So, how can we offer that purpose if we start using Locale.setDefault again?

Perhaps I missed something here.
My assumption is:
* Locale.setDefault is accepted to change the locale of the LocaleProvider for the ESH framework
* Locale.setDefault will be used (again) in the ESH framework
* All non-ESH framework bundles are affected by that change

**Comment by maggu2810** [comment]
So, to be clear.
I am not against "keep it unitialized and return the value of Locale.getDefault()" in its own.
I am afraid that if this is done, the ESH-framework uses Locale.setDefault and change the locale for non-ESH bundles, too.

**Comment by kaikreuzer** [comment]
>  the ESH-framework uses Locale.setDefault

I think if this is done anywhere (apart from tests), it can be in any case considered as a bug as it would not consider a potential CM configuration, which it has to.
But for tests (like https://github.com/eclipse/smarthome/pull/1714/files), it should be a valid thing to do.

> I am not against "keep it unitialized and return the value of Locale.getDefault()" in its own.

Ok, @tomhoefer would you create an according PR then?

**Comment by tomhoefer** [comment]
Yes, will do
