### ISSUE TITLE
Time conversion not accounting for timezone

### ISSUE THREAD

**Issue by cdjackson** [eclipse/smarthome#1746]
There are some issues with time conversion with charting in HABmin so I traced through the persistence REST resource.

In ```getItemHistoryBean```, ```timeBegin``` is received as ```2016-06-25T18:52:42.362Z```.

On line 142 -:
``` java
dateTimeBegin = convertTime(timeBegin);
```

```dateTimeBegin``` gets converted to ```Sat Jun 25 18:52:42 BST 2016```. This is incorrect - it should have been 19:52 BST.

On my Mac, the time is ```2016-06-26T20:08:22+0100``` when printed using ```date +%Y-%m-%dT%H:%M:%S%z```. This shows that the timezone is set correctly with a one hour difference between BST and UTC so the above conversion appears to be incorrect.

Ultimately, when the conversion into local time is performed back in HABmin, it's out by the timezone period.

**Comment by marcelrv** [comment]
@cdjackson this is what I found working on similar issues last week

For all Types, there is the general assumption that they should be reconstructable from their string representation, i.e. typeX.equals(new TypeX(typeX.toString())) should be true.

This is currently not the case for the DateTimeType, since the toString methods converts from a calendar to a Date Object, removing the timezone information which is contained within the internal Calendar object. (some other info is lost as well, e.g. firstdayofthe week etc)

https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/DateTimeType.java#L41

**Comment by kaikreuzer** [comment]
@cdjackson @marcelrv Can you check that #1747 fixes the issue?

**Comment by sjka** [comment]
While @marcelrv's observation is fully correct, I think here the issue is that the "Z" notation comes from ISO format, while our parser so far could handle only RFC date formats (see also http://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html). 

Therefore I created #1747 in order to try ISO format in case the RFC parsing failed before trying other formats...
