### ISSUE TITLE
Basic UI improvement

### ISSUE THREAD

**Issue by s-simma** [eclipse/smarthome#1818]
icons like: light, door, contact etc. have an icon for open and closed state.
In my opinion it would be very helpfull to have an additional icon for "UNDEF".
(could be a small red x in the icon)
This would allow the user to immediately see, if a device is out of order (if a binding supports this)
What do you think about this ?

**Comment by kaikreuzer** [comment]
This question is not about the Basic UI, but about the [classic icon set](https://www.eclipse.org/smarthome/documentation/features/ui/iconset/classic/readme.html).
This already provides fallback icons (also used for UNDEF state). If you feel that some icon should be changed there, please make a concrete suggestion.

To generally mark them with a red x imho does not make sense, because there is no such state like "out of order" for items. UNDEF simply means that it is currently not clearly known.

**Comment by s-simma** [comment]
@kaikreuzer 
so if i understand you correct this mean for e.g. the icon "light"
ON uses icon "light-on.svg"
OFF uses  "light-off.svc"
Fallback (e.g.UNDEF/NULL) uses "light.svg"
this would be perfect !

But the icon "light-on.svg" is the very same as "light.svg". Is it possible to overwrite "light.svg" with a user defined icon in folder ../conf/icon/basic?

otherwise i would suggest to put a (x) grey, red or wathever to dstinguish the fallback from the "ON" state.
This is the same for "contact", "rollershutter" etc.

**Comment by kaikreuzer** [comment]
> Is it possible to overwrite "light.svg" with a user defined icon in folder ../conf/icon/basic?

Yes, in conf/icons/classic, see https://community.openhab.org/t/available-icons/4088

**Comment by s-simma** [comment]
Works fantastic. Thanks !!
