### ISSUE TITLE
persistence extension missing sumSince

### ISSUE THREAD

**Issue by airix1** [eclipse/smarthome#1843]
Seems this was added in a commit but was then reverted.

[https://github.com/eclipse/smarthome/pull/374/commits]

**Comment by maggu2810** [comment]
Hm, there is no comment why the PR has been closed.
Perhabs @J-N-K, @teichsta or @kaikreuzer can give us some informations what has been wrong about.

**Comment by kaikreuzer** [comment]
See https://github.com/eclipse/smarthome/pull/376#issuecomment-139881518.

@J-N-K didn't want to finish #376, because he waited forever for some of his PRs being reviewed on OH1 and thus he has left the project frustratedly.

So if anyone wants to add sumSince (according to what has been discussed in #376), please do so!

**Comment by watou** [comment]
I will!
