### ISSUE TITLE
Float issue in rule

### ISSUE THREAD

**Issue by jsjames** [eclipse/smarthome#1865]
I've tried to narrow this one down to the simplest example. This code will generate the below error. This issue occurred in 1.8 as well (was hoping 2.0 would address).

var float a = 10.0
var float b

a = a - 2.0
b = a \* 2.0

2016-07-14 17:14:00.031 [ERROR] [ntime.internal.engine.ExecuteRuleJob] - Error during the execution of rule Float Test: An error occured during the script execution: Could not invoke method: org.eclipse.xtext.xbase.lib.FloatExtensions.operator_multiply(float,double) on instance: null

**Comment by htreu** [comment]
The error comes from an illegal xbase/xtext script:
The variables `a` and `b` are defined as type float. The literal numbers `10.0` and `2.0` are of type double. Despite that the first assignment may already fail, the 2nd assignment to `a` does switch the type of `a` to double (since `float - double = double`) and the assignment to `b` fails since the xbase parser resolved the operation as `float * double = double` but fails to call it with both parameters being double values.

Using the Eclipse SmartHome Editor shows a syntax error which specifically points you to this:

<img width="259" alt="upload" src="https://cloud.githubusercontent.com/assets/1729268/25854010/e112e012-34ce-11e7-883b-cac0d9fcf6b9.png">

The correct way to deal with this is either to define the literals as floats (like `10.0f` and `2.0f`) or define `a` and `b` as double variables.

**Comment by htreu** [comment]
@sjka pls close.
