### ISSUE TITLE
Hue binding: initialization incomplete

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#1880]
Hue binding initialization is sometimes incomplete. This can be seen because when it occurs, light properties are not set.
I am investigating. It could be or not a consequence of my change done in file HueBridgeHandler by PR #1870.

**Comment by afuechsel** [comment]
@lolodomo Since you removed the code from HueBridgeHandler#onConnectionResumed, that looped through all connected children to initialize their properties and added the code to onBridgeStatusChanged, this could lead to this situation; as this callback is called from the ThingManager but the polling loop in the binding has not yet discovered all connected lights with their ids therefore your initialization was too early.

**Comment by lolodomo** [comment]
@afuechsel : did you encounter the problem ?
If onBridgeStatusChanged is called early,, nothing is initialized because the bridge is not ONLINE. The bridge state switches to ONLINE in HueBridgeHandler#onConnectionResumed and this triggers calls to onBridgeStatusChanged with an ONLINE bridge and so a real first initialization of lights.

**Comment by lolodomo** [comment]
This issue is closed by PR #1899.

@afuechsel : I will reopen issue #1869 if you are sure that my PR #1870 has really broken something.

**Comment by afuechsel** [comment]
Ok, if #1899 fixes it I am fine. Didn't have the time to recheck this issue yet, just thought, it is still open.
