### ISSUE TITLE
BaseThingHandlerFactory needs config.core

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#1883]
It is not a real problem, just want to know if this has been done by intention...

We "declared ConfigValidationException as RuntimeException in order to avoid indirect dependency on org.eclipse.smarthome.config.core.validation for bindings" (PR #1287, comment #1149)

The BaseThingHandlerFactory that the most handler factories are based on, brings a dependency to the config.core bundle.

I add a test binding here:
https://github.com/maggu2810/smarthome/commit/b6afbe99f2f21a6735ed104620a1798c16e08f3c

If you remove "org.eclipse.smarthome.config.core" from the bundle's manifest and open the class "TestHandlerFactory" (that extends BaseThingHandlerFactory), you will see, that the IDE reports an error here.

So, if we are fine with that, this issue could be closed.
If we do not want a hard dependency to config.core if BaseThingHandlerFactory is used, something needs to be changed.

**Comment by kaikreuzer** [comment]
Since our [archetype has this dependency](https://github.com/eclipse/smarthome/blob/master/tools/archetype/binding/src/main/resources/archetype-resources/META-INF/MANIFEST.MF#L12) since the beginning, I would say all is fine.
In #1287, we only wanted to avoid having to depend on validation stuff although it might not be needed. But config.core contains all the ConfigDescription business, which is more or less mandatory for everyone.

**Comment by maggu2810** [comment]
Thanks for clarification.
