### ISSUE TITLE
Bundle sometimes started several times

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#1959]
Somestimes, I can see at startup that my Powermax bundle (1.x binding) is started several times:
```
10:59:09.502 [INFO ] [b.core.service.AbstractActiveService] - PowerMax Refresh Service has been started
10:59:09.507 [INFO ] [b.core.service.AbstractActiveService] - PowerMax Refresh Service has been started
10:59:09.509 [INFO ] [b.core.service.AbstractActiveService] - PowerMax Refresh Service has been started
10:59:10.499 [INFO ] [ng.powermax.internal.PowerMaxBinding] - PowerMax alarm binding: serial connection (/dev/ttyUSB1): connected
10:59:12.361 [INFO ] [ng.powermax.internal.PowerMaxBinding] - PowerMax alarm binding: serial connection (/dev/ttyUSB1): disconnected
10:59:12.361 [INFO ] [ng.powermax.internal.PowerMaxBinding] - PowerMax alarm binding: serial connection (/dev/ttyUSB1): disconnected
```

**Comment by watou** [comment]
Might this be an issue to solve in the binding, or have you seen a similar issue in other 1.x bindings?  I see above [this line](https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/PowerMaxBinding.java#L445) that you are taking action on the `updated()` method when `config` is `null`, which might be related.  

Would it be better to track this in https://github.com/openhab/openhab/issues instead of here, until it's determined to be an ESH issue?

**Comment by kaikreuzer** [comment]
This is not related to ESH, since ESH does not even support openHAB 1.x bindings.

Probably best to report at https://github.com/openhab/openhab-distro, but it would be helpful if you first further analyze whether it is specific to this bundle .

**Comment by lolodomo** [comment]
@watou : that's right, I think I have seen that only for the Powermax binding.
In fact it does not happen very often.
In fact, I am taking actions when config is not null but not when null. Do you think I should add this when config is null ?
```
`this.setProperlyConfigured(false);
```

**Comment by watou** [comment]
> but not when null

The binding is taking actions on [lines 430-443](https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/PowerMaxBinding.java#L430) regardless of `config` possibly being `null`.

> Do you think I should add this when config is null ?

I think the binding should completely ignore calls to `updated()` when the `config` parameter is `null`.
