### ISSUE TITLE
Paper UI: Item creation broken

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#2009]
With the recent master I am not able to add a new item (http://127.0.0.1:8080/ui/index.html#/configuration/item/create) anymore.
The "+" is grey, not white (`name` given and `type` chosen)

commit id: c196f1fd13c92aba1626ab13c8991520f956f765

**Comment by kaikreuzer** [comment]
@aounhaider1 Could you please check?

**Comment by aounhaider1** [comment]
I found the reason for above behaviour and have fixed it but I still am unable to add normal items. It gives an Internal Server Error. I debugged it and the problem seems to be here when we dont send groupNames and tags (we are not sending tags from PaperUI) https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/dto/ItemDTOMapper.java#L65. @maggu2810 can you please check this?

**Comment by maggu2810** [comment]
> I found the reason for above behaviour and have fixed it

@aounhaider1 Can you give me a link to your branch

**Comment by aounhaider1** [comment]
Here it is:
https://github.com/qivicon/smarthome/tree/bug-create-item

**Comment by maggu2810** [comment]
@aounhaider1 Have a look at #2012

**Comment by kaikreuzer** [comment]
#2012 is merged - @aounhaider1 Could you please test it and create a PR?

**Comment by aounhaider1** [comment]
Yes, https://github.com/eclipse/smarthome/pull/2012 solves the item creation issue.
