### ISSUE TITLE
LIFX Binding White and Colour Light brightness channel issues (raspberry pi)

### ISSUE THREAD

**Issue by rocket59** [eclipse/smarthome#2031]
1) Color light 

Since moving from binding snapshot 0.8 to 0.9 the brightness slider in the color channel no longer works properly (with the Original bulbs) in paperui.

Moving the slider in the Control Tab causes erratic behaviour in the lamp brightness. Exiting the Control Tab and re-entering the tab will see the slider at the correct position for the actual brightness level, but erratic slider control persists.

The slider was working correctly in 0.8.

2) White Light 

The on/off button in the brightness channel disappears on cold restart of the pi. Reinstalling the thing solves the issue.

**Comment by kaikreuzer** [comment]
This sounds to me like https://github.com/eclipse/smarthome/issues/1778, which has been fixed a while ago. Are you sure that you are using the latest code?

**Comment by rocket59** [comment]
I believe so, have had this issue since early August. I'm currently using build #454 of OH2.

**Comment by kaikreuzer** [comment]
@kgoderis Can you reproduce this issue?

**Comment by kgoderis** [comment]
I have troubles reproducing it but that is due to my environment. paperUI is not able to render the '000 of things I have in the Control tab. pfff.... I never use the paperUI so I have to test it from scratch, but I am a bit confused: @rocket59 the colorlight only has a color and temperature channel, e.g. wdym with brightness slider?

Now, I did some testing with the colorpicker slider in the classic UI, and when I switch a light OFF I get:

18:20:05.107 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'LivingRoomLIFXLeft' received command OFF
18:20:05.111 [INFO ] [marthome.event.ItemStateChangedEvent] - LivingRoomLIFXLeft changed from 39.996337890625,1,100 to 39.996337890625,1,0
18:20:05.437 [INFO ] [marthome.event.ItemStateChangedEvent] - LivingRoomLIFXLeft changed from 39.996337890625,1,0 to 39.996337890625,1,100
18:20:05.843 [INFO ] [marthome.event.ItemStateChangedEvent] - LivingRoomLIFXLeft changed from 39.996337890625,1,100 to 39.996337890625,1,21
18:20:07.596 [INFO ] [marthome.event.ItemStateChangedEvent] - LivingRoomLIFXLeft changed from 39.996337890625,1,21 to 39.996337890625,1,0

and when switching ON

18:21:03.750 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'LivingRoomLIFXLeft' received command ON
18:21:03.754 [INFO ] [marthome.event.ItemStateChangedEvent] - LivingRoomLIFXLeft changed from 39.996337890625,1,0 to 39.996337890625,1,100
18:21:03.850 [INFO ] [marthome.event.ItemStateChangedEvent] - LivingRoomLIFXLeft changed from 39.996337890625,1,100 to 39.996337890625,1,0
18:21:04.513 [INFO ] [marthome.event.ItemStateChangedEvent] - LivingRoomLIFXLeft changed from 39.996337890625,1,0 to 39.996337890625,1,100

Something is not Ok here, as brightness is bouncing between 0 and 100

mmh... not good. :-(

On the white light : I can not comment on that as I only have color lights

**Comment by rocket59** [comment]
> the colorlight only has a color and temperature channel, e.g. wdym with brightness slider?

@kgoderis Sorry for the late response. I meant that the control interface within paperui, the color channel has 3 inbuilt sliders (for color, brightness and saturation). The brightness slider is unable to correctly control the dimming level for the bulb.

**Comment by kgoderis** [comment]
@rocket59 I am unable to use paperUI in my setup so hard to comment. I thought the paperUI generated a slider for each channel defined in the Thing; saturation is not one of them. Maybe I am missing something here.

**Comment by kaikreuzer** [comment]
@kgoderis The Paper UI renders three sliders for a "Color" item/channel, one for hue,saturation,brightness.

@rocket59 I cannot reproduce your issue. Using the current code, I can use all 3 sliders and my LIFX reacts as expected to all of them.

**Comment by kaikreuzer** [comment]
I assume this does not occur anymore with the latest LIFX refactoring
