### ISSUE TITLE
Thing properties are neither persisted nor fully transient

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#2051]
As it seems, #1682 does not deliver what the title promises: it only never persists any property _changes_. However, when a thing initially is created (e.g. by ```Inbox.approve(...)```), then the properties are initially persisted. An can never be changed again. That's surprising, but at least consistent with the documentation ("Note, that in contrast to configuration updates, property changes are never persisted.").

Based on the #1682, I would habe expected them to become completely transient, i.e. not persisted at all.

What's the idea here?

**Comment by kaikreuzer** [comment]
#1682 was only about allowing bindings to do (non-persistent) modifications. It did not mean to completely remove persistence of properties. They can still be defined through the inbox and e.g. the Rest API and this imho makes a lot of sense this way.

**Comment by markusjw** [comment]
What is then the solution to pass temporary information from the inbox to the binding? In that case it is sad that the binding cannot delete properties defined by the inbox.

**Comment by kaikreuzer** [comment]
I cannot provide any solution, since this was never a requirement. And "passing information" rather sounds like a misuse of the properties, so it might be a good thing that this isn't possible anymore and that a proper solution should be discussed :-)
Could you elaborate a bit on your use case?

**Comment by markusjw** [comment]
The use case is as follows:
The discovery process has some information that the specific thing handler needs when initializing the first time. As this information is thing-specific, my solution was to store it as a flag at the thing using a temporary thing property.
Unfortunately, the property is not temporary because it is persisted once and cannot be removed later. The problem that follows is that the property is still there when initializing the handler after an ESH restart.

**Comment by sjka** [comment]
Thanks for the description of what you want to do. Nevertheless, it is still unclear to me why these properties are only available during discovery and why they must be removed later on. This sounds a bit surprising, as the `ThingHandler.initialize()` in bindings usually always behaves in the same way: it initiates the communication with the device, regardless of the fact if it's talking to it for the first time or not.

**Comment by markusjw** [comment]
My discovery mechanism can find devices that exist already (in the system, not as thing) and devices that are completely new. New devices need to be included into the system at the first thing handler start, the others don't.
So this is thing specific information that is only needed at the first handler initialization.

**Comment by kaikreuzer** [comment]
I invite @cdjackson to this discussion as he imho did similar things for Z-Wave.
I would think that it is not necessary to pass any "new flag" through the discovery service - instead, the binding can store information about "known" devices in a persistent store and thus can identify whether a Thing is newly added or not. That's how you deal with it, @cdjackson, am I right?

**Comment by cdjackson** [comment]
The use case here sounds similar to what I do in ZWave. I don't use a persistent store though (I think we discussed this, but it wasn't implemented in the end).

When a thing is discovered, I store a bunch of properties in the inbox thing that allow me to decide the thing type. During discovery these can be added to if I discover more information. When devices are added to the inbox, they are all added with the same type (zwave:device I think). The main reason for this is so that I don't need to resolve the thing type at the point they are added to the inbox since I may not have read all the properties required to decide the thing type at that stage - in zwave this can take a long time - for battery devices, it could be hours (!!).

When the thing handler is initialised, I read the properties back and then change the device type if it can be resolved. Each time the binding starts it does this check (just in case something changes).

I don't delete the properties as they are useful for later use.

**Comment by markusjw** [comment]
@cdjackson Thanks for the explanation. The difference is that in your case the information is not just useful/correct once but these are really properties that can remain unchanged.

@kaikreuzer Also thanks for the discussion. Yes, I can store this information in the bridge handler. However, I still think it would be cleaner to store it in the thing since it is one flag per thing.

Summing up:
- There is no solution to store temporary info in the DiscoveryResult/Thing
- This ist not seen as a requirement, either.

**Comment by kaikreuzer** [comment]
> However, I still think it would be cleaner to store it in the thing since it is one flag per thing.

Remember that Things can also be defined in other places, like the DSL files and thus they are read-only. So what meaning would such a flag have if it cannot be changed? And what would the user be expected to put in there? This does not really fit well into the architecture.

If you are ok with the suggestion above and this is not blocking for you, I'd close this issue at that point.

**Comment by cdjackson** [comment]
> The difference is that in your case the information is not just useful/correct once but these are really properties that can remain unchanged.

Some properties remain unchanged - the explanation I used above was for the device discovery since I thought that was the use case, but there are a number of other properties that I update regularly...

**Comment by markusjw** [comment]
@kaikreuzer  OK
@cdjackson Yes, you can change properties and the changes are not persisted. The strange thing is that  properties added to the DiscoveryResult **are persisted once** and you can never persist changes to those initial values either.

**Comment by cdjackson** [comment]
> Yes, you can change properties and the changes are not persisted. The strange thing is that properties added to the DiscoveryResult are persisted once and you can never persist changes to those initial values either.

Really? If that's correct then that's a big problem isn't it? We just added some additional functions to allow the binding to read the inbox entry properties so they can be updated. I had assumed the updates were being persisted, and if not I think it should be...

**Comment by kaikreuzer** [comment]
You should not mix up the "discovery api" and the "binding api", these are actually two separate apis. Discovery can create and update discovery results. Once a result is approved, it becomes a Thing and at that moment its information is "frozen", like if it were defined in a DSL file (or coming from any other ThingProvider). ThingHandlers can therefore only make changes to it that are transient.
