### ISSUE TITLE
io.rest sometimes throws a NCDFE

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#2066]
io.rest declares its dependency to io.transport.mdns as optional. If the dependency is not resolved, this can result in NCDFEs:
```
16:21:39.652 [ERROR] [org.eclipse.smarthome.io.rest       ] - FrameworkEvent ERROR - org.eclipse.smarthome.io.rest
java.lang.NoClassDefFoundError: org/eclipse/smarthome/io/transport/mdns/MDNSService
	at java.lang.Class.getDeclaredMethods0(Native Method)[:1.8.0_40]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)[:1.8.0_40]
	at java.lang.Class.getDeclaredMethods(Class.java:1975)[:1.8.0_40]
	at org.apache.felix.scr.impl.helper.BindMethod.getServiceObjectAssignableMethod(BindMethod.java:454)
```

**Comment by maggu2810** [comment]
As you already know the mDNS part is used to publish the REST interface.

I already moved the logic to a separate bundle and used an enhanced logic, so it also respects http(s) port configuration that is done by configuration admin.
I already send you a link some time before, but my code cannot be merged because it is using Bnd, Java8 etc.

So what are your ideas for ESH?

**Comment by kaikreuzer** [comment]
I didn't think about a solution yet. Two possibilities I see:
1. Make the dependency mandatory
2. Move the MDNSAnnouncer to a new bundle io.rest.mdns

What are your ideas for ESH?

**Comment by maggu2810** [comment]
Your point "2" (+ point "1" for the new bundle) :wink:

**Comment by kaikreuzer** [comment]
Ok, will try to do it this week then!
