### ISSUE TITLE
Paper UI renders switches with state options

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#2149]
I have a Switch item ("Switch Plug" in demo.items), which is linked to a switch channel of a Thing.
This is what the Paper UI renders:

![bildschirmfoto 2016-09-09 um 11 36 00](https://cloud.githubusercontent.com/assets/3244965/18382521/99ee1dd4-7681-11e6-90f7-3b708fa5d33b.png)

It used to be a toggle in the past.

**Comment by aounhaider1** [comment]
Are you sure that the option array is empty in channelType? The dropdown is shown only when there are some options in channelType.

**Comment by kaikreuzer** [comment]
Ah, many thanks! That is indeed a bug in the Z-Wave binding...

**Comment by cdjackson** [comment]
@kaikreuzer why aren't options allowed on a switch?  The ESH categories defines many items as switches, but ON/OFF states are not always appropriate. While a toggle might be the suitable representation in the case of a light switch, what about the state of a door state - maybe someone wants to show open/closed. Or what about if you're just displaying a state and want "On" or "Off". Shouldn't options should be permitted, and then rendered?

**Comment by kaikreuzer** [comment]
@cdjackson Yes, options are permitted in case they are true. Note that I kept all your alarm "Switch" channels in place with options (saying "Ok" and "Alarm"). But this channel type that I fixed is the "generic" power switch and for this a toggle is definitely the right widget - a drop down does not make sense. 
Btw, the options were even wrong, they sent "On" and "Off" instead of "ON" and "OFF".

**Comment by cdjackson** [comment]
I don't disagree that toggle is a perfect representation for the widget - for sure. 

My question is really if PaperUI shouldn't provide a toggle control even when options are provided. Ie the logic in PaperUI could have been that any control with type switch, use the toggle even if options are provided.  This would have allowed options to be specified, such that if someone used a text widget sitemap, it could be presented using the options.

**Comment by kaikreuzer** [comment]
I think there is no general right answer, since we do not have the flexibility here as when using sitemaps where the user can specify whether he wants toggles or selection options instead.
As Paper UI is mainly for setup&testing the devices, I think it makes sense to show the option texts, if they are available - rendering a toggle would suppress this information, so you would not have a chance to see whether the options are correctly working.

**Comment by cdjackson** [comment]
This issue means that the state descriptions now influence the widgets - this doesn't seem right to me. I really think that people should be able to specify a state description for a switch.

>  I think it makes sense to show the option texts, if they are available - rendering a toggle would suppress this information, so you would not have a chance to see whether the options are correctly working.

Maybe, but you're telling me that in order to make the widget work in PaperUI, I'm not allowed to have state descriptions, so they aren't rendered anyway.

Let's leave it as it is untill after the next beta, but I think this logic is wrong. State descriptions should provide additional information that can be used in the UI, but the UI should be able to able to decide to render what it thinks is best with the various bits of information it has available.

**Comment by kaikreuzer** [comment]
The Paper UI treats the state options like the Classic UI behaves when it finds "mappings" defined; if there is no special information (On/Off simply does not provide any additional info), this should be omitted.

As I said, this is only the case for the Paper UI, which is meant for administrative purposes and NOT for operation. On any other UI, the user can (e.g. through sitemaps) decide how it should be rendered.

**Comment by cdjackson** [comment]
> On/Off simply does not provide any additional info

But it does since by adding these states into the system, it can be internationalised. It can also be On/Off rather than the actual ON/OFF enum states.

> As I said, this is only the case for the Paper UI, which is meant for administrative purposes and NOT for operation

Sure - fully appreciate that, and again, the system should allow state descriptions to be added. Just because PaperUI doesn't support them is not a good reason to remove them (IMHO anyway).
