### ISSUE TITLE
Add documentation URL to binding.xml

### ISSUE THREAD

**Issue by wborn** [eclipse/smarthome#2353]
A lot of bindings have their own wiki page that contain lots of useful information. I think adding the URLs to these in `binding.xml` could help in several ways:

* in Paper UI a hyperlink could be created to the binding wiki page
* the URLs can be used in automatically generated documentation

People could cleanup their wiki bookmarks and don't have to update them when they get relocated some day. Also after installing a binding they would immediately know where to find more information.

Something similar could be done for forum URLs or creating issues. Though these typically share the same URLs depending on which project they reside in.

**Comment by kaikreuzer** [comment]
Wiki pages are only used in openHAB 1, for ESH the agreed way of [documenting a binding](https://www.eclipse.org/smarthome/documentation/development/bindings/docs.html) is to keep it with the sources, so that it is also versioned with them.
It is then up to the solution to include this into their own documentation - there should be no hardcoded urls anywhere.
