### ISSUE TITLE
Thing stays in INITIALIZING state if initialize() failed once

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#2582]
Scenario:
I create a Thing with a wrong configuration that makes the handler's initialize() method throw an exception (in my case an IllegalArgumentException()).
It is questionable whether this is allowed for the implementation or not - I would say this should not happen, instead the thing status should be set accordingly.
But in any case, this situation (due to a bug) is irrecoverable, because if I now correct the configuration and thus a "Thing update" occurs, the ThingManager logs:
```
14:34:31.193 [WARN ] [ome.core.thing.internal.ThingManager] - Attempt to initialize a handler twice for thing 'lifx:colorlight:30531ecf' at the same time will be ignored.
```
which means that it will never ever again try to initialize my handler - this looks like a bug to me.

**Comment by sbussweiler** [comment]
Can you re-test your mentioned behavior with this [branch](https://github.com/qivicon/smarthome/tree/fixed-thing-update)?

**Comment by lolodomo** [comment]
What would happen if the thing handler initialization exits in timeout ?

**Comment by sjka** [comment]
> What would happen if the thing handler initialization exits in timeout ?

Nothing really. The TimeoutException does not EXIT the initialization, but only makes the rest of the framework continue doing its job. The initialization runs in a separate thread and will continue running anyway. Maybe we should be more clear in the warning message that we print to the logs.

It's the ThingHandler's duty to set the Thing to ONLINE or OFFLINE at the end of the initialization. So since the thread keeps running, this will eventually happen - unless there is a bug in the ThingHandler.initialize(), of course.

**Comment by lolodomo** [comment]
You mean the thing handler init is not interrupted after 5 seconds ?

**Comment by sbussweiler** [comment]
> You mean the thing handler init is not interrupted after 5 seconds ?

Exactly.

**Comment by lolodomo** [comment]
I have since ages an issue with the astro binding that is sometimes remaining in INITIALIZING state. I hope that it could be due to the same reason.
When I run in the console a bundle:stop and then a bundle:start, I got this error:
```
18:30:48.963 [WARN ] [ome.core.thing.internal.ThingManager] - Thing handler for thing 'astro:sun:local' already registered
```
and the thing is remaining in INITIALIZING state.
I even tried to uninstall the astro feature and install it again (through the console) and same result and same warning.

**Comment by sjka** [comment]
@sbussweiler nope. 

It will detect it's `INITIALIZING` already [here](https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java#L611) and only print a warning like this:

```
09:51:07.731 WARN  o.e.s.c.t.i.ThingManager[:615] - Attempt to initialize a handler twice for thing 'lifx:colorlight:dec12c25' at the same time will be ignored.
```

**Comment by sjka** [comment]
btw, the LIFX binding is... well, let's say *a little special*...:

```java
    @Override
    public void initialize() {
        try {
            // ...
        } catch (Exception ex) {
            logger.error("Error occured while initializing LIFX handler: " + ex.getMessage(), ex);
        } finally {
            lock.unlock();
        }
    }
```

**Comment by sjka** [comment]
see #2597

**Comment by sbussweiler** [comment]
The framework is starting the handler initialization for an updated thing, if the handler is not initialized. See #2599.
