### ISSUE TITLE
Push Jetty to 9.3+

### ISSUE THREAD

**Issue by kgoderis** [eclipse/smarthome#2592]
For some reason I can not find back earlier discussion on migration to Java 8, but I was wondering if this is the mean reason of not adopting Jetty 9.3.x? We are currently with 9.2.12 in the target platform definition.

I would need Jetty 9.3 for the ACME protocol implementation, as Jetty 9.3 supports Server Name Indications (SNI) during TLS/SSL negotiation.  This allows the key store to contain multiple server certificates that have a specific or wild card domain(s) encoded in their distinguished name or by the Subject Alternate Name X.509 extension. However,  the SNI extension reliance on a Java 8 API and the and TLS ciphers that are only available in Java 8. Behind all this is the fact that ACME has a TLS-SNI challenge specification that allows one to renew certificates through https, instead of a plain vanilla http challenge/connection. By supporting renewal via https, once certificates are installed, an ESH instance can - for security reasons - redirect incoming http traffic to the jetty https engine

**Comment by maggu2810** [comment]
If we bump Jetty in the target platform of ESH and begin to use Jetty 9.3+ features in ESH bundles, then every product that would like to use that recent ESH bundles needs to bump Jetty, too.
I don't know if this is such an easy task for everybody.

For the ones that are using Karaf and Pax Web a bump to Pax Web 6.0.x would be necessary to use Jetty 9.3.5.v20151012. Pax Web 4.2.x uses Jetty 9.2.x. See e.g. http://ops4j.github.io/pax/web/SNAPSHOT/
Another option for Karaf based products would be to use a custom Jetty integration...

I assume that a bump of the ESH target platform is not such an easy task as to bump it for a specific product e.g. openHAB.

Perhaps the situation is a little bit different for Jetty because it is not a core feature but an additional one (WRT e.g. the requirement to not use any feature that is not available in OSGi R4.2). I am pretty sure @kaikreuzer could clearify this.

**Comment by kaikreuzer** [comment]
As @maggu2810 says, changing the ESH TP wouldn't help you. The Jetty in the ESH TP is only used to have an HTTP server available when developing in the IDE. Every solution is free to choose an OSGi 4.2 compatible HttpService.

Note: I once (more than a year ago) tried to update the TP to Jetty 9.3, but unfortunately, the Jetty guys didn't take the effort anymore to provide all its dependencies in Eclipse Orbit, so I miserably failed in the upgrade due to unresolvable dependencies...

**Comment by kgoderis** [comment]
@kaikreuzer @maggu2810 Ok, that is pretty clear. I can stick to http challenges for ACME (e.g. 9.2.x), it is just a little less secure, but I will document that for end users. Those not wanting to expose their complete OH instance via http will then still need to rely on nginx or equivalent to split/redirect streams

**Comment by kaikreuzer** [comment]
Ok, so I close this issue here.
@kgoderis FYI: Karaf 4.1 will use Pax-Web 6, see https://issues.apache.org/jira/browse/KARAF-4093. Official release date is 11/2016, but they seem to be a little behind their schedule ;-)

**Comment by kgoderis** [comment]
@kaikreuzer Do we intend to use Pax-Web 6 in ESH/OH?

**Comment by kaikreuzer** [comment]
Not ESH as explained above. But OH2 will always try to use a current version of Karaf, yes.

**Comment by kgoderis** [comment]
Mhh... since we have some servlets in ESH, and some in OH2, should they not be treated equally wrt HttpService manipulations and so forth? Potentially, we can  influence HttpService from OH2 which might not be desired for the ESH servlets. Let's see what Pax-Web 6 will offer additionally

**Comment by kaikreuzer** [comment]
ESH servlets should work on any OSGi HttpService. OH2 servlets are free to use features of Jetty.

**Comment by maggu2810** [comment]
> I once (more than a year ago) tried to update the TP to Jetty 9.3, but unfortunately, the Jetty guys didn't take the effort anymore to provide all its dependencies in Eclipse Orbit, so I miserably failed in the upgrade due to unresolvable dependencies...

If we don't care to add some stuff to the p2 third party repo that is generated using Maven artifacts, too, I don't think it is too much work (I already use a bndtools + Maven Repo only launch config that uses also Jetty - at the moment still 9.2.x).

**Comment by maggu2810** [comment]
> @kgoderis FYI: Karaf 4.1 will use Pax-Web 6, see https://issues.apache.org/jira/browse/KARAF-4093. 
> Official release date is 11/2016, but they seem to be a little behind their schedule ;-)

Perhaps we will see it at the end of the year: https://lists.apache.org/thread.html/bd8ba20671c3ed50f32b626907068d40738f03df20bc83d2f3494340@%3Cdev.karaf.apache.org%3E

**Comment by maggu2810** [comment]
FYI: Karaf 4.1.0 is out
