### ISSUE TITLE
Paper UI: Filtering mechanisms for Item list

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#2614]
Currently, the Item list is a flat list and if there are many items defined, it is almost unusable, because the user cannot find the one(s) he is looking for.

I would therefore suggest the introduction of some clever search and filter mechanism:

- There should be a free-text search field at the top, similar to what we have on the Extensions tab.
- It should be possible to filter for items that belong to a specific GroupItem. For this, a selection box with GroupItems could be provided.
- If a GroupItem is selected, it should automatically set the filter for this GroupItem.
- Selecting an Item should hence NOT go to the edit page anymore - instead, an "edit" button should be introduced, similar to what we have on Things.
- Another filter for item types could be added, next to the group filter.
- To quickly get rid of the filters, there must also be a "clear filter" button somewhere.
- When clicking the "+" icon for creating a new item, the current settings of item type and GroupItem should be respected, i.e. the item creation page should be pre-filled with the type and having the group item listed as a parent group.

**Comment by kubawolanin** [comment]
For what I have seen PaperUI is using Angular Material framework. 
I may suggest using [md-autocomplete](https://material.angularjs.org/latest/demo/autocomplete) component instead of [md-select](https://material.angularjs.org/latest/demo/select).
I'm involved in HABPanel more nowadays (need to finish a few things I'm working on), but I may jump in later on.
