### ISSUE TITLE
Tests for org.eclipse.smarthome.core.voice

### ISSUE THREAD

**Issue by m-memova** [eclipse/smarthome#2655]
I would like to implements some tests for the org.eclipse.smarthome.core.voice bundle (mainly for the VoiceManager) and I was wondering if someone is planning some significant changes there. 
In addition, while I was examining the code I could not find out how the KSEvent-s and STTEvent-s occur.
There are methods which handle them (in the DialogProcessor class) but how are they fired?
Any help is appreciated.

Regards,
Mihaela

**Comment by kaikreuzer** [comment]
Hi @m-memova! No, there are no substantial changes planned.

The KSEvent-s and STTEvent-s are fired by implementations of KSService and STTService (they take KSListeners resp. STTListeners as an argument, DialogProcessor implements those two interfaces).

Unfortunately, there is no implementation of KSService nor STTService within ESH yet - so you won't find any code where this is used. It probably also won't make sense to cover these features by tests yet, because I expect changes to the APIs once there are service implemenations coming.

**Comment by m-memova** [comment]
Thank you, @kaikreuzer! I assumed it's something like that but I wanted to be sure. Meanwhile, while I was playing with the Paper UI and the console, I noticed something else: when I tried the command "say %itemName%", I got an error message on the console (for bad expression). But according to the code that should return the item's state. Could you please take a look? Am I doing something wrong or should I open an issue about that?

**Comment by kaikreuzer** [comment]
> Could you please take a look? Am I doing something wrong or should I open an issue about that?

I've not tested that, but it would be nice to see it working.
@lolodomo Have you ever tried that?
@m-memova Feel free to open an issue if it isn't working as expected, thanks!

**Comment by lolodomo** [comment]
No, I have never tried that, I even did not know it was an available feature. But I can try later to day and confirm if that fails for me too.

**Comment by lolodomo** [comment]
@m-memova : you're right, I see the corresponding code. Do you get an error in the console ?
What happens with this command: smarthome:voice say The state is %itemName%
Do you get at least the first part of the message ?

**Comment by lolodomo** [comment]
I am not sure but I think this line is not correct: https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core.voice/src/main/java/org/eclipse/smarthome/core/voice/internal/VoiceConsoleCommandExtension.java#L105
I think it should be:
'''
String itemName = word.substring(2, word.length());
'''
rather than:
'''
String itemName = word.substring(1, word.length() - 1);
'''

**Comment by m-memova** [comment]
I think that line is correct. The substring begins with the character at the specified index and extends to the end of this string or up to endIndex – 1, if the second argument is given. So if String word = "%itemName%", word.substring(1, word.length() - 1) returns "itemName".

**Comment by lolodomo** [comment]
https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#substring(int,%20int)
You're right, index is starting at 0 and not 1.

**Comment by m-memova** [comment]
And I tried the `smarthome:voice say The state is %itemName%` on the console but I got the same message : "Error executing command: bad expression: %itemName%". I did not get the first part of the message.

**Comment by lolodomo** [comment]
It looks like %itemName% breaks the Karaf console command and our code is even not reached.

**Comment by lolodomo** [comment]
Maybe % has to be escaped ?

**Comment by m-memova** [comment]
Thank you, @lolodomo, you are right! It works :-)

**Comment by lolodomo** [comment]
How did you escape it ?

**Comment by m-memova** [comment]
`smarthome:voice say \%itemName\%`
Now I get an error message that the item does not exist which is also weird, but I will figure it out.

**Comment by lolodomo** [comment]
@m-memova : be careful, that is a pattern, so for example if your item name contains a "-", you should escape it.

**Comment by sjka** [comment]
#2860

**Comment by maggu2810** [comment]
Can we close this one now?
