### ISSUE TITLE
Module outputs are not available in scripts

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#2849]
The values of outputs of other modules are made available to script, which is also directly supported by the rule editor:

![screen shot 2017-01-18 at 10 15 23](https://cloud.githubusercontent.com/assets/3244965/22057952/507b7474-dd67-11e6-88b9-7b4b69045d65.png)

When trying to access those outputs, an exception is thrown.

The problem is that in the rule context, they are made available as e.g. "1.newState", which is provided as a map 1->newState in within the rule execution context. It is probably rather a bad idea to define "1" as a variable name...

**Comment by danchom** [comment]
The keys of outputs in rule context are in form "moduleId.outputId". Here  "1.newState" the 1 is the moduleId. If you have modules of the same module type (they will have same output uids), what "newState" of which will you get?

**Comment by kaikreuzer** [comment]
See https://github.com/eclipse/smarthome/pull/2850#issue-201521946.

**Comment by danchom** [comment]
ok but if you have 2 item modules
print(context.get('1.newState')) - will return the state of the first one
print(context.get('2.newState')) -  will return the state of the second one
print(newState) - what will return this? State of the first or the second item?

**Comment by kaikreuzer** [comment]
> what will return this?

Undefined, it might be the one or the other. That's why you should use the other option in case you have the same output id twice.

**Comment by danchom** [comment]
For me, the right way here, is to use inputs in script module and the script must be write using them. In that way the scripts can be reused and will not depend on state of the system (The inputs always will be available, the outputs of other modules can missed). Btw the inputs are also in available in rule context under their names.

**Comment by kaikreuzer** [comment]
@danchom We discussed that already a long time ago: You are mixing up users with developers here.
Only developers have a chance to define a module TYPE (on which they could declare inputs that their script needs). But the usecase at hand here is for the (expert) end user: He uses the existing "ScriptAction" and can get hold of the rule context to do fancy stuff. Note that this "user" feature has been introduced a long time ago already and the Paper UI supports offering the outputs since a few months. And imho, this is a very neat feature for the end user.

What you are talking about are rather "scripted action types" - this is something that will be addressed with https://github.com/eclipse/smarthome/pull/1783. And yes, there you would clearly define inputs for your scripted type, so that you can easily match it etc. But this means that the script is part of the module type and not of the module itself.

**Comment by danchom** [comment]
May be I was not clear, I'm not talking about #1783. My proposal was to add some numbers of inputs (5 or 10) to the current ScriptCondition and ScriptAction module types. In that way the users will have ability co connect them to outputs of other modules and the advance users will have opportunity to write scripts with using these connected inputs (the rule engine set their values and make them available in the rule context).
The current approach has followin cons:
- Only the outputs of the triggered module is available in the rule context. For example : 
1 - is  ItemTrigger module for the first item
2 -  is  ItemTrigger module for the second item
and the first Item change its state
print(context.get('1.newState')) - will print the new state 
print(context.get('2.newState')) - won't be available in rule context. (because at the moment all the outputs are stateless)
print(context.get('newState')) - won't know state of which item is printed.
BTW I want to open discussion about stateless / stateful outputs. I remember that we have discuss this but I think we can do some improvements. I'll add an issue about that, 

- this script "print(context.get('1.newState'))" can't be reused or can stop working because it relays on the module name. When the user change the name of the module, the rule will be compromised.

**Comment by sjka** [comment]
> My proposal was to add some numbers of inputs (5 or 10) to the current ScriptCondition and ScriptAction module types.

Why do you think it's convenient to have a fixed number of inputs and force the user to wire them in an additional step? In the end, the user will have to "remember" what exactly "input3" was. I can really recommend trying this out yourself!

> Only the outputs of the module which was triggered are available in the rule context.

Of course, this is what I would expect. What kind of useful input should come module wich did _not_ trigger the rule?

> When the user change the name of the module, the rule will be compromised.

As will it be when the user changes item names... Of course, this is expected!

**Comment by kaikreuzer** [comment]
@danchom My PR #2850 is meant to provide a solution for the "simple rule editor" as discussed in https://github.com/eclipse/smarthome/issues/2763#issuecomment-272826754 and I think this addresses it nicely.

Your ideas regarding script actions with defined inputs is something that would only be relevant for a (not yet existing) expert rule editor. Ok for me to discuss what makes sense there , but I think it should be an independent discussion and not block #2850.

**Comment by danchom** [comment]
@Kai, I'm not blocking #2850, I just share our experience and how we implemented these module types. I'm ok the current PR to be merged.
@sjka 
>Why do you think it's convenient to have a fixed number of inputs

It's not convenient to have a fixed number and I'll open discussion to invent a way to define them dynamically (in time of rule creation)  
>and force the user to wire them in an additional step

This is normal way to exchange dynamic data between modules. Through the connections the user define (shows) source input data. At the moment you don't have opportunity to see your scriptCondition which item it checks.  
Also with the inputs you have opportunity to write scripts which other users can use in their rules. For example: The script: input1 + input2 + input3 + input4 + input5 will sum data of connected inputs and this script can be used independent of the state of the system and can be used in different usecase.
>Of course, this is what I would expect. What kind of useful input should come module wich did not trigger the rule?

There are different type of outputs. For example ItemTriggers.newState is example of stateful output, The timestamp of the TimerTrigger is stateless output. Why we need a stateful outputs?  For example if you want to create a rule which has to be executed when two items are ON, and do this with two comparator conditions (yes can do this ItemStateCondition but this is just an example and it only compare item states, it can't do some other complicated logic base on the state o fitems). Unfortunately this can't work because only one (the changed one) of comparators can be evaluated, the other won't receive input and logic and may be failed.
>As will it be when the user changes item names...
As Kai said the "advanced user" will write the script (script programmer), the user of home system, can decide to change a name of trigger of rule in his home and will brake the logic of script programmer. I think this is a real use case.
