### ISSUE TITLE
Incorrect url for buchen-maven-repo in pom.xml

### ISSUE THREAD

**Issue by clue42** [eclipse/smarthome#2930]
Hi, it appears that the url for the buchen-maven-repo ist not correct any more and hence the build process is timing out.
Changing the url 
**from:** [http://buchen.github.io/maven-repo](url)
**to:** [https://github.com/buchen/maven-repo/](url)

in pom.xml works as expected and the build process is finishing successfully.

**Comment by kaikreuzer** [comment]
This will only work because you have the required plugin already in your local maven repo.

http://buchen.github.io/maven-repo is the correct url as documented [here](https://github.com/buchen/maven-repo/#usage).
https://github.com/buchen/maven-repo/ is a url that answers HTTP requests, but which does not host a Maven repo, so that's no valid fix.

**Comment by clue42** [comment]
But why is it timing out then? Directly accessing the url gives a 404.

**Comment by maggu2810** [comment]
For me the direct link to the used artifact is working:
www.portfolio-performance.info/maven-repo/name/abuchen/fix-info-plist-maven-plugin/1.0/fix-info-plist-maven-plugin-1.0.jar

**Comment by maggu2810** [comment]
@clue42 Maven use some mechanism to access artifacts in the repo.
The normal lookup is: `repo-url / <groupId-replace-dots-with-slashs> / <artifactId> / <version> / <artifactId>-<version>.jar` (let's assume no classifier and type=jar).

So, if the link above is working for you, all should be fine.
