### ISSUE TITLE
create a RunRuleAction

### ISSUE THREAD

**Issue by BenediktNiehues** [eclipse/smarthome#2964]
In order to directly execute a set of actions defined in another rule there should be an action module which supports this. This would enable the rule engine to support a kind of scene support. Scenes could be defined in a rule with only a set of actions, theses scenes then can be "activated" by callling runNow() on the rule directly or by an action within anoter rule.
The RunRuleAction needs as parameter a set of ruleUIDs which should be executed.

**Comment by kaikreuzer** [comment]
Sounds useful to me. @danchom, any comments?
@smerschjohann How well would that fit to your work on the JSR233 rule support? Would it be easily possible to define trigger-/condition-less rules in e.g. Jython that are effectively merely a script to be executed as an action?

**Comment by danchom** [comment]
>execute a set of actions defined in another rule 

1) A set of actions can be presented as one action throught the CompositeAction
2) if you wish one rule to start other rule, you can do it now with event action and event trigger
3) I think it is not right a rule action to execute actions of another rule. You just to workaround the entire rule engine. 
If you want to reuse module instances (Trigger and Actions) between rules, this is other question. At the moment it is not possible because we support only AND logical operation between Conditions. If you want to do an OR operation you have to duplicate triggers and actions and split the conditions in two rules. 
I think it would be usable to support ANY logical expression between Conditions. We can do it for example with a special (not required) configuration property containing LDAP expression between conditions.  What do you think?

**Comment by kaikreuzer** [comment]
1. As a user, you can't.
2. How? There is nothing like a "TriggeredByAnActionTrigger".
3. This is not at all related to conditions here. It is about reusing "a readily-configured set of actions".

**Comment by danchom** [comment]
1) right, at the moment. In the feature I think we should have a composite editor for users.  
2) one of actions executed by the rule can be EventAction (which throws event with topic=a). The other rule has to have a EventTrigger which is listening for events with topic=A
3) Right "This is not at all related to conditions here", but if we can do OR operation between conditions we can reuse "a readily-configured set of actions". 
As I said if you think it is useful I'm ok to be merged.

**Comment by smerschjohann** [comment]
@kaikreuzer that would be possible. That would just mean that no (other) triggers have to be added to the rule.

But I think @danchom's solution to simply use topics is more generic and more useful. If there are tags for the rules, it would be cool to simply use those to trigger them as it allows to group the rules.

**Comment by danchom** [comment]
It is possible to extend runNow(String ruleUID) command to  a command with optional parameter action tags i.e. runNow(String ruleUID, String... actionTags). When tags are not specified, the rule engine will try to run all rule actions (as it works at the moment). in case when tags are selected, the runNow command will only execute the actions which contains all specified tags.

**Comment by kaikreuzer** [comment]
> As I said if you think it is useful I'm ok to be merged.

I don't want to overrule anyone, I like the discourse :-)
I am wondering a bit though that you do not think it is useful, since you have "scenes" in HAM and this construct would allow something fairly similar.

Regarding 1-3:
1. The result would be a new action type, but not a new action, so that is no solution.
2. As a user, you cannot "throw event with topic A". You would have to use some existing action. Asking users to invent some "useless" item, just to use it to pass such an event, should like a hack.
3. The nice thing about a runNow actions is that the runNow method already skips all conditions anyhow, so we are only left with the execution of a list of actions, which is just want is needed.

**Comment by danchom** [comment]
>I am wondering a bit though that you do not think it is useful, since you have "scenes" in HAM and this construct would allow something fairly similar.

HAM has different architecture. In the HAM condition and actions are standalone objects which can be connected and shared by rules. In the Automation architecture there no standalone modules. All the modules are part of the rule and only the rule can interact with them. To have scene functionality in Automation we permitted each rule to execute a list of actions and this is actually a scene execution.  
IMHO if a rule tries to access actions of other rule, using the functionality of runNow command, it is a real hack of the rule engine. It will not be clear why these commands are executed (run by the rule engine or by the runNow command. The runNow breaks the logic of the containing rule and should be used only for test purposes). Also it is different how these actions are executed (incase of  rule engine, the execution will stop on first fail, when they are executed by the runNow, the execution tries to execute as much as possible actions (not stop on first fail)).
Regarding 1-3:
1) Agree, it is not a solution for the user, but it is solution for developer to propose such collection of data. For me the user solution is to create a separate rule containing these actions.
2) We can provide new composite types base on the eventAction and eventTrigger i.e. RuleExecutedStatusAction and TriggerOnRuleExecutedStatus
3) I mean to extend functionality of runNow command to have opportunity to run just part of the rule's actions not all of them (i.e. only actions tagged as "room1, turn-on"), again only for test purposes.

**Comment by BenediktNiehues** [comment]
Just to note: At the moment such kind of Scene support is already available with runNow and imho it is really straight forward for users. The user just has do define a rule with a set of actions as a scene. To activate the scene the rest endpoint POST /{ruleUID}/runnow can be used. So what currently is just missing is an activation for such scene rules from another rule. And the behavior of runNow to try to execute as many actions as possible - means stopOnFirstFail=false - is exactly what I would expect. Even there should be no problem with cyclic rule executions because the actions are only triggered if the rule is in state IDLE.
Configuring RuleExecutionStatusAction and TriggerOnRuleExecutionStatus trigger is from user perspective not transparent and you even can define cyclic rule executions.

**Comment by danchom** [comment]
>Just to note: At the moment such kind of Scene support is already available with runNow and imho it is really straight forward for users.

For me this is not scene support, it is  a bug exploit in the rule engine which permits to add a rule without triggers. In the past, this was forbidden (I don't know when the bug appears again). For me this is not a rule (without trigger it will never be triggered by the rule engine), it is some kind of dangling object containing group of actions.  I don't understand why do you need the rule engine at all. If I understand you right you are only using Automation rest api and runNow to access handler implementation and  run some kind of functional program logic which workaround the rule engine.  
IMHO the runNow has to be used only for test purposes and not duplicate function of rule engine to execute actions of arbitrary rule.

**Comment by danchom** [comment]
On the other hand you are right, there is no cycling dependency. But I want to mention this support runNow + group of action will work only for self-dependent actions (actions which can be executed by runNow ) - part of actions. This means for other actions, which have inputs and depends from data of other modules you will not have scene support. And how can you explain to the user this can be added but this shouldn't. In case of using dedicate trigger/action for that, there will not such limit (you can add all actions in the scene).

**Comment by danchom** [comment]
@kaikreuzer no I don't think we should add a new concept and rewrite half of functionality. For me it will be clean approach with dedicated trigger/action. The advantages are:
- clean action execution logic - It will be clear why some actions are executed. It will not be possible a rule from one application to execute actions of other application (for me this is security hole) 
- all the action can be grouped by the rule, not only self dependent. At the moment the module type are very simple and you don't use input/outputs, but I think this will be changed in the feature and this will be a problem.

**Comment by BenediktNiehues** [comment]
@danchom wasn't there already a validation for rules which checks if input/outputs fit together? This would/schould then notice if a mandatory input of an action is missing because of a missing output of another module. And if this is in place I see no problem to have rules without triggers. 

An additional point is the handling of the stopOnFirstFail parameter in the executeActions method: I would expect the ruleEngine to try to execute as many actions as possible in each case. Even if there is failing something in the chain which should serve some output: who cares, then the module which needs this output as input fails, too, but the independent actions will still be executed. Maybe this behavior should be configurable in future so that the user can decide if the RuleEngine should proceed after an error on a single module occurred.

**Comment by danchom** [comment]
>wasn't there already a validation for rules which checks if input/outputs fit together? 

Yes you are right, If they not fit the rule will not be in IDLE state and the runNow command can be used.  My point was how to add actions with required inputs into scene. How to explain, why only part of actions can be group into scene and why if I add a non self-dependent action the entire rule goes into UNINITILIZED state. For me all the actions can have opportunity to be group into scene and this can happen with dedicated trigger/action 
If we permitted to have a rule containing only actions (for scene purposes) then do we have to permit rules containing only triggers or only conditions? These rules will not be unusable and we have to change the definition of rule i.e "Rule is container of modules which can or can't be executed by the ruleEngine"

But the big problem is that the rule action can workaround entire rule engine and runs action of other rule. I understand that this is not a problem for your scene implementation support and even have some advantages such as no cyclic scene execution, but  in that way you permit actions of each rule (not only "scene rules") to be run by an action of other rule. What is going on if I have a rule with an action list which has to be executed. I've defined that this sequence  of actions MUST be executed ONLY WHEN some circumstances are happen and MY conditions are satisfied.  You like my set of actions and decide to run it  just using the  simplest way using  runNow command/action (why not, the scene do that). You will workaround my logic implied into the rule and run part of the actions and may be do some damages, because action execution can be risky. After that I'll responsible why my rule is not working properly and damage the system. To find the problem it won't be easy because debugging of my rule's triggers and conditions does not show any problem. I've to look into logs and  have to check all other rule if they accidentally run my actions and finally when find guilty rule I'll ask the author why do that. I'sure the answer will be "what wrong, the scenes do same"

>An additional point is the handling of the stopOnFirstFail parameter in the executeActions method: I would expect the ruleEngine to try to execute as many actions as possible in each case. 

In the past behavior of the rule engine was that, but we have changed it (Kai propose this change and I'm agree with him) .The actions can a sequence of their execution and when skip some action we change the sequence which can be risky.

>Maybe this behavior should be configurable in future so that the user can decide if the RuleEngine should proceed after an error on a single module occurred.

Agree, the rule should have some configuration property which can  configure ruleEngine how to execute the rule. This can be one of these properties. The other can be logic expression over conditions. But this is other topic for discussion.

**Comment by smerschjohann** [comment]
I don't really understand your point here. Typically someone will provide an action handler which can be harmful in some way, ok, but I don't see anywhere in the rule engine or handler registry where someone can restrict a module handler to be only instantiated by a rule template? Otherwise it is always possible to create a rule which damages the system? So where is the point here?

Typically you will create the rules yourself, configure them accordingly, and you know what the action of the rule does, so there would be no harm at all.

But yes, I agree with you, the runNow should run the conditions as well, so if you have for example rollershutters or other electronics which exclude each other (in rollershutters you should never give power to both motors), at least the condition can prevent accidental execution.

But the main problem that I guess should be solved by this, is the reduction of duplication of modulehandler+configuration, so I think there is no other way except global actions (action handler + configuration) and allow the assigning of these actions to multiple rules + a UI which shows for each action where it is assigned to.

**Comment by danchom** [comment]
> Otherwise it is always possible to create a rule which damages the system? So where is the point here?

Yes you are right it always can be  possible to add third party module which harm the system but my point was that this must not be core once which have to be used as examples. For me this will be confused for users and they will wonder how to run actions through the triggers or through the runNow.

>Typically you will create the rules yourself, configure them accordingly, and you know what the action of the rule does, so there would be no harm at all.

This is only one use case. Typically there is one rule engine on one OSGi platform where runs more then one applications. If only one uses rule engine ok but IMHO more then one applications will take advantage of the rule engine.

>But yes, I agree with you, the runNow should run the conditions as well

I'm didn't said that. To check conditions is not easy task. The can conditions has inputs and will expect data in it. It is not easy pass such data, because it can be arbitrary object. For that reason we have decided the runNow command to execute only actions (only these which can be executed, because some of them also expect data on their inputs) for test purposes . 

>But the main problem that I guess should be solved by this, is the reduction of duplication of modulehandler+configuration, 

We can reduce duplication of modules when we permit arbitrary logic expression to be executed over the conditions (not only simple logic and between them). In that way you can merge rules which have duplicate modules in one with more complex condition. For example if you want to do logic OR over the two conditions at the moment you have to create two rules with duplicate trigger and actions and split the conditions between them. If we can do condition1 OR condition2 then we will skip module duplication. 

>so I think there is no other way except global actions (action handler + configuration) and allow the assigning of these actions to multiple rules + a UI which shows for each action where it is assigned to.

There is, to create regular rule with dedicated trigger which is triggered by dedicated action from other rule. Both trigger and action can be base on events.

As I said if you think this is the right way to implement scenes feel free to merge it. The problem for me is the bug that accepts rules without triggers into rule engine must not be fixed, because this somehow break the concept of rules, but I can live with that.

**Comment by danchom** [comment]
I've another proposal. We can extend RuleEngine to fire (always or configured by the rule) an OSGi event for status of action execution. The status can be:
- SUCCESS in case  when the actions are run without problem (to run I mean that they are started without exception, not that they finish their job successfully, because we don't have a callback from a real job) 
- FAILED - with status details of failed action   
In that way, only one new composite trigger type has to be implemented which will  be triggered base on rule status execution of other rule. We will have opportunity to run a rule, not only base on other rule execution, but on fail of other rule too.

**Comment by smerschjohann** [comment]
In general that sounds like a nice feature. But I think it is only useful if SUCCESS means the Job has completed, otherwise it only has limited use. What do you mean we do not have a callback from a real job? I don't see a reason to not have that. Just place the event after the job has completed.

**Comment by BenediktNiehues** [comment]
Let's get back to the essential question here again and handle other questions in other issues.
The main question is if a rules has to have a trigger?
Then for the scene scenario I would need:

- a rule with a set of actions to represent my scene
- this rule needs an eventTrigger, listening on a topic e.g. "smarthome/rule/execute/{RuleUID}"
- a Rest endpoint to fire the event (to activate the scene manually by any UI)
- a FireEvent action to fire the event within an other rule.

From user perspective imho it is far too complicated to define an action in a rule and the trigger in another rule; so you can not use any generic UI if you want to hide this complexity behind it.

I could live with that scenario if a rule by default has a trigger which listens on such an event topic, so that this has not to be configured explicitly. That would imply that every rule can be executed by sending out an event with the correct topic. And even the conditions will be evaluated. 
But with that scenario we easily can run into loops!

**Comment by danchom** [comment]
To summarize my : 
If a list of action is a rule then list of conditions and list of triggers or some combination of then are they rules too? Should they go in IDLE  state despite of they won't be trigger or they don't do anything?
If the scene does not have a trigger then it can't be run without runNow command.
I don't like a rule to be executed by an action which just call runNow method and skipping all my conditions and pre-requests in form of triggers. I'll never be sure why my actions are run. 
But if these are only my concerns I won't stop this implementation and I give up the PR #2983

**Comment by maggu2810** [comment]
> If a list of action is a rule then list of conditions and list of triggers or some combination of then are they rules too?

A rule without triggers and condition but at least one (or more) action could be used to realize "scenes".
I have to re-read the whole thread, but at the moment I don't see anything bad to support action only rules.

I don't think a rule without any action make sense.
So IMHO at least one action should be mandatory for rules, condition and triggers are optional.

> If the scene does not have a trigger then it can't be run without runNow command.

That is right, but we can trigger it by the UI and if there is a runNow action...

> I don't like a rule to be executed by an action which just call runNow method and skipping all my conditions and pre-requests in form of triggers. I'll never be sure why my actions are run.

If there are conditions in a rule IMHO the conditions should be considered on "runNow". For me "runNow" is a manual trigger of a rule and should not skip the condition evaluation.

For scenes it does not make any difference as there are no conditions but actions only.

So, my concerns are that conditions are not checked but actions are executed and this should be avoided.

**Comment by BenediktNiehues** [comment]
@danchom I don't want to overrule you, but from my perspective the initial way would be the easiest and less effort way to support something like scenes. We could even provide an other method which considers the conditions first or make the runNow configurable.

**Comment by danchom** [comment]
If @kaikreuzer and @maggu2810 are agree with this PR then its ok for me too.
BTW Its not easy to recalculate conditions on runNow execution when the condition have inputs.

**Comment by kaikreuzer** [comment]
As already mentioned above, I also do not see any concerns in having rules without triggers - after all, you can also define rules that will never be executed by themselves because their conditions always evaluate to false. If we translate "rule" with "business logic", the requirement that a rule must  have at least one action sounds reasonable to me. No need for mandatory triggers&conditions.

> If there are conditions in a rule IMHO the conditions should be considered on "runNow". For me "runNow" is a manual trigger of a rule and should not skip the condition evaluation.

@maggu2810 This is something that was discussed when introducing the "runNow" feature. For how this is used now (to manually trigger a rule in the UI for testing), I think it makes sense to skip the conditions (you don't want to wait with your tests for the next solar eclipse, so that your condition evaluates to true...). For the "runNow"-action, I agree that it might make sense to consider conditions as well. So @BenediktNiehues's suggestion to make that configurable sounds like a good compromise to me, would you agree?

**Comment by danchom** [comment]
Its OK for me, but I want mention if a condition has an inputs such as ComparatorCondition, the actions of such rule won't be executed by the runNow action because the conditions can be evaluated without input. This can be confused for the user.
The problem can partially be solved by tasteful/stateless outputs which I'm going to introduce in separate issue.

**Comment by kaikreuzer** [comment]
Yes, such a runNow action with respecting conditions wouldn't make sense on ComparatorConditions, but e.g. on ItemStateConditions (which can also check (in an event-less way) for current states) - and I think this will be the main use case (e.g. disable a rule based on presence=off or stuff like that).

**Comment by BenediktNiehues** [comment]
I've updated my PR #2965 with the option to consider conditions.

**Comment by BenediktNiehues** [comment]
As the PR #2965 is closed, this issue can be closed, too.
Will do that now...
