### ISSUE TITLE
Auto linking: channels in advanced channel group types should not be linked

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#3156]
In simple mode (auto linking), the channels associated to an advanced channel type are not linked.
But channels in advanced channel group types are linked while they should not.

**Comment by lolodomo** [comment]
Can I have please some help to find where is implemented in Paper UI the automatic creation of items and channel links when a new thing is added ?

**Comment by maggu2810** [comment]
Have a look at `bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/ThingLinkManager.java`

**Comment by lolodomo** [comment]
Thanks a lot, I see the bug in createLinkIfNotAdvanced(). I will provide a fix.

**Comment by kaikreuzer** [comment]
Sorry, I didn't closely enough follow why we have "advanced channel group types" at all now.
Afair the original design, there was no such flag on channel groups and a groups is simply visible if it contains at least one non-advanced channel and otherwise it is not visible. So why do we need the advanced flag there, which can rather contradict the flags of the channels?

**Comment by lolodomo** [comment]
The general concept was certainly to make a group of channels globally advanced. I can clearly see the interest in such a thing.

By the way, IMHO this "advanced" flag should not be set on a channel type but directly on a channel. For example, I define a channel type representing a temperature; then I want to define different channels using this type, few of them being advanced and others being not (current temperature is not advanced but the dew point could be considered as advanced).

Here is my proposal:
* we add an advanced flag on the channel
* we keep the advanced flag on the channel type for compatibility with all existing bindings. If the flag is not set on one channel, it is inherited from its channel typoe.
* we suppress the advanced flag from the channel group type (I think it is only used by me until now and by the way it is not correctly handled neither by Paper UI nor by the ESH framework).
* It will be possible to make a channel group globally advanced by setting all its channels as advanced.

What do you think about that proposal ?

**Comment by lolodomo** [comment]
Any answer ?

**Comment by kaikreuzer** [comment]
> we add an advanced flag on the channel

I think this is going the wrong way. Actually, I feel it was already a mistake to add label and description to the channel, because I see people now start misusing this to define "string channel type" and "switch channel type" and then reuse these throughout their things - this is not at all the intention of the channel types, which should be a specific functionality of a device (and two "temperature channels" might actually measure some completely different temperatures and thus should be different channel types. The label on the channels themselves was only meant as a mean to be able to support "zones", where it is really exactly the same functionality, but the device offers it multiple times.

So this is my suggestion:

> - we suppress the advanced flag from the channel group type 
> - It will be possible to make a channel group globally advanced by setting all its channel [type]s as advanced.

**Comment by lolodomo** [comment]
Your approach means almost one channel type per channel. In this case, the limit between channel and channel type is not so clear for me.
But ok we can go in this direction too and multiplying the channel types.

**Comment by maggu2810** [comment]
> Your approach means almost one channel type per channel.

Really? I don't think not in general. I assume @kaikreuzer thinks about one channel type per different type.
It depends if a type could be advanced in some case and non-advanced in another case.

**Comment by lolodomo** [comment]
That is exactly the problem and why I would like to put the advanced flag on the channel. If not, we could be forced to duplicate channel type making one advanced and the other not.

**Comment by kaikreuzer** [comment]
> Your approach means almost one channel type per channel.

That is correct. See the [Sonos binding](https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/PLAY1.xml#L13-L54) as an example for that.

> It depends if a type could be advanced in some case and non-advanced in another case.

Could you give an example? I don't really see any real use for that - either a functionality is advanced (i.e. something that only expert users are interested in) or not. It should not really matter which device provides this functionality.

**Comment by maggu2810** [comment]
@kaikreuzer No, I don't know one at the moment. 
My reading of the comment of @lolodomo has been that he complains about duplicate the number of channel types (channel_type1_non_adv and channel_type1_adv).
As my understanding fit to yours that a functionality is advanced or not, I written "Really? I don't think so in general". The last one "it depends if ..." was a note that I cannot state that there is never a use case for a function that is non-advanced in the one case and advanced in the other case. And then we need different channel types.
Perhaps a light actuator with power and energy meter -- in this case the meter could be advanced and only the on/off non-advanced. For meter things itself the meter channel are not advanced. In this case we already should use different channel types, because a power meter of a light differ from a power meter of a light actuator (in this case if someone uses ATM one channel type it will be two -- and so twice -- if he fix that).

**Comment by lolodomo** [comment]
I already provided an example with different kind of temperatures: current tempetature, feeling temperature,  forecat min and max temperatures for today or for tomorrow or in 10 days...  My binding is defining a big number of channels and I want to make few of them advanced. I would like to limit the number of channel types.
But defining 2 instances of each channel types, one advanced and one not is strange for me but a workaround I can use.

**Comment by maggu2810** [comment]
What I want to say above and I assume also @kaikreuzer:
If you have a channel type "temperature_current" then you have to think about if this type is advanced or not.
Why is a temperature_current in one use case not advanced and advanced in another?

**Comment by lolodomo** [comment]
Of course if I define one channel type for each channel, the problem would be resolved but that would be weird to define so many identical channel types.

**Comment by kaikreuzer** [comment]
> weird to define so many identical channel types.

This is a contradiction in itself. A channel type is only identical to itself. So you might only end up defining similar but not identical channel types, which is imho fully ok.

**Comment by lolodomo** [comment]
As I have no chance to convince you, I close the issue.

**Comment by kaikreuzer** [comment]
> As I have no chance to convince you

Hey, of course you have a chance, if you come up with a use case that shows the necessity.

> I would like to limit the number of channel types.

I think this is what the discussion is really about - what is the right granularity of channel types. The status quo is that it is very fine-granular and as such, I think you have to agree that there is hardly a use case that would require to overwrite the advanced flag on channels.
