### ISSUE TITLE
Basic UI: page and frame title containing item state are not updated

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#3175]
If you open a frame linked to an item, the title at the top of the page display the item label with including its state. If the item state is then changed, the title is not updated.
Exiting the frame and re-opening it then oif course displays the correct title.

**Comment by lolodomo** [comment]
@resetnow : before I start to investigate, maybe you can provide your initial feeling of what could be wrong. Do you thing the problem is on server side, that is no update event sent for the event attached to the frame, or is it on the front side that the event would not be handed correctly ?

**Comment by resetnow** [comment]
I don't know if there's an event in the event stream but updating frame (and page) titles is definitely not implemented client-side

**Comment by lolodomo** [comment]
Ok. Do you thing it could be easy to fix ?

I don't know if I should say frame or page... What I am talking about is the title with a blue background and an arrow to return to the parent frame/page.

**Comment by resetnow** [comment]
There is a list of widgets stored in the `smarthome` object; one could make a new widget type for the top bar, send the necessary information (item ID/widget ID) with ajax response and also account for a case when a page is opened by URL. But I would first check if there are any SSE events.

**Comment by triller-telekom** [comment]
I just had a look at this issue and just to make sure we are on the same page: my sitemap looks like:
```
sitemap demo label="Demo Sitemap" {
	Frame label="Demo Items" {
		Text item=LampeTeleviseurColor label="Philips Hue" {
                       Switch item=LampeTeleviseurColor
                       Slider item=LampeTeleviseurColor
                       Colorpicker item=LampeTeleviseurColor
               }
	}	
}
```
and my items file:
```
Color LampeTeleviseurColor "Couleur Lampe TV [%s]"
```
This creates a website (`page1`) with a widget with heading "Demo Items" that contains one text entry saying "Philips Hue XX" where XX is the state.

If you click on "Philips Hue" in this website you get to a website one step deeper in the hierarchy (`page2`) where "Philips Hue XX" becomes the heading and there are 3 widgets (Switch, Slider, Colorpicker) below.

If I understand you correctly you are saying that on `page2` you expect the current value of the item in the heading is updated once you move the slider for example, right?

Moving the slider does NOT update the item in the headline because this is a mossing feature. The `PageChangeListener` creates events for every widget in the current page, but on `page2` the heading it not a widget, thus it does not get updated immediately but on the next reload.

However on `page1` the text entry "Philips Hue XX" DOES get updated immediately if the item state changes (i.e. simulated by changing via classic gui). This is because on `page1` this text entry is a widget and thus it gets a `SitemapChangeEvent`.

**Comment by lolodomo** [comment]
Yes, my concern is the update of the heading on page 2 in your example when this heading contains something dynamic (an item state).
Would it make sense to create a widget for the page title ?

**Comment by triller-telekom** [comment]
In my opinion it would make sense, because in that way the heading can be treated like any other widget and we do not have to change our logic. And if it would appear as a widget the `PageChangeListener` would take care of the updates as it already does when it is on `page1`.

**Comment by lolodomo** [comment]
I took a look how is rendered the page title in Basic UI (and Classic UI - same way).
The change to do to make the page title dynamic is certainly largely too much difficult for me.

**Comment by lolodomo** [comment]
The frame title is also not updated when the frame is linked to an item.

**Comment by lolodomo** [comment]
PR #3526 is fixing the issue with the frame title.
Remains to fix the page title.

**Comment by lolodomo** [comment]
The fix for the page title is I think now easy (the function setTitle already exists).
@resetnow: I have to fix in case of SSE listener and in case of long pooling listener. Can you tell me in which case the long pooling is used and how I can enable this mode ?

**Comment by resetnow** [comment]
@lolodomo you can temporarily replace `featureSupport.eventSource` value with `false`

**Comment by lolodomo** [comment]
PR #3631 fixing the update of page title for SSE browsers is merged.
Non SSE browsers like IE or Edge still have the page title not updated.
