### ISSUE TITLE
Bindings should not be able to remove Things without user approval

### ISSUE THREAD

**Issue by rodneyrehm** [eclipse/smarthome#3199]
Way back when we first discussed the introduction of [Thing Status](https://www.eclipse.org/smarthome/documentation/concepts/things.html#thing-status) we argued that a binding should only remove things upon user request. The [Status Transitions](https://www.eclipse.org/smarthome/documentation/concepts/things.html#status-transitions) visualize this by having the binding react to the status `REMOVING` and confirm the removal by setting the status to `REMOVED` upon which ESH deletes the thing itself.

But it appears that `REMOVING` is not a necessary precondition to `REMOVED` right now. We currently have bindings that set the status of a thing to `REMOVED` when the APIs the bindings use don't list a particular thing anymore. This leads to ESH cleaning out the thing and its references and the user doesn't (easily) realize what happened because the thing is just gone.

I see two options to get back to the idea of bindings not removing things without the user's permission or knowledge:

1. ESH may only clean up things when entering status `REMOVED` from `REMOVING`, otherwise preserving things in status `REMOVED` (as I believe was the original intention)
2. ESH introduced a new state `VANISHED` (or a new status detail, e.g. `OFFLINE:VANISHED`) to denote the situation where a thing no longer "physically" exists but is still mapped in ESH. Additionally ESH should make sure that `REMOVED` can't be set unless the status is `REMOVING`.

**Comment by maggu2810** [comment]
> We currently have bindings that set the status of a thing to REMOVED when the APIs the bindings use don't list a particular thing anymore.

Which one?

> I see two options to get back to the idea of bindings not removing things without the user's permission or knowledge

You missed the first one: Fix the binding and use the API as intended. :wink: 
If the documentation is not clear at this point we should improve it.

Using the `REMOVING` status as a precondition for the `REMOVED` status sounds okay. It does not really prevent wrong usage (a binding could still set the status first to removing and then to removed), but as a programmer you can use an API the wrong way all the time.

A new status detail for the offline status is okay for me.

I assume @sjka has a better knowledge about that stuff than me.

**Comment by sjka** [comment]
> Using the REMOVING status as a precondition for the REMOVED status sounds okay.

I agree. We weren't that strict with these kind of checks when it was first implemented. But since we now (without bigger complaints) throw IllegalArgumentExceptions in many other cases of attempted "misuse", I don't see any problems with it now. 

I would assume that for most bindings it's going to be hard to tell the difference between a OFFLINE:COMMUNICATION_ERROR, OFFLINE:USER_WENT_AWAY_WITH_THE_DEVICE_BUT_IS_GOING_TO_COME_BACK and OFFLINE:THE_DEVINCE_IS_REALLY_GONE_AND_WILL_NEVER_EVER_COME_BACK. 
I would suspect that the user knows very well when something changed at home, so OFFLINE or OFFLINE:COMMUNICATION_ERROR would suffice in order to notice that a destroyed device cannot be used anymore. To be honest, even if a binding would be able to tell the difference I'm struggling a little with the benefit of having an OFFLINE:VANISHED state. What would be the benefit?

As you can see, I'm missing the use-case for this scenario. So far I tend to second @maggu2810's suggestion to rather focus on fixing the binding.

**Comment by rodneyrehm** [comment]
> … I'm struggling a little with the benefit of having an OFFLINE:VANISHED state. What would be the benefit?

It took me a while to understand what @kaikreuzer was trying to explain to me last night. You're absolutely correct, there is no reason to introduce a new status. `OFFLINE:CONFIGURATION_ERROR` is all we need.

> … rather focus on fixing the binding.

absolutely. However, we all seem to agree on bindings not removing things without the user's consent. The docs should clearly state this and the API should enforce this.

**Comment by sjka** [comment]
nice 😄 

I'm about to file a PR for those two things: disallowing bindings to initiate the removal and making the docu more explicit in that respect. Thanks for this feedback!
