### ISSUE TITLE
Automation javadoc

### ISSUE THREAD

**Issue by plamen-peev** [eclipse/smarthome#3269]
Automation javadoc must be fixed in order to compile the project with java 8.

**Comment by sjka** [comment]
You mean "in order to remove the `-Xdoclint:none` statement from the [pom.xml](https://github.com/eclipse/smarthome/blob/master/pom.xml#L392)"? 😉 

No, seriously, you are right in principal. However, just to make this clear: The project still compiles well with Java 8 currently because of this flag.

The only "pitfall" is the fact that this flag is declared in a maven profile which activates itself given by the condition it is running on java 8. Afair, maven omits the automatically activated profiles if you explicitly activate some other profiles, hence you would need to mention the doclint-java8-disable again together with the other profiles.

**Comment by danchom** [comment]
The purpose of this PR is to improve and remove errors in java doc of automation module (according 1.8). It is not intended to change the pom.xml at all.
