### ISSUE TITLE
Basic UI displaying an unexpected value for standard group

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#3290]
With snapshot 889, I can see unexpected display of value for "standard" groups in Basic UI. It is not displayed immediately when opening a page containing a group but a value is then displayed probably when one of the items in the group is updated.

It only happens in Basic UI, there is no such issue using Classic UI or HABdroid.

The problem was introduced after snapshot 853.

I think the problem is not directly in Basic UI code but in the message built by the server and sent to the UI.

**Comment by lolodomo** [comment]
Could it be in relation to merged PR #3274 ?

I think the problem could have been introduced during the last week becasue I did not notice it last weekend when implementing other stuff and running from Eclipse.

**Comment by lolodomo** [comment]
Maybe a normal group has now a state and due to #3294, this state is now displayed by Basic UI.

**Comment by lolodomo** [comment]
@triller-telekom : can you tell us if your change could have changed something relative to the state associated to a standard group ?

**Comment by lolodomo** [comment]
By the way, how is defined the state of a standard group ?

**Comment by triller-telekom** [comment]
I am not quite sure what you mean by "standard group". I am assuming you mean something like this in your items file:

`Group name`

If that is the case then a change of an item should no more affect the status of the group, because the group does not have a type (i.e. baseItem) and thus it also does not have a function. Functions only make sense on types.

So the basicui cannot show any status of a group UNLESS you set it explicitly with a trigger like a "group switch" in a sitemap, see https://github.com/eclipse/smarthome/pull/3314#issuecomment-297457019

I guess this issue is related to #3051

**Comment by lolodomo** [comment]
Ok let's wait for your PR to be merged and then I will ckeck again.

**Comment by lolodomo** [comment]
PR #3314 solved this issue.
