### ISSUE TITLE
State event: adding the transformed state value ?

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#3295]
https://community.openhab.org/t/mapping-of-item-values-not-correctly-shown-in-habpanel/19518/16
The subject is: would it make sense to add the transformed state value in the state event.
The discussion is opened.

**Comment by lolodomo** [comment]
As I understand, it will be required only by UI not usimg sitemap like HABpanel.
SSE sitemap events already include raw and transformed state.

**Comment by maggu2810** [comment]
What is the difference between this issue and https://github.com/eclipse/smarthome/issues/2788

**Comment by maggu2810** [comment]
What is the difference between this issue and https://github.com/eclipse/smarthome/issues/2788 that has been fixed by you with #3135?

**Comment by lolodomo** [comment]
As I understood,  one developer of HABpanel does not want to use the REST API while the REST API is now ok with the raw and transformed state.

**Comment by ghys** [comment]
Sorry for not chiming in before.
I was wondering if it made sense (or was advisable performance-wise) that the transformed state be included in the `ItemStateChangedEvent` payload - probably around [here](https://github.com/eclipse/smarthome/blob/3ae5d7b1b284f2bde6199bfe8dad950fd38cae39/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/events/ItemEventFactory.java#L255) - so it could be retrieved in the SSE stream to update the UI without having to call to `/rest/items/{itemName}/state` each time an item is updated?

In HABPanel's case, the `/rest/events` endpoint (not `/rest/sitemaps/events/subscribe` since it doesn't use sitemaps) is used to monitor for changes in item states, and none of the events include the transformed state.

**Comment by triller-telekom** [comment]
[This specific place](https://github.com/eclipse/smarthome/blob/3ae5d7b1b284f2bde6199bfe8dad950fd38cae39/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/events/ItemEventFactory.java#L255) to enhance the `ItemStateChangedEvent` is too low level to add such information. This layer is supposed to be GUI independent and thus this event does not need any `transformed state` information.

The ItemUiRegistry is able to provide such details for sitemaps, because it knows about the widget type the state should be converted to. Information about how the state should be displayed in the GUI would also be useful.

We should not add UI specific information to our basic events but rather think about a new concept how GUIs can specify what information they need from the backend so the backend can provide these information in a separate manner. This goes into the direction from 
[Rodneys comment in issue 3320](https://github.com/eclipse/smarthome/issues/3320#issuecomment-298037617).

**Comment by lolodomo** [comment]
@ghys : if you are ok, I close this issue.

**Comment by ghys** [comment]
@lolodomo Sure, I agree with @triller-telekom.

**Comment by lolodomo** [comment]
Ok
