### ISSUE TITLE
Extend the Marketplace extension service to support the "UI" package type

### ISSUE THREAD

**Issue by ghys** [eclipse/smarthome#3320]
Hi,
Last week I added the ability to provision custom widgets to the HABPanel user interface for openHAB with OSGi bundles (registering additional resources and templates during the bundle's activation).
Today a first widget in this format was reviewed and accepted in the Eclipse IoT marketplace: 
https://marketplace.eclipse.org/content/gauge-widget-habpanel
which incidentally is the first having "UI" as a package type.

Since the `MarketplaceExtension` and `MarketplaceExtensionService`  only support bindings and rule templates at the moment. I would therefore like to propose - if the time and approach is right - to extend them to support the "UI" package type. An implementation of `MarketplaceExtensionHandler` (similar to `BindingExtensionHandler`) to install and uninstall those bundles would also be needed.

(I'm aware HABPanel is an openHAB project and not all ESH-based products include it; the bundle will simply be useless then, but I understand it might confuse users if they see it appearing in their extension list without the "parent" software available).

Looking forward to your feedback, thanks!

**Comment by kaikreuzer** [comment]
Thanks @ghys! The custom widgets are a very nice feature of HABPanel.
I agree that the Eclipse IoT Marketplace looks like a good match for distributing such custom widgets.

A few things to maybe discuss before we move forward (additionally to [my comments here](https://community.openhab.org/t/new-feature-globally-provisioned-widgets-i-e-with-osgi-bundles/26994/5?u=kai)):
- So far the "UI" category was meant for "complete" UIs and not extensions for a certain UI. I am also wondering if it makes sense to show these widgets in the "UI" tab of openHAB "Add-ons" besides all the "real" UIs or if there shouldn't be a dedicated tab for the custom widgets.
- As you point out, the widgets have dependencies to openHAB and thus are not "ESH-compatible". I don't think it is a must that any listing here can be used by any ESH-based solution, but we should nonetheless think about how we could potentially remove dependencies to a specific solution and thus make it in general more re-usable.
- As HABPanel is still under heavy development (I assume you do not consider the API as stable?), I wonder how to deal with the compatibility and the version range that the widgets define as being compatible. We have a similar problem for the other listing types as well, but I postponed the solution for the moment as I hoped that it won't be relevant too soon - for the custom widgets, I am not so sure about that anymore, though.

**Comment by ghys** [comment]
> So far the "UI" category was meant for "complete" UIs and not extensions for a certain UI. I am also wondering if it makes sense to show these widgets in the "UI" tab of openHAB "Add-ons" besides all the "real" UIs or if there shouldn't be a dedicated tab for the custom widgets.

That's what I suspected, but I tried to try my luck and submit it anyway and it got approved ;) (maybe it was you?)
If there was a way to keep those widget bundles hidden in general-purpose UIs but still recognized as extensions, HABPanel could query the extensions API in a certain way to retrieve them and display a gallery of widget extensions designed for it? They would be installed and uninstalled from this in-app gallery.

> As you point out, the widgets have dependencies to openHAB and thus are not "ESH-compatible". I don't think it is a must that any listing here can be used by any ESH-based solution, but we should nonetheless think about how we could potentially remove dependencies to a specific solution and thus make it in general more re-usable.

As suggested above, if extensions designed specifically for a particular UI only appear in queries made by this UI, wouldn't this at least partially solve the problem, since they wouldn't be offered for installation elsewhere (apart from the main site marketplace.eclipse.org)?

> As HABPanel is still under heavy development (I assume you do not consider the API as stable?), I wonder how to deal with the compatibility and the version range that the widgets define as being compatible. We have a similar problem for the other listing types as well, but I postponed the solution for the moment as I hoped that it won't be relevant too soon - for the custom widgets, I am not so sure about that anymore, though.

That's a very good point.

**Comment by rodneyrehm** [comment]
Hey there,

in response to [New feature: globally provisioned widgets (i.e. with OSGi bundles)](https://community.openhab.org/t/new-feature-globally-provisioned-widgets-i-e-with-osgi-bundles/26994/6) @kaikreuzer asked me to provide some feedback regarding the portability of widgets. Full disclosure: I'm a frontend developer and work with @kaikreuzer at Deutsche Telekom. I'm neither using OpenHAB, nor was I ever forced to deal with AngularJS.

Kai's primary concern was to find a way to be able to use these widgets in the PaperUI. Both UIs (PaperUI, HABPanel) happen to be based on AngularJS, so fully banking on that framework to enable widgets doesn't seem far fetched.

However, I'd like to point to [Web Components](https://www.webcomponents.org/) for a universally applicable approach. In this world the widget would communicate with the application (HABPanel, PaperUI, …) via the DOM (attributes and events). The widget itself would not be tied to AngularJS, React or whatever. This brings the independence necessary for the next application to chose another framework entirely. Web Components include the ShadowDOM, making sure widgets are fully encapsulated modules. HTML Imports (a Web Component specification currently on hold) would allow the packaging of all assets (scripts, css, images) in a single html file. There are similar approaches that create JavaScript modules. Either of these should simplify the deployment of these widgets to having to serve a single file.

We'd have to come up with a common understanding of how to use the DOM interface (attributes, events), in order to make widgets and applications interoperable. There may be different APIs for different types of widget ("controlling an item" vs "visualizing an item's state history"). 

(If the API is defined properly and a widget's meta data provides the necessary input, I could even see these HTML widgets be included in native apps via small WebViews.)

**Comment by ghys** [comment]
Thanks @rodneyrehm for your input.
It's true Web Components might be a good fit for building those kind of discrete widgets and not depend on any framework.
I have no idea how to integrate those into an Angular 1.x app though - there are a few articles about this but it doesn't seem that straightforward, I know there are Components available in Angular 1.5+ (and 2 but that's another story) but I don't know what the gap is between them and regular Web Components.

However, if we limit ourselves to compatibility with Paper UI (at least for the moment), I don't think it would be that complicated to find some common ground.

If this helps, here's a quick overview on how HABPanel's widgets work currently:
* they are described in a JSON structure like [this one](https://github.com/ghys/habpanel-gauge-widget/blob/master/widget/gauge.widget.json): basically you have an Angular template, along with a description of the settings configured for each instance of the widget (using a dialog box constructed from those descriptions) and put in the template's scope ("`config.<setting_id>`") when it's compiled at runtime.
* The template being an Angular template can make use of any features in the Angular template system, as well as the additional directives and stylesheets (notably Bootstrap) added by HABPanel - so there's no "Shadow DOM" equivalent;
* The API exposed to the templates to manipulate openHAB's items is pretty simple, namely those 5 functions:
   * `itemState(itemname)` (alias: `itemValue` for historical/compatibility reasons) - retrieves the item's state;
    * `sendCmd(item, value)` - send the command value to the specified item;
    * `getItem(item)` - retrieves the whole item structure;
    * `itemsInGroup(groupname)` - retrieves an array of items members of the specified group;
    * `itemsWithTag(tagname)` - retrieves an array of items with the specified tag
* There is no facility to include additional assets in the widget description, but scripts and stylesheets sitting on the local server may be loaded using the `oc-lazy-load` directive (on the local server only -
 there's a Content Security Policy in place to try to prevent the injection of arbitrary code, since the templates are easily modifiable with openHAB's REST API). This was the main motivation for the new "globally-provisioned" widgets in OSGi bundles: having the opportunity to publish these assets somehow (and a better distribution mechanism like the Marketplace).
