### ISSUE TITLE
Saving an edited .items file re-arranges sitemap groups

### ISSUE THREAD

**Issue by olemr** [eclipse/smarthome#3321]
Even minor editing in my .items file such as 'labeltext' or 'iconname' in Eclipse SmartHome Designer renders group-items in my sitemap shuffled when viewed in Basic UI or HabDroid.
Also happens after defining new items.
After a restart, the proper ordering is restored.

After a restart:
![image](https://cloud.githubusercontent.com/assets/28068256/25456266/af14574a-2ad2-11e7-8354-d4cec4395a46.png)

After saving just an extra space character in the .items file:
![image](https://cloud.githubusercontent.com/assets/28068256/25456383/1289f8f2-2ad3-11e7-9ed2-eb3a571c5dee.png)

**Comment by sjka** [comment]
That's indeed correct - group members so far have no natural order. By chance, they are initially sorted in the way they were added when the items files were loaded. But since multiple items files can add members to groups, I don't see how this could be turned into a deterministic order in any way.
I fear if you want to have a reliable ordering on your UIs, then you will have to define them in your sitemap(s) explicitly.

**Comment by kaikreuzer** [comment]
@sjka As @lolodomo mentions in #4232, this was different in the past and I agree that a deterministic behavior (at least if items and groups are defined within the same file) would be desirable. (I actually think to remember that we already addressed a similar issue about the order of items outside of groups in the past).  So please allow me to re-open this issue so that we can check whether there is a simple fix possible.

**Comment by lolodomo** [comment]
Please note that we have now the issue even without editing the file but just loading it at startup is enough to produce a random order.
