### ISSUE TITLE
Basic UI: Active switch item with mapping isn't highlighted any longer

### ISSUE THREAD

**Issue by msfunty** [eclipse/smarthome#3472]
I'm using openhab2 and my configuration is based on sitemaps.

All switch items are being displayed but since a week (or so) the chosen item is not highlighted any longer.
When you click it button will be highlighted, but when you leave the page and go back it is not highlighted anymore.

**Comment by lolodomo** [comment]
Please provide a portion of your items and sitemap showing this issue.
It could be linked to the binding behind your channel that does not handle your command  ?

**Comment by msfunty** [comment]
I changed the title.
Normal switch items work, but when mapping is involved it doesn't.

Sitemap (partly):
Switch item=Ventilation_Fan_Level label="Fan" mappings=[1="A", 2="1", 3="2", 4="3"]

Items (partly):
Number  Ventilation_Fan_Level "Fan [%d]" <selfAiring> 	{comfoair="fan_level"}


That problem also exist for items binded to KNX and others. So I assume it is not related to a certain binding.

**Comment by lolodomo** [comment]
Maybe a consequence of my PR #3368. I will check.

**Comment by lolodomo** [comment]
Unfortunately, I can confirm the issue using the scene widget from the demo sitemap.

**Comment by lolodomo** [comment]
I think it has no link with my change but might be again a consequence of PR #3332.
@triller-telekom : could you please take a look ? You can reproduce the issue with the demo sitemap using the 2 "scene" widgets (selection and switch/mappings).
Probably the issue is the conversion of number to ON/OFF ?

**Comment by lolodomo** [comment]
I think the fix is to not try converting to OnOffType when the widget is a switch with mappings.

**Comment by triller-telekom** [comment]
Indeed you are right. In this case the Sitemap Switch points to  a NumberItem which usually is not on/off but multiple settings. I created a PR to fix this.

But I am curious on how many more bugs we find due to my conversion method in PR #3332... Initially I fixed a bug with it but it looks like a lot of functionality relied on that bug ;-)

**Comment by lolodomo** [comment]
Your PR was a clear improvement but it would have needed more testing ;)
