### ISSUE TITLE
[audio] New exception type if audio sink doesn't support the served AudioStream.

### ISSUE THREAD

**Issue by cweitkamp** [eclipse/smarthome#3566]
When looking into [https://github.com/openhab/openhab2-addons/pull/2303](https://github.com/openhab/openhab2-addons/pull/2303) we came up with the question if we need an additional exception type `UnsupportedAudioStreamException` to be thrown if an audio sink doesn't support the served `AudioStream`. Currently e.g. the [Sonos](https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/SonosAudioSink.java) binding throws an `UnsupportedAudioFormatException` - which type is not exactly matching the use case - whereas other bindings (e.g. Kodi in the linked PR or [AllPlay](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.allplay/src/main/java/org/openhab/binding/allplay/internal/AllPlayAudioSink.java)) only log a warning or throw an individual exception.

Any thoughts?

**Comment by maggu2810** [comment]
If there are more bindings that support only an subset of streams we could also thing about a new function `Set<Class<? extends AudioStream>> getSupportedStreams()`.
There is already a similar function for the supported formats.

I prefer "check precondition, then do it or leave it" instead of "do it and catch throwables".

So, the new exception itself is okay to exist, but I also would prefer if the caller first checks the supported formats and calls the `process` function only if it is a supported stream.

**Comment by cweitkamp** [comment]
@maggu2810 One question: If we introduce a new abstract `getSupportedStreams()` method in the class [AudioSink](https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core.audio/src/main/java/org/eclipse/smarthome/core/audio/AudioSink.java) it will have an impact on all existing AudioSink implementations in the different bindings. Is there a strategy to handle such changes?

**Comment by kaikreuzer** [comment]
We could work with a default implementation on the interface for backward compatibility.

What I do not like about `getSupportedStreams()` is the fact that an implementing service needs to be aware of the different types of streams. So adding new classes might become difficult in future.

So what do we actually need here?
The issue that we came across is that we didn't find a way to play unbounded streams. But actually, not being able to really stream gives us a constraint on the size as well - we should not buffer 200MB of a "fixed length" stream either. So just checking for a class won't really help us.

In general, I am still of the opinion that we should rather find a way to properly stream ANY audio stream to the sinks - if we succeed in that, we do not need to define any additional meta-data here.

**Comment by maggu2810** [comment]
> What I do not like about `getSupportedStreams()` is the fact that an implementing service needs to be aware of the different types of streams. So adding new classes might become difficult in future.

Perhaps I am wrong, but `getSupportedStreams()` does not introduce that type dependency. The type of the stream is already checked by the different `process` function.

So, if we find a way that every binding only needs to support audio streaming or not and all different types could be handled generic, is would be the best option.

Also I don't think that a binding needs to be aware of all types. It needs to state what the devices it operates on supports. The framework could then create the supported stream type from the existing stream type if a conversion is necessary.

> @maggu2810 One question: If we introduce a new abstract `getSupportedStreams()` method in the class [AudioSink](https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core.audio/src/main/java/org/eclipse/smarthome/core/audio/AudioSink.java) it will have an impact on all existing AudioSink implementations in the different bindings. Is there a strategy to handle such changes?

> We could work with a default implementation on the interface for backward compatibility.

As long as we don't have a stable API I would prefer to fix the bindings instead of adding the default function. It should be done to keep the API stable or to set a default behavior.
In this case I assume fixing the bindings that throw a compilation failure would be much cleaner.

**Comment by cweitkamp** [comment]
PR #3764
