### ISSUE TITLE
Better handling of configuration file parsing errors

### ISSUE THREAD

**Issue by ThomDietrich** [eclipse/smarthome#3567]
https://community.openhab.org/t/influxdb-openhab2-does-not-store-everyhour-but-everychange/29305/11

The error is related to `*.persist` files but is probably transferable to other configuration files. I remember problems due to malformatted configuration files have been discussed in the past. If the syntax of the file derives to some degree from the expected standard format, the file or parts of it (in this case the Strategies block) is ignored without even logging an error.

Logging a parsing error should be the minimal solution for this issue.

I'd expect this issue and the extend of it to get clearer by checking the parsing code. Thanks for looking into this.

**Comment by sjka** [comment]
The ModelRepository does some syntactical validation, and if that fails it will be logged and the file will be ignored completely. It's like that since about end of January this year, in order to mitigate exactly this. So what dimensions of "the past" are you referring to? Before or after?

I just checked the syntax:
* The position of the curly braces have no impact at all.
* The default block is optional, so by means of the file format this is okay.

And if you reference a strategy which does not exist, then this non-existing strategy won't me executed, of course. The rest will. 

> Logging a parsing error should be the minimal solution for this issue.

Unless you can give some more concrete examples where it fails to work, we have to consider this as done by #2872.

**Comment by kaikreuzer** [comment]
As https://github.com/openhab/openhab2-addons/pull/2285 was just merged, I actually expected a much more detailed error report here after my comment in the forum ;-)
I could have told you that validation errors are shown. I understood you that you wanted to have a change in the DSL grammar to allow a more flexible syntax. But this would need to be described in detail.

**Comment by ThomDietrich** [comment]
@kaikreuzer I can't give more details. I'm just the one creating the issue as the result of the community thread discussion and the claims made there. Ideally I would have investigated the problem myself but at that moment I was not able to interact with my system, nor did I have the time.
I believe it's better to open an issue prematurely (although not ideal) rather than forgetting about it.

@sjka Thank you very much for looking into this (and for your PR)! It's likely that my experience from "the past" was from before January. Also if I'm not mistaken your PR is not part of openHAB 2.0 GA, therefore not active in stable setups.

Anyhow, thanks for the quick resolution of the issue, I agree the Ticket can be closed.

**Comment by sjka** [comment]
> Also if I'm not mistaken your PR is not part of openHAB 2.0 GA, therefore not active in stable setups.

Yes, I think so too.

If you encounter some concrete issues anywhere (which are not yet fixed in 2.1-SNAPSHOT) I'm always happy to have a look!
