### ISSUE TITLE
Discovery should be able to activate per bridge, not per binding

### ISSUE THREAD

**Issue by cdjackson** [eclipse/smarthome#3605]
If a binding has multiple bridges, it should be possible to activate discovery for each bridge separately - not just for the binding. At the moment it's not possible to select which bridge is activated for discovery, and therefore which bridge a new device will attach to, and this is a problem where this needs to be controlled.

**Comment by kaikreuzer** [comment]
This is only relevant for bindings, which have an active pairing mechanism for having new devices join the network, right? 
We still do not have any clean support for such cases in general - e.g. it isn't possible to easily remove undesired devices from the network again, once they have joined and are listed in the inbox.

Is it a realistic use case for end users to have multiple such bridges? Or is it merely something helpful for development purposes?

**Comment by cdjackson** [comment]
Yes, I guess it’s just for bindings with active join mechanisms… And yes, it’s a realistic case - we have this problem now on ZWave as people are using multiple dongles and they can’t control which dongle a device will connect to. Another use case I have is BLE devices have limited connections available - maybe as few as 3 simultaneous connections. If people want / need multiple connections, it may require multiple dongles and in order to avoid them all just joining the first bridge they find, we’d need some control over this.

Re leaving the network - I have a mechanism in ZWave, but it’s not especially nice. It uses a config parameter as an action to put the stick into exclusion mode for 30 seconds. A more standard mechanism would be nice, but that’s another issue...

**Comment by rodneyrehm** [comment]
> We still do not have any clean support for such cases in general

Is that maybe because you're "abusing" the discovery/inbox - which was intended for *announcing* (IP) devices available for pairing - for actually *pairing* devices?

> Is it a realistic use case for end users to have multiple such bridges? 

I'm not sure about current HMIP support, but Homematic used to have network extenders to support larger homes. Our suolution hasn't supported this in the past, but it'd be great if we could support this in the future.

> It uses a config parameter as an action to put the stick into exclusion mode for 30 seconds. A more standard mechanism would be nice, but that’s another issue...

What happens if the device is put into the inbox (i.e. connected with the controller) and ESH goes down before the DiscoveryResult's TTL is reached (subsequently triggering the exclusion)? unless DiscoveryResults are persisted, this would lead to ESH not knowing the Thing yet, but the device thinking it's connected to the controller - no?
