### ISSUE TITLE
State changes of group members don't trigger rules anymore

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#3622]
So far, it was possible to group items (even without a function) and use this group as a trigger ("received update") for rules whenever one of its members changed their values.

see https://community.openhab.org/t/groups-seem-to-be-broken/29307

This regression was introduced in #3314.

**Comment by triller-telekom** [comment]
The way I understood group states are that they are calculated by their members through a function. So it a state of an item has changed the group state should be recalculated.

This is done [here](https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/GroupItem.java#L314).

Such a recalculation only makes sense if there is a function attached to a group. Also a function only makes sense if the group is of a certain type, otherwise the function isn't able to deal with the different states of them. These were the rationale behind the changes I introduced in #3314.

What I didn't consider is people using (plain, i.e. without type and function) groups just to group (different) items not only for the purpose of grouping them for a GUI but that they expect a notification on the `GroupItem` if a member changes.

Since I only call the `setState` method in the case a function is set on a `GroupItem` I will not reach [this notification line](https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/GroupItem.java#L330). The `setState` can only be called if the state of the group itself changes and that can only occur if the group state is calculated through its members. However the notification within `setState` should be called!

To sum it all up: My changes of #3314 corrected a lot of "strange and wrong" behaviour of groups, but I missed the notification of `GroupItem`s in case of an item change.

My proposal to fix it would be to notify the listeners in case of a state update from a member also if there is no function.

**Comment by kaikreuzer** [comment]
I think in general @triller-telekom fix makes sense, it is just unfortunate that it has these side effects on existing users.

The question to me really is: WHAT update do group items without a type receive? I see in the rules that they react on "received update", but it is really completely undefined what goes in there - and as such, having such a state update of the group is simply wrong.

I remember discussions where people asked for a trigger that triggers if any item of a group received an update and then also wanted to have the concrete item at hand. This is probably the really required use case here and having an undefined state update on the group is just an ugly workaround for it.

I'd also like to add that there are already other fixes that actually [rely on the fact that there isn't a flood of unnecessary group item updates](https://github.com/eclipse/smarthome/pull/3495#discussion_r119040105) - if we bring them back, we would need to find other solutions for those.

**Comment by triller-telekom** [comment]
Since this issue seems to affect quite a lot of people and there might be some further follow up discussions on how to solve it properly, I did some tests to find a workaround.

Every group that should receive state changes on their member items need a type, so please define the group like this:
```
Group:Switch myGroup
```
instead of
```
Group myGroup
```

It doesn't matter what kind of types you put into such a group. The `Switch` type is just a workaround for now. Because this type tells the `GroupItem` that its `baseItem` is a `Switch` and ALSO ADDS a `function`: `Equality`. Since the group then has a function it will receive updates if one of its member items changes their state.

Please note that the `state` of such a group will be `UNDEF` after a member item has changed. That is because if you insert different types, for example `Switch` and `Dimmer` into that group, then the ´Equality` function compares `states` like `ON` and `100` which are not the same and thus result in the group state `UNDEF`.

**Comment by hoggle64** [comment]
This workaround fixed my problem.

**Comment by kaikreuzer** [comment]
The new behavior has been documented for existing users (see https://github.com/openhab/openhab-distro/wiki/openHAB-2.1-Release-Notes#general-changes), so we can close the issue as it is not considered as a bug.

**Comment by NickWaterton** [comment]
All I can say is that this change has utterly, utterly broken my Openhab2 configuration.

The following lines in my zwave.items file
```
Group:Number:SUM() Energy_Daily "Total Daily kWh usage [%.2f kWh]" <energy> (gB, energy)
Group:Number:SUM() Energy_Monthly "Total Monthly kWh usage [%.2f kWh]" <energy> (gB, energy)
```
Don't work for some reason, and cause the **WHOLE** zwave.items file to be thrown out. Similar lines in all my items files cause them to be thrown out (with no errors in the logs either). Thus I have no items, and the sitemap won't load at all ("does not exist").

Debugging is a nightmare in the new 2.1 version. I would like to give a big thumbs down to the new "throw everything out if there is one error" system. Without the UI up, I can't even tell where to start looking for the problem. this makes OH2 unacceptably fragile. New users will have **NO HOPE** of ever getting anything working.

I won't tell you how many hours it took me to find the problem lines, but you may be able to sense my frustration.

I have no clue how to find this hidden problems, given the total lack of error messages.

Can anyone say what is wrong with these items? worked fine in OH1 and OH2 2.0.

**Comment by NickWaterton** [comment]
OK, found it, the lines should be:

```
Group:Number:SUM Energy_Daily "Total Daily kWh usage [%.2f kWh]" <energy> (gB, energy)
Group:Number:SUM Energy_Monthly "Total Monthly kWh usage [%.2f kWh]" <energy> (gB, energy)
```
Note: No () after SUM.

I already fixed one error where I was using:
```
autoupdate=false
```
instead of
```
autoupdate="false"
```
All with no help from the error logs.

On to the next items to fix.

**Comment by sjka** [comment]
> I have no clue how to find this hidden problems, given the total lack of error messages.

Just have a look at your log file (openhab.log in your case). You _will_  find the corresponding error:

```
11:25:15.700 [WARN ] [el.core.internal.ModelRepositoryImpl] - Configuration model 'test.items' has errors, therefore ignoring it: [1,18]: no viable alternative at input ')'
```

**Comment by NickWaterton** [comment]
It would be helpful if the logs were more specific, so far I have found many "undocumented differences of opinion" I call them, not errors (as they worked fine in 2.0).

So far I have found that you now can't have a Group without an item. You must have an item, _even if that item does not exist_ - previously you did not need to define an item for a group.

so:
```
Group label="Camera Control" icon="camera" {
```
does not work (and breaks OH totally),
but
```
Group item=made_up_thing label="Camera Control" icon="camera" {
```
Works. I just have to go through 1000 lines to find these (and others - did you know you can't have an empty frame?, or that autoupdate=false breaks openhab now?).

Then I have to go through 7000 lines of rules to find what is the error there, with no help from the error logs (and I don't consider "there is an error" to be useful).

This is worse than moving from OH 1.9 to 2.0 OMG.

**Comment by kaikreuzer** [comment]
Really, I do not know why a WARNING like
```
Configuration model 'test.items' has errors, therefore ignoring it: [1,18]: no viable alternative at input ')'
```
should cost hours of tracking down the error in your file. It clearly states that in line 1, column 18 it finds an illegal closing bracket.

> now can't have a Group without an item

For the first time, ESH is now telling your that you can't and it gives you appropriate error messages.
Your were NEVER allowed to use groups without items, just [check the docs](http://docs.openhab.org/configuration/sitemaps.html#element-type-group).

The general advice to anyone having issues with getting the syntax right is to use the Designer as an editor as this will give you syntax errors right in the editor already and you should have never ended up with such broken configuration files.

**Comment by NickWaterton** [comment]
Sorry, there are no such error messages in any of my logs (and I have them set to DEBUG). I have looked, both for ERROR and WARN messages, but no, nothing.

Even if I had found them, the syntax is very obscure, I'm not sure I would have understood what it was telling me.

This is why I call them "undocumented differences of opinion", because the OH documentation is so contradictory and out of date, that you are never sure what is correct and what is not.

You say "check the docs" Like there is some sort of bible, well I did. _From your link_. This is what it says:

`Group [item=<itemname>] [label="<labelname>"] [icon="<iconname>"]`

According to my understanding, items in `[]` are **optional**. Now you are saying that suddenly _item_ is not optional (and never was), and how do I not know that - other than it has always worked without it up to now, and the documentation says that it is optional.

And despite what you say, I have **NO ERROR/WARN** messages in the logs at all. The effect is to make your sitemap dissapear without trace, with no clue as to why.

In my opinion, this change has made OH2 so fragile, that hardly anyone who isn't a seasoned expert at OH2 configuration will be able to get anything to work.

Feel free to disagree with me, but the users will tell. See how many messages there are on the boards "where is my sitemap", and variants of the same. I urge you to rethink this strategy, as users will leave very quickly if they cannot get result.

**Comment by kaikreuzer** [comment]
> I have NO ERROR/WARN messages in the logs at all

If this is the case, I fully agree with you that it is a critical issue that needs to be fixed.
So please be so kind and open a new issue here in the issue tracker with a short example of a sitemap that gets swallowed without any log message and it will be dealt with. Thanks!
