### ISSUE TITLE
[Paper UI] Show configuration page of newly added things, if required params are not set

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#3657]
If a new Thing is added from the Inbox, which does not have all required parameters set in the config (e.g. because some user password is required), no handler is instantiated and the Thing status goes to "configuration pending".

It is difficult for the user to figure out that he needs to go into the Thing configuration to fill in some more details, before he can use the device.

I'd therefore suggest that the Paper UI should directly jump to the Thing configuration page in such a situation.

**Comment by kaikreuzer** [comment]
@htreu As discussed :-)

**Comment by Pavion** [comment]
See also some community ideas here:
https://community.openhab.org/t/paperui-prompt-for-credentials-config-after-discovery/36892/6

**Comment by htreu** [comment]
Hi @Pavion, I read [your suggestions ](https://community.openhab.org/t/paperui-prompt-for-credentials-config-after-discovery/36892/6)and like `#2` quite a lot:
Upon discovery approval you could check the configuration description of the thing and apply the check you suggested (are there empty && required properties in the config) and then redirect to the thing edit page instead of thing view. The check of the config description should be done here too, as the thing might have empty properties which are not required but set to default values by the binding.

`#1` is, as you mentioned a too generic solution, `#3` would only be the start of a way more complex wizard-like approach which I would like to start only if we have the requirements to do so. 

I would be happy to see your PR here!

**Comment by Pavion** [comment]
Hello Henning and thank you for your answer. As you can see, I've submitted a PR, but can't get past the automatic checks although I've signed the ECA as required. Also I can't understand why Travis CI build fails. Do I miss something..?
As it's a rather small change regarding but one function, I'd have no problem with you or someone else taking over and implementing this solution. For me it's not the matter of putting my name somewhere but to contribute by offering a solution, which is feasible both for a developer and an end user. 

_P.S. Schönen zweiten Advent! :)_

**Comment by htreu** [comment]
Hi @Pavion, I just saw your PR and joined the discussion. Thanks for taking the time and contributing! Especially for PaperUI and JavaScript there are not so many contributors.

_Ich bin etwas spät dran, Danke Dir :-)_

**Comment by triller-telekom** [comment]
This was implemented in PR #4702 so this issue can be closed. @sjka @kaikreuzer
