### ISSUE TITLE
Paper UI: display for Contact items with MAP transformation

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#3821]
What is the expected display in Paper UI for a contact channel ? I get no value and no control displayed.

**Comment by htreu** [comment]
I can confirm that in the current master there is no display for the a ContactItem. Although in my OH 2.0 instance it works just fine.

**Comment by htreu** [comment]
Update: configuring my channel-type (temporary contact channel and thing type for the Magic bundle) with state options (OPEN/CLOSED) and `readonly=true` it works just fine:

<img width="362" alt="screen shot 2017-07-10 at 17 37 12" src="https://user-images.githubusercontent.com/1729268/28026465-72250cf4-6596-11e7-8a90-db71d823c7f1.png">

**Comment by lolodomo** [comment]
Is `readonly=true` required to have `OPEN` displayed ?
What do you mean by "thing type for the Magic bundle" ?

**Comment by davidgraeff** [comment]
I used to send OnOffType.On/Off to contact items, because I understood contact as a read-only switch basically (so that all boolean types are allowed). But in recent ESH versions that didn't work for me as well, including a warning message in the log, that the type is wrong though.

**Comment by htreu** [comment]
@davidgraeff that sounds like a state conversion issue, please create another issue for this.
@lolodomo from what I see from the code `readonly=true` is required for Contact items to display correctly. Otherwise (`readonly=false`) there is a dropdown with state description options if available. The Magic Bundle is a new OSGi bundle which provides a dummy binding with dummy devices. In case you start ESH/OH from the Eclipse IDE you can choose to activate it in the launch config and then add dummy devices. Its in an early stage and Contact items are not supported yet. I will create another PR for this.

See #3555 for the initial commit.

**Comment by htreu** [comment]
See https://github.com/eclipse/smarthome/pull/3828 for the contact sensor PR.

**Comment by lolodomo** [comment]
Ok I will check if my channel is declared as read only.

**Comment by htreu** [comment]
Since this seems to be a configuration issue, can we close here?

**Comment by lolodomo** [comment]
Please give me a moment to check that and I will close the issue.

**Comment by lolodomo** [comment]
It is not working with Paper UI packaged in snapshot 951.
Here is my channel:
```
	<channel-type id="status">
		<item-type>Contact</item-type>
		<label>zone_status</label>
		<description>xxx</description>
		<state readOnly="true"></state>
	</channel-type>
```
Hre is one of my item:
```
Contact PorteEntree "Porte entrée [MAP(fr.map):%s]" <door> {channel="powermax:zone:maison:entree:status"}
```
**Please note that there is a MAP transformation.**

**Comment by lolodomo** [comment]
I discovered that something changed. Now I get the unmapped state displayed, CLOSED for example. That is already better.
But is it expected that the MAP function I put in my item label to be ignored ?

**Comment by htreu** [comment]
This is unfortunately not yet implemented in Paper UI. The transformation is actually applied to the current state and also send via the REST interface as a separate `transformedSate` property on the item DTO. I will issue a PR with the transformation result taken into account when rendering the items.

**Comment by kaikreuzer** [comment]
I think for the Paper UI it is ok (while not perfect) to show the un-transformed state only. We currently do not even offer setting a custom label formatting for items in general - this is only possible in items files since the parser also registers as a StateDescriptionProvider; but we e.g. cannot do the same for items that are created through the Paper UI.

The formatted state is clearly a feature meant for UIs and different UIs might actually do a different formatting (that's why we have it considered in the sitemap events). For this reason, I do not think that it should be added to the "raw" ItemStateEvents. In the light of https://github.com/eclipse/smarthome/issues/5337, I would rather hope that the Paper UI can in future use a dynamically created sitemap for its control view - this would give us many more features for customisation of this view.

**Comment by flaviocosta-net** [comment]
Kai, in the current state of the sitemap implementation, it is already taking the state descriptions into account:
```
    public String formattedState(Item item) {
        State state = item.getState();
        if (state instanceof UnDefType) {
            return null;
        }
        StateDescription sd = item.getStateDescription();
        if (sd == null) {
            return state.toFullString();
        }
        try {
            return state.format(sd.getPattern());
        } catch (IllegalFormatConversionException e) {
            logger.error("Conversion error on item " + item.getName(), e);
            throw e;
        }
    }
```

One substantial difference between the existing and the new sitemap implementation is that most/all formatting would now be managed on the server side, the client already gets a String ready to be presented, taking into account language/i18n/patterns, so the value will be displayed the same way regardless of the UI.

Another important change is that the new sitemap tells clients what they want to show, but it does not say where the information comes from: values may come from items, things, from another sitemap... but the client UI only sees containers and data on them. The item ID does not appear anywhere in the rendering model that is sent to the UI.

However, it should not be too difficult to generate a dynamic sitemap that lists all items, where the item ID comes as a label atom and the transformed/formatted value is a text atom, or something else with a specific semantic that the Paper UI expects to use.

**Comment by htreu** [comment]
Thanks @flaviocosta-net for stepping in here. The Paper UI currently gets all its information from the none-ui REST endpoints. The control page is a mix from the things/thing-types/channel-types/items REST endpoints and from the ItemStateChanged events over SSE. With the new sitemaps we might also get the state updates from the sitemap events and picking up the server side rendered state text.

**Comment by flaviocosta-net** [comment]
@htreu, I did a few changes to the code and now, with a small class and a short transformation script, I have a sitemap that automatically lists all items in the ItemRegistry:

![2018-06-26_16-51-28](https://user-images.githubusercontent.com/35621323/41938497-398d3b7a-7961-11e8-9618-0d7fed11757f.png)

The id of each widget matches the item id, so it can be related to the source item, for instance:

```
  {
      "components": [
        {
          "type": "icon",
          "data": "/icon/string?state\u003dHello+SmartHome%2521"
        },
        {
          "type": "label",
          "data": "DemoString"
        },
        {
          "type": "text",
          "data": "Hello SmartHome!"
        }
      ],
      "id": "DemoString",
      "type": "widget"
    },
```
The date time value does appear very nicely with the standard settings, need to check why.

I also tried to create a similar sitemap for the ThingRegistry, but the interface does not have a method such as ItemRegistry.getItems() that lists everything in that registry. What exactly the Paper UI does to display a list of Things?

**Comment by htreu** [comment]
The ThingRegistry has the `getAll` and `stream` methods which will give you access to all elements in the registry.
Paper UI uses the thing REST interface which in turn uses the `stream` method.

**Comment by flaviocosta-net** [comment]
I see, the method `getAll` is inherited from the `Registry` interface, that's why I couldn't find it. So it now works with the ThingRegistry too, the sitemap is not really great in terms of visual rendering but it does work to validate the initial concept:

![2018-06-27_14-16-11](https://user-images.githubusercontent.com/35621323/41991784-b26b5faa-7a14-11e8-8208-71f5ec3057b4.png)

I am now working on SSE, so once it's ready it may be easier to visualize how sitemaps like these could be somehow integrated in the Paper UI.
