### ISSUE TITLE
Unable to get all rules using over Http Rest Request

### ISSUE THREAD

**Issue by plamen-peev** [eclipse/smarthome#3903]
I am using the `RuleResource.get(@QueryParam("prefix") final String prefix, @QueryParam("tags") final List<String> tags)` metod.
In my request `prefix` and `tags` parameters are not specified so I am expecting all rules to be returned.
However after some debugging i fond that the `tags` parameter is not null, despite the fact that it is not specified in the request, so in the current implementation only the rules that are with no tags are returned.

**Comment by danchom** [comment]
The method RuleRegistry.getByTags(String... tags) works in following way:
1)  tags == null  the method returns all rules
2) tags == empty string array it returns a list of rules without tags
3) tags.size > 0  returns all rule which contains specified tags.
If the rest request can't create a method call with null arguments for tags IMHO it is better to treat an empty list as tags == null, otherwise we can't return all available rules by the rest.
Also I see that getByTag(String tag) returns all the rules when the tag was not specified. I think the method getByTag and getByTags should not have different semantics.
@kaikreuzer what do you think?

**Comment by kaikreuzer** [comment]
Yes, I absolutely agree with you - (2) does not make sense and it should behave just like (1). Can you create a PR for it? Thanks!
