### ISSUE TITLE
[config] Attribute 'bindingId' is not allowed to appear in element 'config-description:config-descriptions'.

### ISSUE THREAD

**Issue by cweitkamp** [eclipse/smarthome#3908]
When looking into [openhab/openhab2-addons#2494](https://github.com/openhab/openhab2-addons/pull/2494) we came up with the following question: The xml files for defining `thing-types` (or `bridge-types`, etc.) requires a `bindingId` attribute in the `thing:thing-descriptions` tag. Assuming the `bindingId` attribute belongs in an OH2 binding related `config-description:config-descriptions` tag results in an error while compiling the binding:

```
[ERROR] ERROR found by checkstyle: .binding.avmfritz/ESH-INF/config/config.xml:5 Attribute bindingId is not allowed to appear in element config-description:config-descriptions.
```

Example `config.xml` (abstract):
```
<?xml version="1.0" encoding="UTF-8"?>
<config-description:config-descriptions bindingId="avmfritz"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:config-description="http://eclipse.org/smarthome/schemas/config-description/v1.0.0"
	xsi:schemaLocation="http://eclipse.org/smarthome/schemas/config-description/v1.0.0  http://eclipse.org/smarthome/schemas/config-description-1.0.0.xsd">

	<config-description uri="config:fritzdevice">
		<parameter name="ain" type="text" required="true">
			<label>AIN</label>
			<description>The AHA id (AIN) that identifies one specific FRITZ! device.</description>
		</parameter>
	</config-description>

</config-description:config-descriptions>
```

Is this the expected behavior? If yes, why?

**Comment by kaikreuzer** [comment]
Yes, absolutely expected, since config descriptions are used in many contexts, so having a "bindingId" element in its schema simply does not make sense. I have created #3914 to make this more clear in the documentation.

Note that the config URIs must adhere a certain naming convention, which is roughly documented [here](https://www.eclipse.org/smarthome/documentation/development/bindings/xml-reference.html#xml-structure-for-configuration-descriptions): For thing-types, it has to be `thing-type:fritzaha:fritzdevice` and not `config:fritzdevice`.

Hope this helps!

**Comment by cweitkamp** [comment]
Perfect. Thanks.
