### ISSUE TITLE
 Wrong switch state shown in Basic UI

### ISSUE THREAD

**Issue by breti** [eclipse/smarthome#3909]
I've noticed that there seems to be an issue with "invisible switches" in Basic UI.

This is the switch definition in the item file:

`Switch gl_vsw_tresorpin "PIN visible" { expire="10s,command=OFF" }`

And this is the sitemap:

`Switch item=gl_vsw_tresorpin label="Show PIN" icon="keyring" visibility=[gl_vsw_tresorpin!=ON]`

Turning on the switch will make the switch disappear because of the visibility-setting - that's fine. After the 10s timer of the Expire-Binding has expired, the switch will turn off and be visible again. That's fine too - but the switch is shown as ON, not OFF then! I've to reload the browser page (Ctrl+F5) to have the switch shown as OFF.

There is no such issue with the openHAB Android App.

Just for clarification: A label with a PIN is shown in my setup as long as the switch is hidden.

Item:
`String gl_str_tresorpin "[%s]" { http="..." }`

Sitemap:
`Text item=gl_str_tresorpin label="PIN" icon="keyring" visibility=[gl_vsw_tresorpin==ON]`

Openhab2 2.1.0-1 on Raspbian
Tested with Firefox 54.0.1 on Win7 and Android, Chrome 60.0.3112.78 on Win7

**Comment by kaikreuzer** [comment]
@resetnow Maybe another one for you to analyse? Thx :-)

**Comment by resetnow** [comment]
This is because when both visibility and state change, BasicUI handles it as "either-or", so only visibility is applied. This is, of course, wrong, I just didn't think there could be events like this. Fixing this is a matter of changing a couple of lines in BasicUI (https://github.com/eclipse/smarthome/blob/master/extensions/ui/org.eclipse.smarthome.ui.basic/web-src/smarthome.js#L1740), but there could be side effects and it needs some testing.
