### ISSUE TITLE
Paper UI: problem when scrolling in the control page

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#3959]
On an Android tablet using Paper UI (in Chrome) and the Control page, as soon as I scroll with my finger, Paper UI is automatically switching to the next tab (location), even if I scroll only in the middle of a page.
On a PC using the mouse to scroll, this problem does not exist.
It makes the control page unusable on a tablet or phone.

**Comment by htreu** [comment]
Confirmed!

**Comment by htreu** [comment]
Here is a good explanation of the bug we are facing: https://stackoverflow.com/questions/41567668/md-swipe-left-and-md-swipe-right-is-doing-same-functionality-moving-only-left

previous to the latest PaperUI refactoring there was something which looks like a workaround "now". @kaikreuzer, @lolodomo what do you think? Since the md-swipe issue is still open, do we need this feature? The most easy thing would be to disable left/right swipe for tab changes atm. The workaround I removed was the major performance killer when changing tabs (which is _fast_ now).

**Comment by htreu** [comment]
Here is the original issue from angular: https://github.com/angular/material/issues/10145
I will investigate the workarounds described there.

**Comment by maggu2810** [comment]
@htreu Thanks for having a look at
