### ISSUE TITLE
Discovery service updating thing configuration automatically

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#3975]
I discovered that a thing configuration is dynamically and automatically updated when the same thing is discovered again with different properties.

The code that is doing that is here:
https://github.com/eclipse/smarthome/blob/master/bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/PersistentInbox.java#L200

It looks very strange that discovery could have priority to what the user defined. The thing could even have been defined in a config file and in this case should not be updated.

In my opinion, once the thing is created, it should not be updated by a discovery service.

What do you thing ? Is it a bug like I think ?

**Comment by htreu** [comment]
From the code you referenced it seems like it was done on purpose. The dynamic thing update was introduced with https://github.com/eclipse/smarthome/pull/52.

**Comment by lolodomo** [comment]
Can we discuss whether it is a good think or not ?

**Comment by htreu** [comment]
Absolutely. I don´t know the API yet so I will have to look into it first. But my opinion is to have this "feature" and at the same time let the API support you in case you don´t want to update or at least update only parts of the configuration.

**Comment by kaikreuzer** [comment]
This is an important feature that is indeed there on purpose.
It allows discovery services to update the things that they have provided in the first place, so that they stay current and usable. Use cases are e.g.:
- updating the IP address of a device, if it is regularly changing (as it might be assigned through DHCP)
- "local" things (such as astro&weather) can have their location updated, if the system location is moved.

**Comment by lolodomo** [comment]
But if your thing is defined in a configuration thing file ? Its configuration should not be updated ?
Is the advice to never use in a config thing file a thing UID that can be used by the discovery service ?
