### ISSUE TITLE
Eclipse compilation errors in core bundles - Annotations

### ISSUE THREAD

**Issue by doandzhi** [eclipse/smarthome#4045]
Hello, I am facing compilation problems on **org.eclipse.smarthome.core** bundle. The compiler says

>  _"The annotation @NonNull is disallowed for this location"_.

  I checked which version of **org.eclipse.jdt.annotation** and it is **1.1.0** which according to this [this](https://stackoverflow.com/questions/22531237/how-to-enable-jsr308-null-annotations-on-types-in-eclipse ) article is not compatible with Java 8. Tried to delete the whole bundle pool in case it uses cached jars from there but this didn't solve the problem. There is a newer version of the same .jar in the bundle pool but eclipse uses the older one. 

Does anyone have this problem too, and how could it be solved?

**Comment by svilenvul** [comment]
I can confirm the problem with Eclipse Neon Build id: 20160613-1800 and the latest changes from the master branch.

**Comment by triller-telekom** [comment]
@doandzhi Do you also have Eclipse Neon? Does it work in maven for you?

**Comment by doandzhi** [comment]
Yes it is built succesfully in Maven. 
I use Eclipse Version: Mars.2 Release (4.5.2)
Build id: 20160218-0600

**Comment by triller-telekom** [comment]
@doandzhi: Oh, Mars is even older that Neon. By that time these annotations where not fully supported. We would kindly ask you to update to Eclipse Oxygen since this is our official development environment: https://www.eclipse.org/smarthome/documentation/development/ide.html

@svilenvul: Does ESH compile clean with maven for you? If not what is the error message? And if it does, would you also please update to Oxygen?

**Comment by svilenvul** [comment]
Yes, ESH compiles clean with maven. I will update to Oxygen.

**Comment by doandzhi** [comment]
After updating to Eclipse Oxygen the issue is resolved. Thanks a lot :)
