### ISSUE TITLE
[Documentation/API Doc] BaseThingHandler.getBridge().getHandler()

### ISSUE THREAD

**Issue by davidgraeff** [eclipse/smarthome#4069]
The JavaDoc of `BaseThingHandler.getBridge().getHandler()` says "the handler can be null", but in recently added extensions I saw this:
```
    @Override
    public synchronized void initialize() {
        ... omitted ...
        TradfriGatewayHandler handler = (TradfriGatewayHandler) getBridge().getHandler();
        String uriString = handler.getGatewayURI() + "/" + id;
        ... omitted ...
    }
```
There is no null check. Is `getHandler()` guaranteed to return a handler if called in a thing `initialize`?
This issue is either/or:
* Change the JavaDoc to mention when and under which conditions the bridge handler is available.
* Correct the usage of the method in the above binding.

**Comment by sjka** [comment]
Good point - in fact both is correct. The `getHandler()` method _can_ return `null`, but since #2087 is it guaranteed by the framework that children only get initialized once the bridge successfully got initialized, therefore at this point in time the bridge's handler cannot be null. 

Would a "(can be null for a Thing which is not initialized)" be more clear from your perspective? 
I guess it would help to additional link to https://www.eclipse.org/smarthome/documentation/concepts/things.html#thing-status. However, I'm not really sure whether it is appropriate to point from JavaDoc to a website or not. The risk is that the URL gets outdated easily without noticing it.

**Comment by davidgraeff** [comment]
@sjka I would duplicate the information of the linked page instead.

Can we make it even more explicit like in:
"(can be null for a Thing which is not initialized. Note that a Bridge is guaranteed to be initialized before its children. It is therefore safe to call getBridge().getHandler() for a subordinate Thing)"
