### ISSUE TITLE
Add a property to thing types that declares extensibility

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#4146]
A few thing types have a fixed set of defined channels, while others are meant to have a flexible number of channels defined by the user.

We would need a way to identify the "extensibility" of a thing type, so that this can be checked by the framework and nicely be supported by UIs (see e.g. #4142).

Possibly it is also good to give a list of channel-types which are allowed to be added (not all types will be valid in general, I guess).

**Comment by htreu** [comment]
Since this change would add just another property to thing-types I would recommend to move the ThingType class from 4 - 5 constructors to a Builder pattern. I will deprecate the current constructors but will add the `extensible` property only to the builder.

any objections @maggu2810, @kaikreuzer, @sjka?

**Comment by maggu2810** [comment]
Okay for me.
