### ISSUE TITLE
Exported handlers

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#4330]
Let's continue this one: https://github.com/eclipse/smarthome/pull/4311#issuecomment-331152732

If handlers are exported the API of the handler implementations must not use private packages ("must" if we don't like to create a broken API).

See e.g. http://enroute.osgi.org/tutorial_wrap/270-private-references.html

So, we should consider if we want exported handlers and fix the existing ones (some time) or if we should change the archetype and existing bindings.

**Comment by triller-telekom** [comment]
I agree that exporting our handlers is useless if they provide methods that can only be used together with other data types of that bundle which are not exported. So either we also export them (is that an option?) or we have to change them in a way that their public API does not reference internal data types anymore.

I would not go the way of not exporting the handlers because as @kaikreuzer suggested in https://github.com/eclipse/smarthome/pull/4311#issuecomment-331152732 it might be useful to extend a handler some time.

**Comment by maggu2810** [comment]
Only using exported stuff in handlers could lead to exporting a lot of packages and I don't know if every developer could keep track of what needs to be exported and what not (at least the one that is not familiar with all that OSGi stuff).

If a products needs a proprietary extension of a bundle, why not using a fragment?

**Comment by kaikreuzer** [comment]
> Only using exported stuff in handlers could lead to exporting a lot of packages

To precise this it should say "using exported stuff in the public API of handlers", so it isn't that bad - it simply means that people should carefully think about what they publicly add to their handlers. https://github.com/openhab/static-code-analysis/issues/210 sounds like a good idea in order to avoid unwanted exposure.

> why not using a fragment?

Mainly because fragments are considered bad and should be avoided where ever possible besides a few specific use cases (e.g. supplying additional resources or native code). They are simply causing too many issues regarding the lifecycle.

**Comment by maggu2810** [comment]
Let's pick this up again:
If you think it could be useful, it is okay for me to export them.
But does it make sense?
I assume exporting the handlers could be useful if you want to create a derived class. Then you will also need a thing handler factory that create instances of your subclasses for special thing type IDs.
If the handlers are exported and used by subclasses in special products -- and this is wjat we want to support -- we also need to think about API changes of handler implementations as we will break third party stuff similar as if we change the API of a core package...

**Comment by triller-telekom** [comment]
FYI: With the [ZigBee binding](https://github.com/openhab/org.openhab.binding.zigbee) we now have one which has an `ZigBeeCoordinatorHandler` in one **core** bundle and a specific handler in another bundle. And in this use case it absolutely makes sense to export the handler.
