### ISSUE TITLE
Roadmap / Continuous plan for dependency version updates

### ISSUE THREAD

**Issue by davidgraeff** [eclipse/smarthome#4353]
New versions usually come with improved developer comfort or even necessary functionality. It usually makes sense to not fall behind too much.

The current situation is that a new version of a dependency is agreed on by all developers. But the process how this happens is not formalized.

## Proposal: Yearly dependency check

I propose a yearly dependency version update vote mechanism. It works like this:
* Every year all major dependencies (Java/OSGi/UPnP/etc) are checked for an update to the latest or the highest minor or longterm version. Benefits are worked out (usually less own code).
* A subscription system is offered, so that someone can register and get notified when such an event will take place.
* A grace period / period of request for comments allow all users/consumers of ESH to comment on dependency updates.

 Everybody that is using ESH and interested in its development would subscribe to this event and is able to comment on why a newer version might not fit his or other use-cases and point out release blockers.

If people are only consuming and not contributing (participating in those votes), it is not ESHs fault, if those solutions do not work with newer ESH versions.

At the moment I don't see the roadmap of ESH regarding dependencies and how it can stay up-to-date.

**Comment by sjka** [comment]
> New versions usually come with improved developer comfort or even necessary functionality. It usually makes sense to not fall behind too much.

No. You must not forget that ESH is a framework intended to be used to build solutions on top, be it commercial or open source, run on big servers or on feeble "embedded" hardware inferior to a RPi1. Therefore this project has to facilitate many different needs. Our goal should not be to always require the latest (and admittedly sometimes greatest) versions of any library, but rather stay as compatible as reasonably possible in order to allow a maximum of flexibility running together with other bundles in the same stack while keeping the footprint as small as possible. Hence you don't see a roadmap for always staying up-to-date as this is neither feasible nor viable. 

> usually less own code

...and usually a much bigger footprint of which only a fraction is actually used (see guava, jersey, apache commons, ...). 

There might of course be good and valid reason to update the minimal version requirement of a certain library, but in the end this has to stay a case-by-case decision.

There are restrictions which are annoying, like e.g. OSGi 4.2, Guava, Java 8 (since a couple of days) and the like. They hurt us all and every maintainer is well aware of these. However, you would not solve this with your proposal - they will all get rejected anyway.

The process however is very clear: We have Github issues if anybody sees a need to update a minimum requirement and in the end it's the committers who decide and possibly cast a veto on that. See also here: https://dev.eclipse.org/mhonarc/lists/smarthome-dev/msg00057.html

I'm sorry to say that I do not share your initial assumption and therefore I also don't see the need for inventing any new process for it.

**Comment by davidgraeff** [comment]
But that's my point. You will never know if users of ESH are still using an older version for example OSGi 4.2 and there is no formal check of current implementations of OSGi either, therefore the burden on the contributors might be for no reason. Technically you can stick with OSGi 4.2 forever of course, everything can be developed around and implemented in own ways. But the OSGi committee decided for a reason to deprecate certain features and introduced newer concepts in 4.3. I'm not so sure if ESH framework users are so happy to not be able to use osgi 4.3 capabilities for instance. But OSGi is just an example.

**Comment by sjka** [comment]
> But the OSGi committee decided for a reason [...]

...seriously?

My previous comment obviously was not clear enough: Some adopters of ESH actually _are more than happy_ that there is such a huge grace period for updating their whole stack. You might be able to imagine that Eclipse SmartHome is not the only dependency they have. 

If that helps you: Nobody is happy with being stuck on such an old version and nobody is doing this "just for fun" or because new features aren't appreciated.

**Comment by davidgraeff** [comment]
This issue is not about ESH being on older dependency versions. It is about that there is no clear public communication on how/when/by whom the dependencies get updated. I wouldn't have asked or opened this issue if the process was clear to me. I made one suggestion in the initial post on how I imagine an open/public process could look like. But that's really just a suggestion, it's not the main aspect of this issue.
