### ISSUE TITLE
Thing().setProperties() only works if parameter/property is String type.

### ISSUE THREAD

**Issue by lsafelix75** [eclipse/smarthome#4354]
Unlike DiscoveryResultBuilder() which accept Map<String, Object> properties, Thing().setProperties(Map<String, String>) only accept "String" as its value.  This causes problem if the property/parameter deffned as type="integer" in things.xml. Is this intention to avoid changing "thing" parameters in runtime?

**Comment by sjka** [comment]
You have to distinguish properties and configuration: Configuration is what the handler needs in order to successfully communication with the device (e.g. IP addresses, IDs, passwords,...) which normally the user has to configure (unless the device can be discovered automatically by a discovery service). For those, you have to have a config description, usually as XML in the binding's ESH-INF folder. They can have different types (Strings, Numbers, Booleans).

Properties on the other hand are technical stuff that the user has nothing to do with or which at maximum have informational character (e.g. firmware version). They might be detected by the discovery service or by the handler and updated correspondingly.  They can be changed by (and only by) the handler at runtime, never by the user. They can be strings only and they are not defined in the thing type XMLs.

The BaseThingHandler has methods for altering both, configuration and properties. 

Does this make it more clear and answer your question?
