### ISSUE TITLE
Paper UI: new discovered things should be displayed as ignored when they are auto ignored

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#4360]
When you ask for new discovery things for example for Sonos, new things are displayed at screen as "not ignored" while they are in fact ignored due to the automatic ignore mechanism (existing thing with the same representation property).
If you reload the inbox by clicking on the menu item "Inbox" then they are ignored as expected.

**Comment by htreu** [comment]
This is the result from my analysis:
* `PersistentInbox` will pass a newly discovered thing to the `thingAdded` method from the `AutomaticInboxProcessor` which does the `autoIgnore` check.
* the `AutomaticInboxProcessor` will call `setFlag(thingUID, IGNORED)` on the `PersistentInbox`. This marks the discovery result from the storage with the flag, not the instance which is currently processed by the `PersistentInbox`.
* `setFlag` will immediately post an `updated` event for the discovery result (note: this happens before an `added` event is emitted).
* Paper UI will happily ignore the `updated` event since no entry for the given thingUID is present in the Paper UI inbox repository.
* `PersistentInbox` will then post an `added` event with the instance the discovery service created. This instance does not have the `IGNORED` flag set.
* Paper UI will pick up the `added` event and display the discovery result as a new result, just because the flag is still set to `NEW`.

A refresh of the Paper UI inbox will retrieve all discovery results from the backend. Since the `IGNORED` flag was correctly set to the instance from the storage Paper UI will then correctly hide the auto-ignored result.

**Comment by htreu** [comment]
One solution would be to reload the discovered result from storage before emitting the first `add` event. This will then provide the correct flag.
The unused `updated` event is obsolete (in this scenario) but does not hurt as long as the client checks for existence of the given thingUID.
