### ISSUE TITLE
[PaperUI] Discovery and TTL

### ISSUE THREAD

**Issue by martinvw** [eclipse/smarthome#4391]
Yesterday I was totally confused about a (to me unknown) feature of the Inbox / Discovery. I was not aware that discovery results could have a TTL so I spent one hour to find out why my discovered items where disappearing from the Inbox, both the logs and the PaperUI did not given any indication that it would be removing then at certain time or why it was removed.

See also: https://community.openhab.org/t/network-snapshot-inbox-being-filled-and-emptied/34968/3

Imho it would be great if we could show it in the paperUI, eg "this Thing will be removed if not accepted after 2 minutes", so for that it would be needed to expose the TTL property in the REST endpoint and render it in the paperUI. 

If you agree it will be easy for me to add it to the REST endpoint, updating the PaperUI might be a little bit harder but should not be impossible.

WDYT?

**Comment by sjka** [comment]
Isn't it rather like that: If the device is still there, it will be re-discovered before the TTL expires, therefore refreshing it. So it will stay in the inbox.
If the device is gone, it will after the TTL expired also be removed from the inbox. But adding it in that situation is pretty pointless, as the device will remain "offline".
So if a device vanishes from the inbox although it is still available, then maybe the TTL settings in that binding are too short?

**Comment by martinvw** [comment]
Okay, in this case the network binding only executes a scan on demand so it is not refreshed.

**Comment by sjka** [comment]
Okay, that won't work then... 

In any case, I think it makes sense to add the expiry timestamp to the REST API. 

I'm just not sure how to present it in the PaperUI without cluttering the list further - it's hard enough to read already. Maybe @htreu has an idea how to do it "the material way"?

**Comment by htreu** [comment]
I dont know if there is "the material way". But what you see often now is a circle around the avatar filling up (like downloads) or declining (like TTL). Here is my suggestion:

![inbox-ttl](https://user-images.githubusercontent.com/1729268/31384727-77d9c35c-adc0-11e7-82b4-389ddcc3278e.png)

I would also add a tooltip which explains the circle and tells about the remaining time. wdyt?

**Comment by martinvw** [comment]
> I would also add a tooltip which explains the circle and tells about the remaining time. wdyt?

Great 👍

**Comment by hreichert** [comment]
Looks good!

**Comment by kaikreuzer** [comment]
Sorry guys, this does not make sense to me (despite the fact that I think it is ugly and against MD, sorry @htreu 😛 ).

> "this Thing will be removed if not accepted after 2 minutes"

This is not what the TTL wants to express. The TTL is a technical mean for discovery services to automatically declare that a Thing is not available anymore - so that it does not explicitly have to call the "removeResult" method. The normal situation should be that the Thing is re-discovered within the TTL, so it simply stays available in the inbox.

The TTL is NOT meant to rush the user to accept a discovery result asap. This is not the summer clearance sale.

So I guess the discussion comes up because the network binding simply misuses this feature. Using a TTL without background discovery imho does not really make sense.

**Comment by martinvw** [comment]
I created a new issue in the openhab repo: https://github.com/openhab/openhab2-addons/issues/2776
