### ISSUE TITLE
ConfigDispatcher: Config file processing order-dependent if exclusivePIDs are used

### ISSUE THREAD

**Issue by hsudbrock** [eclipse/smarthome#4424]
### Context
The `org.eclipse.smarthome.config.dispatch.internal.ConfigDispatcher` processes configuration files in the `processConfigFile` method. How a config file is processed depends on whether it has a so-called _exclusive PID_ or not: A config file has an exclusive PID if its first line starts with a PID marker _pid:_ followed by a PID.

### The Issue
Consider the following two config files:

a.cfg:
```
pid:some_pid
A=some value
```

b.cfg:
```
some_pid:B=some other value
```

Then the processing of these two files in the ConfigDispatcher depends on the order in which the two files are processed:
* If `a.cfg` is processed first, then the resulting configuration contains both properties `A` and `B` for PID `some_pid`.
* If `b.cfg` is processed first, then the resulting configuration only contains property `A` for PID `some_pid`.

Frankly, I do not know which result is the correct one, but I think that it is not correct that it depends on the order in which the files are processed. 

One result of this 'order dependency' is that the test `ConfigDispatcherOSGiTest#theSameLocalAndGlobalPIDsInDifferentFilesAreConsideredOnePID` sometimes fails on my machine (it uses two config files with the same structure as in the example above) - depending on the order in which the two config files used by this test are processed (the config files are processed sorted by lastModified date, which is the same on my machine for both used config files). 

### Expected behavior?
As stated above, I do not know what the expected behavior is. However, from looking at the code of the method `ConfigDispatcher#processConfigFile` I see that there is some logic that tries to skip config properties for a PID if this PID is used as exclusive PID in another config file. Currently, this logic works only if the file with the exclusive PID is processed last. So I guess that the expected behavior could be that config properties for a PID are ignored if there is another config file which has this PID as exclusive PID. However, from looking at the unit test referenced above, skipping properties in files without exclusive PID is not expected. But of course this unit test might simply be buggy...

To conclude: Does anyone here know what is the intended behaviour here regarding parsing of config files with and without exclusive PIDs?

**Comment by kaikreuzer** [comment]
@htreu Could you have a look? I agree with @hsudbrock that there should be no dependency on the processing order.

**Comment by htreu** [comment]
Yes, agreed. The processing order should not change the result here.
Since we want .cfg files with an exclusive PID marker (like `pid:my.service.pid` in the first line) to be really exclusive and especially benefit from the file delete mechanism we should drop all other entries with this pid from other files. So when a file later defines a key/value pair for an already known exclusive PID (e.g. by defining the pid inline like `my.service.pid:key=value`) this line will be skipped.
The only order dependent processing is then given for .cfg files which define the same exclusive pid in the first line: here the file processed last will win and have its values passed to the configAdmin. An error should be logged in case this situation occurs.
