### ISSUE TITLE
HTTP resources not resolved from fragment bundles

### ISSUE THREAD

**Issue by htreu** [eclipse/smarthome#4433]
The registered HTTP services and resources (ClassicUI, BasicUI, PaperUI) do not resolve resource requests using the bundles ClassLoader any more. This looks like a bug in the current Equinox implementation used by ESH, see https://bugs.eclipse.org/bugs/show_bug.cgi?id=526150.
This has the effect that resources from fragment bundles are not loaded any more. When deploying the org.openhab.ui.paperui fragment bundle with the IDE runtime setup the fragment resources do not get served.

Workaround: as described in the bug report we will provide our own implementation of the HttpContext which behaves correct according to the OSGi spec.

**Comment by maggu2810** [comment]
Do we really want to add code to work around a bugs that are platform / solution specific?
At least the bug and the workaround does not affect me. But why do we need to introduce a custom HttpContext implementation in the Eclipse SmartHome framework?

If there is a bug in e.g. Apache Felix SCR version that I would like to use should the ESH framework work around that bug or should I patch the third party code or use a version / alternative implementation without that fix?

What about other HttpService implementations? Are there more buggy ones?

**Comment by maggu2810** [comment]
If you want to use a filter, it only affects (AFAIK) servlets using the same HttpContext.
So if we would work around the buggy Equinox version, I would prefer if we do it in a way that also introduce a missing feature (so we have at least a really feature for that change).

We could create an HttpContextProvider interface that defines a method:
```Java
HttpContext getHttpContext(final String id)
```

The id is choosen by service but should be perhaps in the commain reverse domain name manner as PIDs.

A simple implementation of that interface should be provided as a OSGi component in a separate bundle (so products can simple use their own one).

We could think about an implementation that returns it own HttpContext implementation - and always a new one - to fix the Equinox bug.
There could be another one that returns always the same HttpContext (or specific by the ID) to apply a filter for all existing servlets.
...

**Comment by kaikreuzer** [comment]
@maggu2810 This is not a workaround for a specific solution, but it is a feature of ESH. We state that all we require is an OSGi 4.2 compatible HttpService and we offer customization of the UIs through fragments. It turns out that this does not work with Equinox and this is even the implementation we use within the ESH IDE - so not an ideal situation. We could wait for Equinox to be fixed and update our TP then. But this will take a while.

As some background: When working on https://github.com/eclipse/smarthome/issues/579 I noticed that we will sooner or later need a central service that provides us with HttpContext. I therefore took this issue as an opportunity and suggested @htreu to directly start this path for fixing this issue. The idea was to have a HttpContextFactory, which we can use to deliver default/authenticated/non-authenticated/etc contexts to the UIs as desired. The exact interface of such a service clearly still needs to be discussed (and extended over time).

**Comment by maggu2810** [comment]
The second part of your comment is not about an workaround but an ESH feature.
But the initial comment is IMHO a workaround as we need an OSGi 4.2 compatible HttpService (as you have written) and it only seems that the Equinox implementation does not fit to the specification itself. The real requirement is not that it needs to work with Equinox.
So, if we ignore the second part of your comment, we should choose an implementation for the IDE used TP that does offer an OSGi 4.2 compatible HttpService.

But, we have the other part...
And it seems also to fit in some way to my comment above (okay you have chosen `HttpContextFactory` and mine has been `HttpContextProvider`).

I assume it should be able for solutions to use its own factory implementation or do we need to handle all the different possible context providers in ESH itself and make it configurable?

Do you think using a shared context for all servlets could be a use case, too?

**Comment by htreu** [comment]
Sorry guys, I missed your comments while implementing #4435. Lets take the discussion about the interface design and use cases to the PR.
