### ISSUE TITLE
FR: Interactive charts for basic ui

### ISSUE THREAD

**Issue by mueller-ma** [eclipse/smarthome#4495]
I found this libary https://frappe.github.io/charts/ which generates interactive JS charts.

**Comment by sjka** [comment]
When I read https://github.com/eclipse/smarthome/issues/4493#issuecomment-341885573 correctly, then this would not imply simply exchanging one chart library for another, but actually also changing the Basic UI architecture from server-side rendering to client-side rendering. With #4493 being fixed by #4496 I don't see any need to implement such a major change. Therefore I'm closing this for now.
