### ISSUE TITLE
Basic UI: Refresh disabled forever for image/chart when they are first hidden

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#4507]
The JS code is disabling the refresh of image/chart that are hidden. It is done at this line:
https://github.com/eclipse/smarthome/blob/master/extensions/ui/org.eclipse.smarthome.ui.basic/web-src/smarthome.js#L445
It happens because `_t.image.clientWidth === 0` when the image/chart is hidden.
The problem is that the refresh is never re-enabled when the image/chart is then made visible.

**Comment by lolodomo** [comment]
@resetnow: what was the reason to disable the periodic refresh ?
I would suggest to not disable the periodic refresh but just to do nothing when `_t.image.clientWidth === 0`.
WDYT ?

**Comment by resetnow** [comment]
This is to clear refresh requests for images that don't even exist anymore (say, you moved to another sitemap page). Otherwise you may end up with a big number of handlers and callbacks after a while. Another solution would be not to use clientWidth hack but append an attribute to image controls before moving to another page.

**Comment by lolodomo** [comment]
Or we could simply re-enable the refresh when making the image visible.

**Comment by resetnow** [comment]
You just need to keep track of whether the refresh was actually disabled before enabling it again. To avoid this hack, you could also clear interval before performing page navigation.
