### ISSUE TITLE
Add a link on "how to report a security vulnerability" on the website

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#4515]
Every Eclipse IoT project is expected to have a link on "how to report a security vulnerability" on its website, see https://wiki.eclipse.org/IoT/PMC#Releases.

We therefore need to add such.

**Comment by triller-telekom** [comment]
According to the cited website the Eclipse team states that a link to them is enough:

`
The project has to include a link on the main project home page on "how to report a security vulnerability", a properly labeled link to https://eclipse.org/security/ is fine
`

However on that website there are two possibilities on how to deal with a report. The reporter can write an email to security@eclipse.org or use the button labeled "Report a potential vulnerability now". The later one points to the Eclipse bug tracking system and the reporter is encouraged to set the bug to "committer-only" so the bug is not made available publicly.

This leaves the following questions open:

1. Are we fine with a link to that website? - If not, what else shall we offer as a contact option?
1. How should that link be called and where should it be placed? Somewhere in the footer near the "Connect with Eclipse SmartHome" twitter and github buttons?

I would vote for providing a link to the Eclipse website because they have the central email address and also the bug tracker with bugs that are not shown publicly.

**Comment by maggu2810** [comment]
Isn't the report about a security vulnerability also a contribution? So, we could place it to the contribution page.

**Comment by sjka** [comment]
That depends in the interpretation of "on the main project home page". I.e. if the intention was to make it reachable from the _first_ page or just _anywhere_ on the home page.

**Comment by triller-telekom** [comment]
My intention behind my post was to put it on the *first* page, so it is easily reachable and not hide it somewhere in the documentation. But for sure we could also add it on the *contribution* site, too.

**Comment by kaikreuzer** [comment]
1. Yes, adding a link is enough, that's what I requested in the issue (" is expected to have a link ").
2. The IoT-PMC expects the link to be "easily findable" by anyone visiting the website in order to report a vulnerablity. It does not have to be on the first page, but it also should not be hidden anywhere deep down.

I would suggest to add a sentence with the link in the "Join the Community!" section on the homepage (https://www.eclipse.org/smarthome/) as well as adding a paragraph on how to report vulnerabilities at https://www.eclipse.org/smarthome/documentation/community/contributing.html#getting-involved.

**Comment by maggu2810** [comment]
@kaikreuzer I moved this 0.9.0 project task to "Done" (on Github's project view).
