### ISSUE TITLE
System channels for 2-button trigger channels (a.k.a. rockers)

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#4541]
We currently have the following two channels:

| Channel | Events |
|:---|:---|
| system.button | SHORT_PRESSED & LONG_PRESSED & DOUBLE_PRESSED |
| system.rawbutton | PRESSED & RELEASED |

As discussed in the context of the [enocean binding](https://community.openhab.org/t/enocean-bindings-opencean-or-aleoncean/12493/58) but certainly also relevant for others, it would make sense to also have something like `system.rocker` and `system.rawrocker` for 2-button controls with their corresponding events.

**Comment by maggu2810** [comment]
@sjka Do you think about a event table that looks like this one:

<table>
  <tbody>
    <tr>
      <th>Channel</th>
      <th>Events</th>
    </tr>
    <tr>
      <td>system.rocker</td>
      <td>
        <ul>
          <li>UP_SHORT_PRESSED</li>
          <li>DOWN_SHORT_PRESSED</li>
          <li>UP_LONG_PRESSED</li>
          <li>DOWN_LONG_PRESSED</li>
          <li>UP_DOUBLE_PRESSED</li>
          <li>DOWN_DOUBLE_PRESSED</li>
        </ul>
      </td>
    </tr>
    <tr>
      <td>system.rawrocker</td>
      <td>
        <ul>
          <li>UP_PRESSED</li>
          <li>UP_RELEASED</li>
          <li>DOWN_PRESSED</li>
          <li>DOWN_RELEASED</li>
        </ul>
      </td>
    </tr>
  </tbody>
</table>

**Comment by sjka** [comment]
Sure, that would be symmetric to the "single button" ones. 

I was just not sure about the UP/DOWN, as they could of course be horizontally aligned as well. Or would then be intuitive like LEFT==DOWN and RIGHT==UP? Or should be rather use something which does not imply any orientation - but I couldn't find anything better yet which doesn't carry yet another meaning by itself.

Having said that, I'm personally fine with the UP/DOWN proposal!

**Comment by maggu2810** [comment]
EnOcean is using "I" and "O" and it's meaning could differ by the region (some use I for UP and other ones O for UP).
A unspecific name instead of up / down is okay for me, too and would perhaps make sense WRT the left / right example.
DIR1 and DIR2 (direction) is okay for me, too.

**Comment by cdjackson** [comment]
Can I suggest an alternative to DOWN_DOUBLE_PRESSED to use numbers instead of DOUBLE. This is easier to use when more than double is used (eg 4x = quadruple, 5x = ??) - DOWN_PRESSED_2X, DOWN_PRESSED_3X, DOWN_PRESSED_4X etc).

I would like to see up to 5X added to fix in with ZWave definition.

**Comment by sjka** [comment]
> Can I suggest [...] I would like to see up to 5X added to fix in with ZWave definition.

Good point. Even if not as a system constant, this would allow bindings like zwave to extend it consistently. 
Unfortunately that was done differently for the "single button" case previously. I'm not sure if it is a good idea to break that? And having it inconsistent also is not nice. What do you think?

**Comment by htreu** [comment]
+1 for direction agnostic naming of the buttons. I already like the DIR1/DIR2 proposal. Even A/B would be okay for me.

**Comment by sjka** [comment]
The downside of such completely agnostic names is that they are absolutely unintuitive in both orientations. Considering that these are pairs of buttons which control the same item together I think it would be nice to have something which is intuitive enough so people need to look their meaning in the binding documentation.

**Comment by sjka** [comment]
However, the more I think about it the harder it gets finding something that abstracts up/down and right/left without adding some functional meaning which we definitively do not want at that stage. So A/B becomes more and more viable IMHO.

**Comment by kungfoolfighting** [comment]
I would not necessarily want A/B because often A and B are already used to distiguiish between the channels. It would get pretty confusing if you have direction A and B and channel A and B. I like DIR1 and DIR2 better. That way even the directions could be numbered, if you had buttons that work like old-school digital joysticks that go into 8 directions.

**Comment by kungfoolfighting** [comment]
Another thing: Why do we have the distinction between button and rawbutton?
I didn't understand it when I first saw it, and I still don't.
Isnt the conversion between two raw-button presses to a double-press something that a profile should do?
If I wanted to have a something happen when I do two long-presses after each other, for example, I would have to first convert simple button presses to long presses in the binding, and then detect two long-presses in the profile to convert them to something else.
So the question is: Shouldn't all conversion from raw button events happen in profiles? (This is the way I am currently doing it for very long presses in order to initiate dimming.

**Comment by kaikreuzer** [comment]
> So the question is: Shouldn't all conversion from raw button events happen in profiles? 

In theory yes, but the tricky question is: Where do the profiles live? For EnOcean, we indeed get the "raw" information (pressed/released) out of the button. But or other systems, such as Homematic and KNX, the processing is already done in the device itself - my KNX rockers e.g. directly send short press & long press events, I cannot get hold of a "released" from it. That's why we have defined these different channels as they address different behavior.

>  So A/B becomes more and more viable

I agree with @kungfoolfighting that this isn't ideal either as for example EnOcean uses A/B for the double-rocker devices - so at least here this would be pretty confusing.

> EnOcean is using "I" and "O"

[Asking Google about it](https://www.google.de/search?q=rocker+switch&tbm=isch), this actually does not seem to be a too bad choice - but it somehow implies a meaning and I hear that you prefer completely agnostic naming.

DIR1/DIR2 seems to be the best compromise then - I didn't see anybody that is against this choice, right?
