### ISSUE TITLE
org.eclipse.smarthome.io.javasound has no voice

### ISSUE THREAD

**Issue by SilentTheseYears** [eclipse/smarthome#4547]
org.eclipse.smarthome.io.javasound has no voice (version ref-0.9.0.b6)
the bundle error:
java.io.IOException: mark/reset not supported
	at java.io.InputStream.reset(InputStream.java:348)
	at com.sun.media.sound.SoftMidiAudioFileReader.getAudioInputStream(SoftMidiAudioFileReader.java:139)
	at javax.sound.sampled.AudioSystem.getAudioInputStream(AudioSystem.java:1113)
	at org.eclipse.smarthome.io.javasound.internal.AudioPlayer.run(AudioPlayer.java:60)

**Comment by maggu2810** [comment]
What are the necessary steps to reproduce that error?
Is the error still be present in the recent master?

**Comment by SilentTheseYears** [comment]
just test ref-0.9.0.b6,the recent master is not . And found the paper ui --> Configuration --> System,it is not save the change configuration , when exit [Concierge](https://github.com/eclipse/smarthome-packaging-sample) and restart [Concierge](https://github.com/eclipse/smarthome-packaging-sample).

**Comment by maggu2810** [comment]
* I used a dist with ESH 0.9.0.b6
* I started the dist
* I opened the Paper UI in the browser
* I navigate to Configuration -> System
* I stopped the dist
* I started the dist again
* I opened the Paper UI in the browser
* I navigate to Configuration -> System
* Still no error in the log.

So please come with a step by step guidance, how to reproduce the error.

**Comment by SilentTheseYears** [comment]
I step by step guidance use paper ui system configure,setup the configure,but  restart [Concierge](https://github.com/eclipse/smarthome-packaging-sample),the change configure didn't save and reset to null.It's no error log writting to the  log file.  The javasound has no voices,but webaudio has voices.The javasound has error log:
java.io.IOException: mark/reset not supported
at java.io.InputStream.reset(InputStream.java:348)
at com.sun.media.sound.SoftMidiAudioFileReader.getAudioInputStream(SoftMidiAudioFileReader.java:139)
at javax.sound.sampled.AudioSystem.getAudioInputStream(AudioSystem.java:1113)
at org.eclipse.smarthome.io.javasound.internal.AudioPlayer.run(AudioPlayer.java:60)

**Comment by sjka** [comment]
If I understand you correctly, then you are facing the problem that the configuration is not persistent across restarts of your system. ESH uses the OSGi config admin in order to store configuration changes. To what I can see, this works perfectly. If this would not be the case, then please re-open this issue.

Now, the question is what happens to the values in the config admin service after a reboot. This clearly is beyond the scope of the Eclipse SmartHome framework. As you mentioned concierge, then I'd suggest you should have a look there. I can only speculate, but if you are using the felix config admin implementation, it stores its data somewhere in the filesystem - when you then run the OSGi container in a way that it cleans all the data on every restart (like e.g. the [sample packing](https://github.com/eclipse/smarthome-packaging-sample/blob/master/distro/runtime/concierge/smarthome.xargs#L9) does), then also your configuration settings will be gone. But as I said, I'm just speculating and this clearly not the right place to get support on that! 

In any case, I will close this here as being out-of-scope.

**Comment by SilentTheseYears** [comment]
@sjka May be you are right. Now, I have wrote a binding which use the aplay. aplay is a command which play the audio. It is work well. May be my system cause this problem. I use the embedded yocto linux system.
