### ISSUE TITLE
Define OAuth client library

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#4551]
[More](https://community.openhab.org/t/openhab-2-oauth-library/8710) and [more](https://github.com/openhab/openhab2-addons/pull/2407/files#r132824492) bindings require access to servers through OAuth(2).

It is therefore a recurring question on how this should be best implemented.
The Jetty HTTP client does not bring any built in support for OAuth.
So we would either have to define an ESH-API on top of that and implement it ourselves against the Jetty libs, or we have to find a suitable library.

At a first glance there is the [Google Oauth Java Client](https://github.com/google/google-oauth-java-client), but this builds on Apache HTTP client and thus would add multiple MB to our stack, which is imho not acceptable.
Another one is [Apache Oltu](https://cwiki.apache.org/confluence/display/OLTU/OAuth+2.0+Client), which only depends on Apache Commons libraries.

I am not sure what is the best choice - defining an ESH API might give us most flexibility and having a proper HTTP client at hand, there actually should not be too much logic involved in the implementation. And we should have some experts in the community that might be able to contribute some decent code to get started on this.

**Comment by ollie-dev** [comment]
I would really like to see an included and standardized OAuth2 client. It should support automatic token refresh handling, like the [Google OAuth2 CredentialRefreshListener](https://developers.google.com/api-client-library/java/google-oauth-java-client/reference/1.20.0/com/google/api/client/auth/oauth2/CredentialRefreshListener).

**Comment by smerschjohann** [comment]
The swagger [codegenerator](https://github.com/swagger-api/swagger-codegen) makes use of the Apache Oltu library. In other projects, we successfully used it in combination with the retrofit2/rxjava codegenerator. In addition, this can be easily integrated in okhttp.

I'm not sure what the ultimate goal here is. Do you only want a default OAuth2 implementation or a way to communicate with (possible swagger enabled) REST services etc.?

**Comment by Hilbrand** [comment]
The [Oltu](http://oltu.apache.org/) library is in attic (meaning retired) so that doesn't seem to be a viable option.

The google library isn't moving very fast support for newer dependencies, as that seems to be causing internal problems with google (see the issues/prs on the github page). However it does seem possible to write a custom HttpTransport implementation. Such a custom implementation could be used to wrap around the eclipse/jetty httpclient. For the Spotify Binding  (https://github.com/openhab/openhab2-addons/pull/2295) I'm trying a proof-of-concept to see if I can use the google library and what the foot-print would be.

For a generic authorization implementation this would require some generic authorization page I guess? Some centralized place to persist tokens. How would that look like? How should that work in PaperUI? I'm trying to get some input to see if that is something I can (re)write the Spotify binding to use such a generic service and how difficult that would be.

**Comment by kaikreuzer** [comment]
Hey @Hilbrand, sorry, this issue here wasn't kept up to date - with https://github.com/eclipse/smarthome/pull/5142, we meanwhile actually HAVE a custom OAuth client library, which builds on Jetty HTTP client and persists the tokens. So I think this issue can be closed and you should have a try whether this suits your needs.

Note that the library so far works headless only. My idea would be to add an "oauth context" information to the access token configuration parameter of a Thing and that we could make the Paper UI do the authentication through the redirects. That part isn't yet specified or implemented, though.
