### ISSUE TITLE
OSGiEventManager should do safe method calls and identify handlers that are blocking

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#4591]
[There are reports](https://community.openhab.org/t/jetty-update-karaf-4-1-3-upgrade-and-full-lsp-support/36354/7?u=kai) where the OSGiEventManager gets blacklisted by the OSGi EventAdmin, which results in an unusable system state. Instead of being blamed, the OSGiEventManager should instead make sure to identify blocking handlers itself and return quickly.

**Comment by sjka** [comment]
Even if it would take such buggers out of the game, I still see two remaining problems:

The default timeout of e.g. [felix event admin](http://felix.apache.org/documentation/subprojects/apache-felix-event-admin.html) is 5s, which is exactly the timeout of the safe method caller in this case. So at the point where it identifies a slow event subscriber, it is already to late and the event manager got banned itself. 

If the internal timeouts are fixed, then the same would arise if there are multiple slow subscribers because they are informed serially. 

The "proper" solution I guess would be to inform the subscribers asynchronously completely (and thereby taking care to ban slow subscribers itself). Wdyt?

**Comment by sjka** [comment]
no major objections so far, so I'll look into making an according PR proposal.
