### ISSUE TITLE
IDE: several errors relative to @NonNull fields that may have been not initialized

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#4671]
With the current source code, I have several errors in Eclipse IDE.

Here are few examples where I have errors:
https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/internal/common/SafeCallerImpl.java#L45
https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseThingHandler.java#L102
https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseThingHandler.java#L119
https://github.com/eclipse/smarthome/blob/master/bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/AbstractDiscoveryService.java#L100

I have to say that a Maven build is working well, my problem is only in Eclipse.

**Comment by lolodomo** [comment]
It seems to be relative to fields marked with `@NonNullByDefault({})`.

**Comment by maggu2810** [comment]
Do you use the Eclipse SmartHome IDE setup or the openHAB one?
Which version of the Eclipse IDE you are using?

**Comment by lolodomo** [comment]
Eclipse version: Oxygen Release 4.7.0.

How can I check if I am using the Eclipse SmartHome IDE setup or the openHAB one ?
I can tell you that I have all repo including Eclipse Smarthome in my Eclipse setup. I can update Eclipse Smarthome or openHAB.

Note that the problem has appeared with the recent changes only, I had no this problem one week ago.

**Comment by maggu2810** [comment]
The used setup file does matter because it contains the settings of the Eclipse IDE.
* Eclipse SmartHome is using this setup file: https://github.com/eclipse/smarthome/blob/master/targetplatform/EclipseSmartHome.setup
* openHAB is using this setup file: https://github.com/openhab/openhab-distro/blob/master/launch/openHAB2.setup

If someone change settings in the setup you are using for the installation, the changes are applied to your Eclipse IDE.

So, if you state "I have all repo" (and I interpret "all" as ESH + OH) you are using the openHAB setup instruction file.

I am using:
* Eclipse "Version: Oxygen.1a Release (4.7.1a)"
* Eclipse SmartHome setup instruction file

and don't see this errors.
So, perhaps you could first try to bump your Eclipse IDE to "Oxygen.1a" and if this does not help create an issue in openHAB distro that their setup file should be changed.

AFAIK The `@NonNullByDefault({})` is not interpret correctly by "older" JDT compilers so perhaps you need to use 4.7.1a to get a more recent one.

**Comment by lolodomo** [comment]
Thank you for your help.
I just started an update. Lots of things. I will report once it is finished.

**Comment by lolodomo** [comment]
After the full update, the package explorer is empty !
My run configuration is still working, showing all bundles.
In Naviagate => Open setup, I can see different setups + workspace. Workspace looks apparently good.
How can reload the package explorer ?
Sorry, I am sure that it is a newbee question :)

**Comment by maggu2810** [comment]
You state that the Package Explorer is empty, so I am sure you "see" the Package Explorer itself. But just to be sure:
* Windows, Show View, Package Explorer

The Package Explorer contains a traingle on its upper right side.
You can change the "Top Level Elements" to "Projects" or "Working Sets".
If you choose "Projects" you should see all imported projects (regardless of the assigned working set).
Perhaps you want to use "Working Sets" (I don't know.)
Under "Select Working Sets" you can choose the "Working Sets" that should be visible.

**Comment by lolodomo** [comment]
I have everything in Project explorer.
I don't remember which view I was using. Is it the package explorer which groups projects more or less by repo ? This one is empty.

**Comment by lolodomo** [comment]
Ok I was in fact certainly using the Project Explorer with top level elements set to working sets.

**Comment by lolodomo** [comment]
I am now with Version: Oxygen.1a Release 4.7.1a.

**Comment by maggu2810** [comment]
And it the error still present after a full rebuild?

**Comment by lolodomo** [comment]
After an additional update and a full rebuild, everything seems to be ok again.
Thanks again for your advices.
