### ISSUE TITLE
[Tradfri] Ikea Tradfri Gateway Communication Error

### ISSUE THREAD

**Issue by leoMehlig** [eclipse/smarthome#4936]
After my Tradfri Gateway automatically updated itself to version 1.3.14 it stopped working with openHAB 2.2.

It gets reported as `OFFLINE (COMMUNICATION_ERROR)` and the log shows `[DEBUG] [.tradfri.internal.TradfriCoapHandler] - CoAP onError` regularly.

The release notes mention some changes to CoAP. Does anyone else have this issue?

**Comment by leoMehlig** [comment]
@eiGelbGeek  The next morning everything worked again. Thought it was related to the updated since it happened immediately after it update. 
Should I close this again?

**Comment by rralf** [comment]
Somehow sounds like this could be duplicate of my (yet unsolved) bug report #4839 ?

**Comment by leoMehlig** [comment]
The only difference is, that it couldn't communicate right away after startup.

**Comment by eiGelbGeek** [comment]
Just had the time to test the new firmware on the Tradfri Gateway ... Fresh OH 2.2.0 installation, Tradfri Binding installed, Tradfri Gateway added, security code entered. It seems to work. No crash in the last hour.

**Comment by sjka** [comment]
Just for the record: we are talking about gateway firmware version 1.3.14 where it so far appears to be fixed. Correct?

**Comment by eiGelbGeek** [comment]
Yes Firmware 1.3.14 works for me

**Comment by leoMehlig** [comment]
The initial problem seems to be fixed somehow. The gateway is not running for a few days without any problems. Maybe this was due to some hiccup during the update??
I'm closing this for now.

**Comment by sjka** [comment]
Cool, thanks for the clarifications.

**Comment by eiGelbGeek** [comment]
4 Days without a Crash..... now the Gateway crashed every 10 Minutes :-(

**Comment by rralf** [comment]
Does it also crash if OpenHAB's tradfri binding is inactive, could you please check that?

I'm very sure that OpenHAB causes - in some way - this issue, but nevertheless, the Gateway must not crash and stop functioning. Not saying that OpenHAB's implementation is buggy, it just causes the GW to crash because of its crappy firmware.

This darn issue now exists (at least for me) for more than three months, firmware upgrades or hardware exchanges didn't fix a single bit. I think it's time to contact IKEA developers and send them a detailed bug report. Do any of you happen to have their contact?

This is really starting to make me frustrated, three months of dancing the extraordinaire light-switch-dance in my living room is really enough. Otherwise next step is to switch to a Hue bridge. At least Tradfri lamps are said to be compatible...

**Comment by eiGelbGeek** [comment]
Perhaps via Twitter? https://twitter.com/IKEAUKSupport?lang=de

I will check later the Tradfri Gateway without Openhab.  

Now I connected the Bulbs Back to the HUE Bridge .... but there is the RGB Bulb Problem ;-)

**Comment by rralf** [comment]
So let's give it a try: https://twitter.com/r__ralf/status/957345063914364928
I wouldn't mind if others confirm this issue :-)

**Comment by kaikreuzer** [comment]
Wow, they were quick in answering!

**Comment by eiGelbGeek** [comment]
I think I could narrow down the problem a bit. I have to buy the day only a lamp to test .... if the gateway is registered without lamps to Openhab ... no crashes are produced. If the RGB lamp is registered, then the gateway crashes again.

It seems to be the Crappy RGB firmware!

If the RGB lamp is registered to a HUE gateway, then I can use the API and curl to set colors, but after about 1 hour the lamp will reset and turn white at 100% brightness (it seems the lamp crashes). That reinforces a crappy RGB Bulb Firmware.

**Comment by rralf** [comment]
A crappy firmware of a lamp must not lead to crashes of the gateway.

**Comment by eiGelbGeek** [comment]
But it seems so 😉

Perhaps there are too much Request from the Bulb.... that the Gateway crash.

**Comment by rralf** [comment]
Yes, no doubts. But then both firmwares are buggy.
