### ISSUE TITLE
Thing configuration descriptions not working

### ISSUE THREAD

**Issue by cdjackson** [eclipse/smarthome#5110]
ZWave configuration descriptions are no longer working - configuration from the internal ConfigProvider is ok, but configuration from the XML files is not provided. It seems that the conversion in the ThingConfigDescriptionProvider is not making the conversion from thing to thing-type.

Maybe it is related to https://github.com/eclipse/smarthome/pull/5021 as it's about the right timeframe for this having been introduced and it looks like the original provider was changed at this point to a new Alias interface (@sjka). From my quick look at this, it seems that the thing config provider is no longer being called (and possibly isn't registered from what I can see in the IDE).

Also see this [forum post](https://community.openhab.org/t/zwave-habmin-association-and-configuration/40094).

**Comment by kaikreuzer** [comment]
@cdjackson I tried to analyse this, but I failed to reproduce any issue due to the lack of hardware and the both issues https://github.com/openhab/org.openhab.binding.zwave/issues/832 and https://github.com/openhab/org.openhab.binding.zwave/issues/833.

> From my quick look at this, it seems that the thing config provider is no longer being called

Are you sure? At least in my IDE, it is called as expected, so I don't see an issue here.

Stepping through the code, I cannot figure out what the problem might be. Could you please step through the ConfigDescriptionRegistry and see why your descriptions are not returned?

**Comment by cdjackson** [comment]
What I saw when I looked at this was the ```ThingConfigDescriptionAliasProvider``` was not registered in the registry and wasn't being called. I initially put a break on the config provider in the ZWave binding, and then stepped into the registry and checked the Map/List of registered providers and I'm pretty sure it wasn't there. I also put a break in the ```case "thing":``` switch statement in the alias provider, and that wasn't called.

I will take another look at this later though.

**Comment by kaikreuzer** [comment]
It is absolutely ok that the alias provider isn't called, when you already provide a description for the "thing:..." uri. The alias is just a fall back, if nobody provides a description for a thing - it then makes sure that the description of the according thing type is returned.

**Comment by cdjackson** [comment]
Hmm - I'm not sure I understand what you mean. If I request a config description for ```thing:a.b.c```, then I expect that the alias provider is always called as it must provide the thing-type configuration - not only if no other provider responds to the thing config description. 

At least this is how it used to work. Thing configuration from the thing-type, and other providers, must be combined.

**Comment by cdjackson** [comment]
Ok, I checked the code and it seems that this is the problem then - the alias providers are now only called if no other information is found, and this means we now don't get the configuration from the xml provider (which is thing-type) if we have another provider.

**Comment by kaikreuzer** [comment]
Ok, this is indeed then a different behavior to before that we didn't notice.
From the method signature, imho it is expected by a ConfigDescriptionProvider to deliver a "full" description and not just parts of it. But I just discussed this with @sjka and we came to the conclusion that it would be indeed cumbersome for the bindings to get hold of the XML-defined info as well in order to provide a full description, so he will change the implementation to always consider the input from the aliased providers as well.
