### ISSUE TITLE
ESH-INF/thing/things.xml: Refer to bridge of other binding

### ISSUE THREAD

**Issue by davidgraeff** [eclipse/smarthome#5301]
Discussion: https://community.openhab.org/t/development-is-it-possible-in-a-thing-types-xml-for-a-thing-to-refer-to-bridges-defined-in-some-other-binding/42126

I have declared a thing like this:
```
<thing-type id="topic">
```
and I'd like this thing to be a child of a bridge of another binding:
```
<thing-type id="topic">
	<supported-bridge-type-refs>
            <bridge-type-ref id="otherBinding.someBridge" />
	</supported-bridge-type-refs>
</thing-type>
```

One way is to just have the same binding ID for all those bindings, but this restriction does not make sense if it really is an extensible parent/child relation.

## The bigger picture
* Imagine there is a binding to configure connections (let's say to configure Mqtt brokers).
* And another binding to configure things with channels that react to incoming data on a connection or provide the means for the user to send data to the connection (for instance to realize Mqtt topic messages).

The following picture visualize this, concentrate on the box called "MQTT Binding" and "Homie":

![](https://user-images.githubusercontent.com/3244965/29963082-e5eda0f4-8f05-11e7-9902-b97819541098.png)

The "MQTT Binding" would be the parent binding that configures the connections. The child binding "Homie" would need to use those connections. The "MQTT Binding" would establish a public interface with its bridge specification that child bindings can freely use.

## Binding dependencies
Of course this would introduce binding dependencies. This concept does not yet exist.

**Comment by kaikreuzer** [comment]
Well, I think @sjka already [gave the answer here](https://community.openhab.org/t/development-is-it-possible-in-a-thing-types-xml-for-a-thing-to-refer-to-bridges-defined-in-some-other-binding/42126/6?u=kai):

_"There already exist several such cases, e.g. zigbee, zwave, bluetooth, knx (planned)… So far, such cases were always considered to be one “binding”, i.e. they were all using the same binding ID, even if there are several different bundles which add additional, specialized thing types. I would consider doing the same for MQTT."_

The bindings do not reflect a certain "product support" but rather a "technology support". Just like we do not have a "Fibaro binding", but only a "Z-Wave binding".

Also note that certain products can potentially be supported through multiple bindings - e.g. an "Osram Lightify bulb" through a "Lightify binding" (using the Osram gateway), the "Hue binding" (using the Philips gateway) and the "Zigbee binding" (communicating directly). So effectively, your case is adding "Homie support through MQTT binding".

I am aware that this isn't ideal from a user point of view - nobody would have the idea to look for Homie support in the MQTT binding documentation. This is something that we should try to figure out on the documentation side, though.

FTR: The [Blukii support](https://github.com/eclipse/smarthome/tree/master/extensions/binding/org.eclipse.smarthome.binding.bluetooth.blukii) is the prototype for such a situation (which had already been [sketched out here (pretty similar to your diagram)](https://github.com/eclipse/smarthome/pull/4535#issuecomment-344178594) - it comes as an additional bundle for the Bluetooth binding and thus is an integral part of the Bluetooth binding, if the blukii bundle is installed. I am still looking for a good format for the README.md (i.e. its documentation) to make it integratable into the Bluetooth documentation. What is probably specifically helpful is to have that product-to-binding relation formally declared in some add-on meta-data as discussed in https://github.com/eclipse/smarthome/issues/3692.

**Comment by ssalonen** [comment]
Very good comment with much appreciated references. 

I would like to highlight that the blukii example shows how bundle/binding ("bluetooth.blukii") can refer to bridges in some other bundle ("bluetooth"). 

Interestingly, the bindingId in blukii bundle is set to "bluetooth". So does this mean that this setup works when there is no need to introduce bridges by blukii bundle? Otherwise one could not refer to those in the thing xml.

This is not a huge caveat since usually/often there are not many levels of bridges.

**Comment by kaikreuzer** [comment]
The important point to understand is that OSGi bundles are just a technical split - whether all code and XMLs for Bluetooth (incl. Blukii) are in a single bundle or they are spread over x bundles is just the same at runtime. This has been designed this way right from the start - so that any binding can be easily extended by more specific features by simply adding those features as separate bundles (while their Things use the same binding id).

**Comment by mrbig** [comment]
@kaikreuzer I've tried to implement the same solution you shown with blukii (code can be found [here](https://github.com/mrbig/openhab2-addons/tree/3216-binding-sunspec-modbus/addons/binding/org.openhab.binding.modbus.sunspec) )
It works with PaperUI but unfortunately it doesn't when I try to set up the bridge and thing in a .things file.

My things file looks like this:

```
Bridge modbus:tcp:se4000 [ ... ] {
    inverter-single-phase myinverter [ ... ]
}
```
The bridge is found and set up correctly, but the inverter wich is handled by the sunspec bundle isn't.

I believe it is caused by [GenericThingProvider.xtend](https://github.com/eclipse/smarthome/blob/5528ad5e460e2d8b6412bc34610530c0f2f06a28/bundles/model/org.eclipse.smarthome.model.thing/src/org/eclipse/smarthome/model/thing/internal/GenericThingProvider.xtend#L232): currently things under a bridge should be handled exactly by the same handler that handles the bridge.

Is there a workaround for this? Could this been solved by the blukii package?
