### ISSUE TITLE
[Classic Icon Set] "presence-on" icon is missing

### ISSUE THREAD

**Issue by Confectrician** [eclipse/smarthome#5416]
Hi,

This is a port from openhab/openhab-docs#660

It seems that somethings going wrong in https://github.com/eclipse/smarthome/blob/master/extensions/ui/iconset/org.eclipse.smarthome.ui.iconset.classic/README.sh and the html tags for the presence icon are generated wrong.

**Comment by sjka** [comment]
@ItIsFelix the mentioned script at least "works as designed". What would have been your expectation wrt to the alt property in case of the presence icon?

**Comment by ItIsFelix** [comment]
Hallo sjka, for the icon presence.png I see the alt-property "presence-off".
That looks strange to me.
See here: [OpenHab - Classic Icon Set](https://docs.openhab.org/addons/iconsets/classic/readme.html)

Thanks 
Felix

**Comment by triller-telekom** [comment]
@ItIsFelix: I have fixed that in the linked PR. Thank you for reporting it!

**Comment by sjka** [comment]
It generally list all of the available state variants (if any). Have a look [here](https://www.eclipse.org/smarthome/documentation/features/ui/iconset/classic/readme.html) at e.g. `battery`, `blinds`, `door`, `frontdoor`, `garagedoor`,... 

So, let me ask again: what did you _expect_ to see there? I.e. 

* Do you think it is surprising that the `alt="..."` property contains all the available state variants and you would have expected it to contain only the category name? This would however apply to all of the icons, not only to the `presence` in particular.
* Or are you rather missing a `presence-on` variant of the `presence` icon in particular? This indeed doesn't currently exist - that's why I mentioned that the script "works as designed".

**Comment by ItIsFelix** [comment]
Hello @sjka, 
you are right. An alt-property like "presence" is not correct.
I was expecting an alt-property "presence-off presence-on"

I didn't realize that there is no presence-off.png

**Comment by ItIsFelix** [comment]
In theory I agree with you. 
The alt attribute specifies an alternate text for an image, if the image cannot be displayed or if a user for some reason cannot view it.
But in this case, the alt attribute is used to show the different states of icons. (see the fire icon or switch icon)

Now we can say there is a icon named "presence" to display the presence (at home) and a icon named "presence-off" to display the absense.
A third icon is not needed because there are only two valid states.

Or we can do it like all other "switch" icons.
There is a base Item like the icon named "presence" to display a base icon (maybe it should look like the group icon), a "presence-on" to display the presence and a "presence-off" to display the absense.
