### ISSUE TITLE
Syntax to set thing parameters that are inside parameters group

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#5561]
I just discovered with the Z-Wave binding that is possible for a thing to define parameter groups and then define parameters in these groups.
The problem is that I have no idea what is the syntax to define such parameter in a things file. I searched in the documentation and this is defined nowhere.

The documentation should be enhanced with this concept of parameter groups with an explanation how to use it.

**Comment by lolodomo** [comment]
I tried `<group>:<parameter>=<value>` like for example `configuration:config_14_1=1` but it is an invalid syntax detected when the file is read.

**Comment by sjka** [comment]
Afaik the parameter groups are simply hints for the UIs in order to render certain parameters together. Therefore config description parameters simply reference their corresponding group name. 

That does not change the fact that the config parameters themselves are a flat list and can be addressed like that within the DSL. i.e. simply `config_14_1=1` would have been be correct in your above example.
