### ISSUE TITLE
GenericItem : trying to set state of Group with invalid state

### ISSUE THREAD

**Issue by kgoderis** [eclipse/smarthome#5565]
I have the following Group definition:

`Group:Switch:OR(ON,OFF) gValveStateHC2 (All)
`
Which is referenced in the Item definition of a bunch of Switch items. 

`gValveStateHC2 (Type=GroupItem, BaseType=SwitchItem, Members=5, State=OFF, Label=null, Category=null, Groups=[All])`

I also have a persistence strategy in place:

`gValveStateHC2* : strategy = everyChange, everyMinute, everyHour, everyDay
`

When starting up the runtime I see 

`2018-05-11 11:22:00.069 [ERROR] [pse.smarthome.core.items.GenericItem] - Tried to set invalid state 0 (DecimalType) on item gValveStateHC2 of type SwitchItem, ignoring it`

At this stage I can not (yet) pinpoint wether this is related to the persistence core bundle or something else, but I *think* that is has to due to the fact that the persistence module stores OnOffTypes as 0 / 1, and that during the restore this conversion is not done they other way around

**Comment by sjka** [comment]
The persistence services have just a signature of `PersistenceService.store(Item)`. The rest is up to the concrete persistence service implementation. 

As there is none within Eclipse SmartHome (yet), I think we can safely close this issue here. May I ask you to open a corresponding issue for the persistence service you are using (in the corresponding github project)?
