### ISSUE TITLE
Define README format for sub-bundles of bindings

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#5571]
We have more and more bindings that are split into several bundles, where there is a main bundle that holds the binding.xml and the README.md as specified [in the docs](https://www.eclipse.org/smarthome/documentation/development/bindings/docs.html) and additional bundles that bring (optional) support for specific devices/bridges.

Examples are the Bluetooth binding with the bluetooth.blukii bundle, the MQTT binding, Zigbee (currently in openHAB) etc.

We are so far missing a template/recommendation for the READMEs within those additional bundles, so that these can be easily integrated into a documentation website.
My suggestion would be to have a placeholder in the main README to identify the place, where the optional bundle content can be included. I can be left to the documentation site whether the content is included inline or as a link to a sub-page.

This issue is imho also closely related to https://github.com/eclipse/smarthome/pull/1853 as it also adds content/documentation for specific thing-types.

//cc @cdjackson & @ghys: FYI as you might have input on this topic as well.

**Comment by Tony-Hu** [comment]
> My suggestion would be to have a placeholder in the main README to identify the place

I do agree with the suggestion. It looks quite clear when I step into a binding folder. However, it's hard to know there are some bundles behind a binding(like Bluetooth binding and ZigBee binding you listed.) by just reading the documentation.
Since the bundles usually come up with specified devices/bridges, I believe a "Hardware configuration" part is commonly needed in a bundle's ``README.md``. For example, [TI2531 Coordinator configuration](https://docs.openhab.org/addons/bindings/zigbee/readme.html#ti2531-coordinator) in ZigBee binding.

**Comment by cdjackson** [comment]
A few thoughts from me...

The danger with this is we end up with a very big readme, so I would like to suggest a possibility where the binding author can insert small "snipits" into the main readme for each sub-binding. This would allow the main readme to contain short summaries of each binding - possibly broken into sections that make sense for the binding (eg hardware overview, channel overview...) that can be placed appropriately, and then link out to more detailed information relevant to the sub-binding.

I think this is pretty much in line with the suggestion from @kaikreuzer other than just "a placeholder" we effectively allow "a number of placeholders".

As an example, and using the example from @Tony-Hu, I personally don't think the TI coordinator config should really be in the docs as it is - and certainly we shouldn't have detailed hardware installation information for every dongle included into a main readme as this could make it a very large document.

What I think would work though is to include a short overview of the hardware, with a link to a more detailed description. Again using the TI2531 as an example, we might want a short hardware overview of the TI dongle in the main readme so that users get information on the hardware, but detailed information about how to flash the firmware should probably be in a separate page (it's fine when there's just a single dongle, but when there's 4 or 5, it makes it too long).

So, as a suggestion, something like

```
{{link file}}
```
to link to another file,

or 

```
{{include file}}
```
to include the data inline.

This is conceptually not too dissimilar to what we have done with the ZWave documentation where each thing is split into a separate file.

**Comment by kaikreuzer** [comment]
Sounds quite straight-forward, but I have one concern, though (which mainly applies to stage c):
Our [current archetype](https://github.com/eclipse/smarthome/blob/master/tools/archetype/binding/src/main/resources/archetype-resources/README.md) splits the information about a single thing into separate sections: list of the defined type, which ones are discovered, their configuration, their channels and a full example to see everything interacting.

I feel that if we want to come to stage c (and also to be able to generate this content from the thing xmls), we will have to think about a general restructuring of the README, so that one Thing is described fully in a single section (incl. its configuration, channels, etc.).

If we now decide that for the start a or b is enough, we can postpone such a decision. But it would mean that any sub-readme that is written now will have to be re-written later on.

**Comment by sjka** [comment]
Sure, we might think as well about restructuring the readme files. 

Nevertheless, having split up the information across several sections is exactly the purpose of "Stage C": You could as well have multiple snippets per extension (e.g. SNIPPET_DISCOVERY.md, SNIPPET_THING_TYPES.md, SNIPPET_CHANNELS.md) and include them accordingly. 

I second @cdjackson though, this doesn't make sense for huge bindings, but might be feasible for bindings with very few, small extensions (e.g. where bridges are added by extensions).

Overall, stuff like that might get hard to maintain pretty quickly. On the other hand it is hard to keep an overview either way in huge bindings. That is what we will need #1853 for.

**Comment by kaikreuzer** [comment]
So what's your recommendation as a first step? Go for stage a or b and leave the content of such sub-readmes completely open/unspecified?

**Comment by sjka** [comment]
Yes, my approach would be like that. 

At this point I don't see a documentation structure which would work perfectly well across all extensible bindings. However, I think it would make sense to experiment a little on a concrete binding we have already and see how it feels. Maybe in that way we at least can derive a recommendation for future extensible bindings. I suggest to start with the bluetooth binding as it is within the same repository and therefore can be adapted forth and back easily if needed.

As a first step I will try to adapt our docu generation here accordingly. Let's so how that goes...

**Comment by sjka** [comment]
As with #5611 we currently have a solution that fits our (current) needs, let's close this one and create a new issue once there are new requirements.
