### ISSUE TITLE
[REST API] rest/persistence/items returns duplicated entries for SwitchItems

### ISSUE THREAD

**Issue by openhab-5iver** [eclipse/smarthome#5628]
OH 2.3.0 snapshot 1288 (ESH 0.10.0.201805241348)

When making the call...

http://<ohserver>:8080/rest/persistence/items/Outlet6

... the following is returned...

```
{
  "name": "Outlet6",
  "datapoints": "4",
  "data": [
    {
      "time": 1527153550000,
      "state": "OFF"
    },
    {
      "time": 1527153550000,
      "state": "OFF"
    },
    {
      "time": 1527191908000,
      "state": "ON"
    },
    {
      "time": 1527191908000,
      "state": "ON"
    },
    {
      "time": 1527199491000,
      "state": "OFF"
    },
    {
      "time": 1527199491000,
      "state": "OFF"
    },
    {
      "time": 1527213052000,
      "state": "ON"
    },
    {
      "time": 1527213052000,
      "state": "ON"
    }
  ]
}
```
The datapoints are correct, but each entry is duplicated. The actual data from mariadb is not duplicated...

```
Time | Value
2018-05-24 21:50:52 | ON
2018-05-24 18:04:51 | OFF
2018-05-24 15:58:28 | ON
2018-05-24 05:19:10 | OFF
```
This is only occurring for SwitchItems. Persistence data for other types of items is not duplicated.

**Comment by triller-telekom** [comment]
For `SwitchItem`s and `ContactItem`s this is actually intended, see:

https://github.com/eclipse/smarthome/blob/45a7ee5f7b91dbb62b846a605b9e81e6fa8fc8d3/bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/internal/persistence/PersistenceResource.java#L315-L319

But this logic was wrong in the way that it repeated the previous state with the previous time instead of the previous state with the current time. I have created PR #5630 to fix this. This PR also contains a test case to not break it again next time :)

**Comment by openhab-5iver** [comment]
Running OH snapshot 1298 w/ ESH 0.10.0.201806080647, the issue is resolved. Thank you!

**Comment by kaikreuzer** [comment]
Excellent, thanks for your feedback!

**Comment by openhab-5iver** [comment]
It allowed me to finally get this posted... https://community.openhab.org/t/persistenceviewer/46407.
