### ISSUE TITLE
JSON Storage must not use colons in file name

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#5687]
The files produced by the JSON storage have illegal names for Windows, see https://community.openhab.org/t/openhab-storage-api-generate-filenames-with-colons-which-are-invalid-on-windows/46028:

```
07:18:50.454 [ERROR] [ome.storage.json.internal.JsonStorage] - Error writing JsonDB to D:\OpenHABRoot\OpenHAB2\userdata\jsondb\amazonechocontrol:account:account1.json. Cause D:\OpenHABRoot\OpenHAB2\userdata\jsondb\amazonechocontrol:account:account1.json (Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch).
07:18:50.458 [ERROR] [ome.storage.json.internal.JsonStorage] - Error writing JsonDB to D:\OpenHABRoot\OpenHAB2\userdata\jsondb\backup\1528175930458–amazonechocontrol:account:account1.json. Cause D:\OpenHABRoot\OpenHAB2\userdata\jsondb\backup\1528175930458–amazonechocontrol:account:account1.json (Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch).
```

**Comment by triller-telekom** [comment]
This seems to be a little bit more tricky than thought on a first place...

If I change the `JsonStorageService` to replace unwanted characters with for example "_", this service will always do that and look for files that have the "_" instead of ":" for example. This is no problem for new installations which do not yet have any jsondb storage files on the file-system.

On systems with existing jsondb files on the file-system, those files will not be found anymore.

Since the JSONDBStorgae is used throughout the framework I rather decided to fix this issue just in the biding, because using the ThingUID as a storage name is apparently not a good idea, at least on windows systems. This way I only break it for users of the amazon echo control binding, but not for everyone else.

See my PR in: https://github.com/openhab/openhab2-addons/pull/3634

**Comment by J-N-K** [comment]
Maybe we could add an „auto-upgrade“? 

1) Look for new file, if exists use it
2) Look for old file, if exists rename and use  it
3) Create new file

This could be removed in a later version.

**Comment by maggu2810** [comment]
Hm, a developer does not need to know the implementation of the used storage service.
There is no limitation in the storage name (AFAIK) and if one storage implementation decides to use the given name as a file it is up to that implementation to grant that all names are working.
Why should the binding developer not use a "colon" if this works for another storage limitation and regardless what a implementation does, if the API does not limit the name itself?

The JSON storage could check if a file using exactly the given name exists and use that file if it is present already.
If the file is not present, another logic could be used.

E.g. there could be a mapping file that translate between storage name and a generated UID.
As a consumer of the storage implementation I expect that
"a:b", "ab", "a#b", "a_b", "a-b", "a b", ... are different storages.
