### ISSUE TITLE
Sprintf choking on UoM values

### ISSUE THREAD

**Issue by 9037568** [eclipse/smarthome#5773]
When attempting to use a UoM value in a widget (eg. Number:Temperature), statements that use sprintf fail. Getting the raw value still works.

For example, if the item `tomTempL` is an Item of type Number:Temperature, the following statement produces a valid value (e.g. `79`):

````
          <h2 style="margin-bottom:1em;">{{itemValue('tomTempL')}}</h2>
````

while this statement fails, producing the value `{{'%.1f' | sprintf: itemValue('tomTempL')}}`:

````
          <h2 style="margin-bottom:1em;">{{'%.1f' | sprintf: itemValue('tomTempL')}}</h2>
````

**Comment by htreu** [comment]
@9037568 please forgive my ignorance, but what code are you working on? It looks a loot like angularjs but I can not find a specific code snippet in our codebase.

In case `itemValue` returns the item state this will clearly fail, since `20 °C` can not be printed by the pattern `%.1f`. We encounter the same issue in the backend when using String#format on QuantityTypes.

The first option which comes to my mind is to define your own filter which is able to deal worth UoM values. Splitting scalar and unit before doing the formatting should work.

**Comment by 9037568** [comment]
This is for the [habpanel ui](https://github.com/openhab/org.openhab.ui.habpanel), which I had thought was an ESH feature. My mistake.
