### ISSUE TITLE
support - (dash) in item names

### ISSUE THREAD

**Issue by andred** [eclipse/smarthome#5818]
Looking at the git history, there doesn't seem to be any indication as to why - (dashes) are not allowed in item names. Commit a27737719af6617df2b659c91a16e05e910355b0 added the restriction (claiming refactoring), without any further explanation.

Before opening a PR, can somebody clarify this please? Do you foresee problems if support was to be added?

**Comment by kaikreuzer** [comment]
Afair, they were never allowed since openHAB 0.1 (only the active check was added later).
Dashes clearly would cause all rules&scripts to break as they would be mistaken with "minus".
As all consumers (like UIs etc.) are expecting the current definitions, I doubt that there is any reason why we should introduce such a breaking change.
