### ISSUE TITLE
Early calls to updateProperties() throws warnings in AbstractManagerProvider.update()

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#588]
migrated from Bugzilla [#466778](https://bugs.eclipse.org/bugs/show_bug.cgi?id=466778)
status NEW severity *normal* in component *Core* for *---*
Reported in version *unspecified* on platform *PC*
Assigned to: Project Inbox

On 2015-05-07 16:13:16 -0400, karel goderis wrote:

> When creating a new Thing, and ThingHandler, code like
> 
> Map<String, String> properties = editProperties();
> properties.put(selector.getChannelID(),
> entry.getValue().getAsString());
> updateProperties(properties);
> 
> throws a lot of these in the logs
> 
> 2015-05-07 22:08:43 [WARN ] [.c.c.r.AbstractManagedProvider:138  ] - Could not update element with key tesla:models:v12killer in ManagedThingProvider, because it does not exists.
> 
> The call originates from the this.callback.thingUpdated(thing) here below
> 
>   protected void updateProperties(Map<String, String> properties) {
>         boolean propertiesUpdated = false;
>         for (Entry<String, String> property : properties.entrySet()) {
>             String propertyName = property.getKey();
>             String propertyValue = property.getValue();
>             String existingPropertyValue = thing.getProperties().get(propertyName);
>             if (existingPropertyValue == null || !existingPropertyValue.equals(propertyValue)) {
>                 this.thing.setProperty(propertyName, propertyValue);
>                 propertiesUpdated = true;
>             }
>         }
>         if (propertiesUpdated) {
>             synchronized (this) {
>                 if (this.callback != null) {
>                     this.callback.thingUpdated(thing);
>                 } else {
>                     throw new IllegalStateException("Could not update properties, because callback is missing");
>                 }
>             }
>         }
>     }
> 
> which contains
> 
>        public void thingUpdated(Thing thing) {
>             thingUpdatedLock.add(thing.getUID());
>             thingRegistry.update(thing);
>             thingUpdatedLock.remove(thing.getUID());
>         }
> 
> Is there a timing problem as to the Thing being created but not yet being added to the thingRegistry?

On 2015-05-07 18:20:58 -0400, Dennis Nobel wrote:

> How do you add the thing? From the DSL or UI?

On 2015-05-08 03:18:44 -0400, karel goderis wrote:

> The thing is created from the DSL.
> The code is called upon in the ThingHandler after initialisation, but in a thread that is spawned in initialize()

On 2015-05-08 03:44:53 -0400, Dennis Nobel wrote:

> Actually the whole concept does not work with the DSL files. The ThingManager tries to save the updated properties via the ManagedThingProvider. But if the things are configured through the DSL, there is no entry in the database. This does not only applies for properties, but also for configuration updates.
> 
> As long as we do not have a possibility to write back changes into the DSL, the only option I see is to leave out the serialization in DSL case and remove the warn logging.

On 2015-05-08 03:51:22 -0400, karel goderis wrote:

> Ok - from the code I can see that updating configurations and properties is still ok and allowed. Per discussion with Kai, I am re-organising the Tesla binding by moving a lot of channels out of the DSL and store the corresponding values as Properties. 
> 
> I understand that serialisation is not possible in the DSL case, but is there a need then for to have a thingUpdated() call? I can imagine that DSL-orginated Things also want to react upon changed in their Configuration and Properties?
> 
> K

On 2015-05-08 05:36:03 -0400, Dennis Nobel wrote:

> We are mixing up two different cases
> 
> 1) thingUpdated() is called by the framework to inform the binding a thing was updated
> 2) updateThing() is called by a binding to to inform the binding a thing was updated
> 
> If you want to write properties from the binding, you call 2) updateThing (implicitly via updateProperty). But it seems that this does not work for things configured through the DSL.
> 
> If you change the configuration of a thing in the DSL at runtime, 1) thingUpdated will be called in your binding. So this works.

On 2015-05-09 05:29:09 -0400, karel goderis wrote:

> Ok. Will thingUpdated() also be called when the Properties change? (in other words, do we assume they can change over time as well?)
> 
> My assumption is that Property changes can be triggered in different place, e.g. the ThingHandler, or the Thing's BridgeHandler.
> 
> Today we do not really care what part of a Configuration has changed, since the base assumption here is that a dispose() and initiliaze() will happen anyways, and most probably, the complete ThingHandler will be reconditioned.
> 
> Now, with changes in Properties it would be handy to know which Property exactly has changed with the thingUpdated() call. This functionality can be part of the ThingHandler on a case by case need, or could be refactored in a sense that we would get a propertyUpdated(String property,String newValue) method in the BaseThingHandler?
> 
> K

**Comment by kaikreuzer** [comment]
@kgoderis, how shall we proceed with this issue?
From what I read it seems that the issue comes from the fact that you cannot update properties of a DSL defined things. There isn't really any easy solution around this. The simplest way around it would be to catch the exception in the framework and do a debug logging instead - to simply care for the situation that a handler tries to edit properties on a read-only (because DSL-defined) Thing.

**Comment by kgoderis** [comment]
@kaikreuzer @dnobel Just coming back to this old issue, I have noticed that (with the latest ESH API) it is not possible to call updateProperties() from within initialize() in a ThingHandler

I have  a use case (and this must be a frequent one) that upon/during initialisation of the ThingHandler, a connection is made to the remote hardware, and some device specific data is read, and converted into properties for the Thing (e.g. device_name, serial_number and alike).

Knowing the limitation of updating DSL-originated things, this throws an exception like this:

2016-04-09 16:46:15.990 [ERROR] [.c.thing.internal.ThingManager:656  ] - Exception occured while initializing handler of thing 'helios:ipvario213:practice': java.lang.IllegalStateException: Could not update thing helios:ipvario213:practice. Most likely because it is read-only.java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Could not update thing helios:ipvario213:practice. Most likely because it is read-only. 

I still think that - even if write-back is not supported - properties should be able to be updated, even if their state is not persisted afterwards.

Just for my understanding, is the architecture calling for a limitation of what you can do in the initiliaze()? e.g. postpone connecting to a device in for example a polling Runnable, and limit the initliaze() to setting up data structures?

**Comment by sjka** [comment]
Yes, this is a frequent use-case, but normally this either happens during discovery or for dynamic data it's modeled as a channel (and in that sense I'd even consider a device name as dynamic, as long as it can change over time).

I fully understand your wish for transient properties. However, I think we had that discussion in several places already (i.e. dynamic channels, configuration,...). Properties are simply part of the Thing, and that cannot be written to the DSLs (currently). And if we would allow transient changes, we'd run into all kind of weird situations wrt user experience after restart of the provider (or any of its dependencies), depending on if a Thing is available at that point in time or not.

**Comment by kgoderis** [comment]
@kaikreuzer Just a polite ping, given that in the discussions on dynamic properties and alike, we always come to the conclusion that DSL files need to have write-back capabilities. Is this is something that is still on the "map" somewhere? if not, then all concerned would be aware of the fact that an alternative solution (in casu, defining different Thing types, or a catch-all Thing type in their binding) is to be used

**Comment by kaikreuzer** [comment]
> we always come to the conclusion that DSL files need to have write-back capabilities.

I am not sure if this is the conclusion for this issue. I would rather support that we treat property updates as transient, so that it is possible to change them during runtime through the binding, but without persisting it (at least if defined in a DSL). I discussed this with @sjka last week again and think that this should be a workable solution (and it might be already on @sjka's todo stack ;-))

**Comment by lolodomo** [comment]
I get these warnings with the hue binding when starting openHAB 2 beta 3 and having hue things defined in a file..

**Comment by afuechsel** [comment]
I analyzed this a bit. `updateProperties()` actually updates the properties at least in the hue binding, but code is called more than once and the update is only beeing done because of the special implementation in the hue binding. Explanation: 

E.g. the hue binding sets 3 properties in its `HueLightHandler#initialize()` method: 

```` 
updateProperty(Thing.PROPERTY_MODEL_ID, modelId);
updateProperty(Thing.PROPERTY_FIRMWARE_VERSION, fullLight.getSoftwareVersion());
//...
updateProperty(Thing.PROPERTY_VENDOR, vendor);
```` 

What happens, is this: 

1. updateProperty calls `AbstractManagedProvider#update()` that logs a warning "Could not update element with key {} in {}, because it does not exists."
1. `ThingManager#thingUpdated()` is called. It throws an IllegalStateException. 
1. the initialize-Method of the HueLighthandler is left immediately due to this exception
1. This Exception is ccaught in the HueBridgehandler's polling loop
1. Now *only because this is a polling loop* the initialize() method of the HueLightHandler is called *again* trying to set the properties *again* 
1. the first call updateProperty now woul *not* again throw an exception, due to the check in BasicThingHandler, whether the value has already been set (which has been in the previous call) 
1. the second updateProperty will now be executed, logging again a warning, throwing again an exception and bailing out
1. pollingLoop continues...

Eventually, after several calls of the same code, all properties would be set, several exceptions would have been thrown, several log messages would have been shown... Not an ideal case. 

Bindings without such a loop would bail out at the first exception and no property would be set. 

### Suggestion

* Remove the IllegalStateException being thrown for read-only properties, replacing it with a debug logging
* change the warning logging to a debug as well

**Comment by kaikreuzer** [comment]
I would ask a more general question: If the method updateProperties() is only called by bindings themselves (I at least could not find any other caller) and when bindings must not assume that properties are persistable: Should they simply assume that a call to this method NEVER persists the changes, but only sets them in memory until the next restart?
All we would have to do is to remove the `this.callback.thingUpdated(thing);` call in the BaseThingHandler.

**Comment by afuechsel** [comment]
I would agree to @kaikreuzer and create a PR for this change.

**Comment by maggu2810** [comment]
> so that it is possible to change them during runtime through the binding, but without persisting it (at least if defined in a DSL)

The merge request has been accepted very fast.

Now I have a question:
I have used the properties in the thing handler to persist stuff (one time assigned addresses -- non-configurable ones). So, I assume this does not work anymore. Correct?

Should a binding always store its information about things in a custom persistent storage with its own cleanup methods etc.?

**Comment by kaikreuzer** [comment]
> The merge request has been accepted very fast.

Well, the conclusion of this change was already there 26 days ago (https://github.com/eclipse/smarthome/issues/588#issuecomment-220767420).

> I have used the properties in the thing handler to persist stuff 

As discussed in this issue, that meant that your binding made inherent assumptions that the thing existed in the managed provider - imho not a valid assumption.

> So, I assume this does not work anymore. Correct?

Correct. While as an easy workaround you can simply do a call to updateThing(getThing()) - but this does not make the assumption any better ;-)

> Should a binding always store its information about things in a custom persistent storage with its own cleanup methods etc.?

In general yes. But we can certainly discuss whether this is a feature that should be provided by the framework - feel free to open a new issue for that.

**Comment by maggu2810** [comment]
Okay, I will store the persistent properties in a custom storage for my bindings.
No prob, but that the change does impact all (not only DSL ones) has been realized by me by the PR.

To be sure to understand the impact:
Properties are now transient for all things, because they are not stored persistent for the DSL ones.
What about configuration?
Can a configuration persisted for the things that has been created using the DSL (you see, I do not use the DSL the last month)?
If not, is it a wrong assumption that a configuration will be persistent for other things?

**Comment by kaikreuzer** [comment]
> What about configuration?

Same problem. Bindings are not supposed to change the configuration by themselves, such changes should originate from a user.

Before you further ask: Dynamic channels are also not possible for DSL defined Things.
I think we should sooner or later finish the discussion on https://www.eclipse.org/forums/index.php/t/1072808/ and come to a conclusion...

**Comment by kgoderis** [comment]
> Before you further ask: Dynamic channels are also not possible for DSL defined Things.
> I think we should sooner or later finish the discussion on https://www.eclipse.org/forums/index.php/t/1072808/ and come to a conclusion...

I am again late to the discussion (/me slap!), but I am ok with the initial change. To me, these transient properties are/should simply stored in the remote devices themselves. As such, they should imo not be persisted by the framework, since we read them out every time the runtime starts. 

However, on the dynamic channels: I think the same principle should apply, e.g. it should be possible to dynamically define channels on Things without these channel definitions being persisted, because the creation of those channels is triggered/dependent on the data that is read from the remote device. These channels can be "built up" every time the runtime starts (or, the ThingHandler(re) initializing)
For me the big benefit is that you do not have to create different thingTypes for all possible hardware/software variations of a device. For example, the Helios VideoPhone comes in many variations, some with/without a keyboard, with/without a card reader, with/without Wiegand door locks and so forth. In function of the hardware detected, channels to control those hardware parts can be added dynamically.


just my 2 cents

**Comment by maggu2810** [comment]
The discovery service changes the IP configuration of the things.
So, I assume this is a corner case and normally every configuration should be changed by the user.

There are devices that do not store stuff itself but leave it to the application to store it.
But if the properties are not the correct place I will use another one.

Perhaps @kaikreuzer you can give me some tips to do it in the correct way.

A device supports multiple addresses. The thing handler needs to read the list of supported ones, choose one and have to use same on at this time. If there is no such address in the properties, I stored the chosen one, if there is already one I used that one. So, I will change that to store the address in another place and fill the information all the time on startup to the transient property. That's easy. It should be available in the properties, so a user see that address.
I don't expect any problem here (at least after I implemented the usage of the storage backend).

Some devices gives me the option to read the configuration from the device (so the thing handler already exists and handles the device).
I would like to fill the configuration, so the user can see the current values and change them.
How should this be done if a binding should not change the configuration itself?

Another point is the user can configure the device address in the configuration. There is one configuration value that indicated "auto-detected by the binding". I can leave this "auto-detect (one time)" in the configuration and check if there has been already one detected (using the custom storage). But I think it would be better to change the configuration from auto-detect to the detected one. As this is already done by the jUPnP discovery, do you see any problem here?

**Comment by kaikreuzer** [comment]
> The discovery service changes the IP configuration of the things.
> So, I assume this is a corner case and normally every configuration should be changed by the user.

Yes, this is a corner case, and this one can be sure that the Thing is editable, because it was added through discovery and not manually added.

> I would like to fill the configuration, so the user can see the current values and change them.

I think we still have a general issue with the concepts, because the original intention of the configuration is the configuration of the handler, not of the remote device. See e.g. the IP address config parameter of Philips hue: This is the IP address to tell the handler how to reach the device, but it is not the IP address that the hue bridge is supposed to use (and which would be set in the bridge if the user changes the parameter).
ESH historically expects the remote systems to be up and running (and readily configured) already and is not designed to do remote administration of them. I see that this is more and more needed (and talking about "thing configuration" already misleads people to think that this is what it's for...).
A heavy user of configurations is @cdjackson in ZWave, where they are also treated as device (and not handler) configurations. Chris, how do you actually deal with the fact that DSL defined Things are not modifiable? Is this something that the ZWave binding does not support at all?

**Comment by maggu2810** [comment]
IIRC the properties and the configuration has been stored in the same collection in the thing. There is some logic to split the configuration and the properties entries by their name etc. The properties are now transient, wouldn't be it a good time to split the internal holding of the configuration and of the properties, so different collections are used that can't ever be mixed up?

**Comment by kaikreuzer** [comment]
> IIRC

I think you don't ;-)
The Thing already has separate sets for its configuration and property values.

**Comment by cdjackson** [comment]
> Chris, how do you actually deal with the fact that DSL defined Things are not modifiable? Is this something that the ZWave binding does not support at all?

Sorry - I missed this comment...

Yes - this causes problems - both for configuration, and also for properties since I am also storing some device information in the properties to allow it to be used in the UI. Maybe this is also not intended, but currently there are two options - properties, or some sort of read-only configuration (which doesn't seem right for low level device information).

For configuration data, currently things defined in the DSL are not able to be configured. Until recently I never realised that the thing configuration was not intended to support device configuration - I think this is a major flaw since people want to be able to configure devices - they don't want to have to revert to a separate software to configure their system as is stated above.  I also think that there's a mismatch in the concepts since we also have the ConfigStatusDescriptions with status such as ```Pending``` which makes no sense at all if it is only meant to be configuring the thing handler.

As I commented in the OH2 forum, maybe a way to work around this might be to add an attribute in the config description that indicates that the information is ```volatile``` and it could either not be stored in the ESH config descriptions at all (eg the system could possibly call a callback to get the status) or, this ```volatile``` flag could be used to indicate to the system that it should store the config in the storage system.

**Comment by kgoderis** [comment]
@kaikreuzer I also was not aware that Configuration was intended to configure the handler only and not the devices. Now I understand your answers to all my previous questions on the subject. With Things representing physical objects, and transitioning from openhab1, this indeed is not a very easy concept to naturally assume

Still, as chris, I do think there are many use cases where you have to read out some configuration info from the device and store it to parameterise the Handler, to display it in the UI and so forth, apart from what can be done through a third-party configuration tool, a web admin ui of the device itself etcetera

We need a solution for this

K

**Comment by afuechsel** [comment]
@kgoderis, I understand very well your wish to have a concept for configuring the devices but how far would you go? I mean, devices could have many configuration parameters, some of them might even be depending on each other. Which one would you like to configure? Each of it? Only a part of it? You may very easily end up in a configuration hell. 

The device configuration API often is much more complex and subject to frequent changes for each firmware release of the very same device (e.g. for D-Link cameras...) This would require even more often code changes in bindings, supporting backward compatibility for older firmwares etc. 

On the other side, if we stick to the original ESH concept, where the device is up and running we have a natural spilt: configuration is done with the tools the device provides (like you connect a router to a network and configure the router before using it with its own config UI) and usage of the device is done within ESH. 

I agree, that it could be useful to configure devices but we all must be aware of effort required to do so. Just my 5 cents.

**Comment by kgoderis** [comment]
It will always be a subset of configurations parameters that would be configured, obviously, and it is to the binding to deal with the complexity so that is not a big issue. I think nobody expects tone able to fully configure a device from ESH/oh

On the other hand for example the Helios binding (ip door phone ) I have one thing type and 1 handler implementation that covers the common denominator hardware. But one can install optional hardware plugins in the device like a card reader, wiegand relays, push buttons. Well, I would like to be able to read out the hardware config, store that info, and re use it in the binding, change what is displayed in the UI, dynamically add channels in function of the hardware. That information can be transient, does not have to be persisted, because it is read out every time the handler is initialised. As it stands I would have to define a thing type for every possible hardware combination. That is ridiculous in itself.

**Comment by kaikreuzer** [comment]
>  I also was not aware that Configuration was intended to configure the handler only

@kgoderis As a long time openHAB 1 user, you should have been aware of that - to make it even more obvious, I have tried to document [how "Things" came up in the first place](http://docs.openhab.org/tutorials/migration#understanding-things).

> As it stands I would have to define a thing type for every possible hardware combination.

Why this? You can define your Thing dynamically without requiring a thing type. Ok right now this won't work with DSL defined things; but would it be all fine if we allowed in-memory changes to the channels without persisting them, just as we did for the properties? The problem with that might be that we also would not persist any potential configuration of such channels; so this would need to be recontructed by the binding as well on the next start. If this is fine for everyone, I would suggest to open a new issue to do something similar like https://github.com/eclipse/smarthome/issues/1682 for the updateThing() call within the handler.

> We need a solution for this [device configuration requirements]

I would suggest to continue the discussion on [this thread in the forum](https://www.eclipse.org/forums/index.php?t=msg&th=1079343&goto=1739444&#msg_1739444).
