### ISSUE TITLE
[homematic] Allow to configure a factory reset on thing deletion

### ISSUE THREAD

**Issue by FStolte** [eclipse/smarthome#5997]
### Summary
New feature: It should be possible to configure whether devices are factory reset when the corresponding things are deleted.

### Context
The homematic binding currently has a configuration parameter called `unpairOnDeletion`. It allows to configure whether devices should be unpaired from the gateway when the corresponding thing is deleted. Homematic gateways offer the option to factory reset a device when unpairing it. This option currently defaults to `false` and cannot be configured by the user.

### Open Question
There are two possibilities to implement the new configuration.
* Provide a new boolean configuration parameter to activate/deactivate factory reset on thing deletion
* Refactor the existing configuration parameter to provide three choices: no unpairing on thing deletion, unpairing without factory reset  on thing deletion and unpairing with factory reset  on thing deletion.

The advantage of the first option is that it can be easily implemented and that it is not API breaking. Refactoring the `unpairOnDeletion` configuration parameter would introduce incompatibilities with existing configurations that specify this parameter.
On the other hand, having two separate parameters allows to specify a misleading combination. Since a factory reset always implies unpairing, it does not make sense to activate a factory reset on thing deletion while the unpairing on thing deletion is deactivated. But it would be unclear what behavior should be expected when this combination is specified. Having only one parameter would let us exclude this combination by design.

What solution would be preferred by the ESH community? I favor the refactoring, but would be fine with implementing either.

**Comment by triller-telekom** [comment]
Given the fact that the homematic binding exists since quite a while and a lot of people are using it, it would not be nice to break the API. Since this parameter is also a bridge parameter, ALL users would be affected which use the binding.

However the good thing is that the `unpairOnDeletion` is an advanced parameter and set to `false` as a default. So most people will have this setup.

If you would introduce the new parameter `factoryResetOnDeletion` you could mention there that this parameter always wins. It should be set to advanced as well and also have a `false` as default. This way users will hopefully read the description before enabling this advanced parameter. Maybe we should also mention that the `unpairOnDeletion` will be overruled by `factoryResetOnDeletion=true`.

WDYT?

**Comment by FStolte** [comment]
I was actually thinking of having unpairOnDeletion=false overrule factoryResetOnDeletion, but your suggestion looks like a better option which should lead to less misunderstandings.

I agree that this would then probably be the most satisfying solution for all users of the binding.

**Comment by triller-telekom** [comment]
@FStolte Can you close this issue please? And next time just mention "fixes #number" in your pr so the issue will be auto closed once the pr is merged, Thanks.
