### ISSUE TITLE
Unmanaged items created after approving inbox items

### ISSUE THREAD

**Issue by dushanlk** [eclipse/smarthome#6001]
I have a ESH integrated service and my own binding. The ESH framework creates un-managed items right after approving an box item. What was the idea behind making them un-managed. Is there a nice way to force to create managed items on inbox item approval? Or do I have to listen to `ItemAddedEvent` and do some dirty work to make managed?

**Comment by triller-telekom** [comment]
I guess you are referring to your your forum post https://www.eclipse.org/forums/index.php?t=msg&th=1094505&goto=1793182&#msg_1793182 right?

In ESH there exists the so called "simple mode" which can be enabled/disabled for example in the settings of Paper UI. By default, however, it is enabled.

What this simple mode does is, it creates a "placeholder" `Item` for a newly created link that would otherwise point to no where. This is done by the `ChannelItemProvider`. I said "placeholder" `Item`, because this provider also withdraws this `Item` if the user creates a "real" `Item` and links it to that channel.

I do not know your use-case, but you probably want to disable the simple-mode and create your `Item`s by yourself which you can also edit afterwards.

**Comment by kaikreuzer** [comment]
If there are any further questions open, I'd suggest to do any follow up discussion in the linked forum post.
