### ISSUE TITLE
Custom dynamic icons with spaces not working anymore

### ISSUE THREAD

**Issue by michaeljoos72** [eclipse/smarthome#6071]
Hi

From WeatherUnderground-Binding we get a state like “Regen” or “Regen möglich”. Long time ago I have added custom icons for every condition and I’m sure that it worked! For above 2 states I have two custom icons in \icons\classic-folder:

weather-regen.png
weather-regen möglich.png

But now the conditions from wunderground that have a space bring up the default icon.

2.4.0 Snapshot 1328

Thanks & BR
Michael

https://community.openhab.org/t/dynamic-custom-icons-with-a-space-in-state/48135

**Comment by kaikreuzer** [comment]
You might want to enable debug logging of `org.eclipse.smarthome.ui`.
If I am not mistaken, you should see log messages for icon names the system tries to look for before using the default icon as a fallback.

**Comment by michaeljoos72** [comment]
I did enable logging last night and I was wrong with the assumption that it takes the default icon. But it does not differ between "Regen" and "Regen möglich".

Icons I have:
weather-regen.png
weather-regen möglich.png

Weather conditions:
Regen --> it takes "weather-regen.png" (OK)
Regen möglich --> it takes "weather-regen.png" (Not OK)

This is unfortunately not visible in the log as the system does find an icon, but not the one with the space. Long time ago when I prepared these "space-icons" I'm sure it worked.

**Comment by lolodomo** [comment]
I will debug this issue.
Is it the same whatever the UI (basicUI, classicUI, ...) ?

**Comment by michaeljoos72** [comment]
yes, it's the same for basicUI and classicUI

**Comment by kaikreuzer** [comment]
I now remember that this was changed by some PR of @htreu. The assumption in that PR was that no spaces should occur in states and thus the icon name is only determined from the content up to the first space. Afair, this was due to UoM introduction, because otherwise the icons didn't work for number items anymore.

@htreu might be the best person to point at the code in question and maybe to come up with some alternative treatment, so that the old behavior is still supported. I am not a big friend of spaces in filenames, though, so maybe string item values could be pre-processed in some way, e.g. by simply removing the spaces...

**Comment by htreu** [comment]
@kaikreuzer's memory is correct, we introduced this change with the introduction of Units of Measurement (UoM). With UoM all NumberItem states have the unit attached and separated by space. So a look up for category "Temperature"  and state "20 °C" would fail to find the existing "temperature-20.png".
A workaround would be to try to parse the remaining part (here "20") to Number and otherwise use the full state as usual.

I will propose a fix.
