### ISSUE TITLE
Thing file parser cannot handle multiple value parameters

### ISSUE THREAD

**Issue by fruggy83** [eclipse/smarthome#6146]
When I understand line 68 of file thing.xtext correctly, it is not possible to define a config parameter in a thing file with multiple values. I would expect something like 

key=ID '=' value=ValueType (',' value+=ValueType)*

However I am not familiar with this grammer.

Best regards
Daniel

**Comment by htreu** [comment]
Hi @fruggy83,

your observation is correct. Multiple values are currently not supported from the Thing DSL. Also your suggested patch looks okay, jus a little correction:

```
key=ID '=' value+=ValueType (',' value+=ValueType)*
```

Since `value` is then treated as a list all the time additional modifications might be necessary. You are welcome issuing a PR.
