### ISSUE TITLE
Enhancement: Item-type Number and INCREASE/DECREASE commands

### ISSUE THREAD

**Issue by sprehn** [eclipse/smarthome#6166]
I noticed that INCREASE and DECREASE are accepted commands for channel of item-type Dimmer, but not anymore for channel of item-type Number. Probably since 2.2 -> 2.3.
With this ticket I would like to suggest to allow those commands.

**Comment by kaikreuzer** [comment]
They have [never been accepted commands since the initial code from 8 years ago](https://github.com/openhab/openhab1-addons/commit/53123636d94ec4a49745a11f0dc8350c97da894a#diff-5f148bc76fad5622e1f28394f0ad0624L50) - introducing them now would probably break around 200 bindings out there, which wouldn't know how to deal with those commands.
