### ISSUE TITLE
Failed to resolve target definition : PKIX path building failed

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#6215]
When I run mvn clean install, I got this error:
```
[ERROR] Failed to resolve target definition D:\dev\openhab2\git\smarthome\targetplatform\smarthome.target: Failed to load p2 metadata repository from location https://dl.bintray.com/openhab/p2/openhab-deps-repo/1.0.28: Unable to read repository at https://dl.bintray.com/openhab/p2/openhab-deps-repo/1.0.28/content.xml. sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target 
```

**Comment by lolodomo** [comment]
@kaikreuzer : please help.
Building is no more possible.
It looks like a certificate problem with this URL: ://dl.bintray.com/openhab/p2/openhab-deps-repo/1.0.28/content.xml

**Comment by kaikreuzer** [comment]
Same now happens on the openHAB2 build: https://openhab.ci.cloudbees.com/job/openHAB2-Bundles/409/console

No clue why this happens, I didn't change a thing...

**Comment by kaikreuzer** [comment]
openHAB build works again (https://openhab.ci.cloudbees.com/job/openHAB2-Bundles/410/), so I assume this issue here should be solved as well.

It seems Bintray deployed a new certificate yesterday, which probably caused a temporary hiccup:

<img width="360" alt="screen shot 2018-09-16 at 16 52 58" src="https://user-images.githubusercontent.com/3244965/45597759-1962aa00-b9d1-11e8-9ec1-fb0ab9e4f268.png">
