### ISSUE TITLE
PaperUI: Context "thing" with limitToOptions=true does not work

### ISSUE THREAD

**Issue by triller-telekom** [eclipse/smarthome#6274]
If a ConfigDescription has a parameter that has the `context` "thing", PaperUI renders a nice drop down of all available things.

However it should be possible to offer options and limit the list of things to these given options.

At the moment, PaperUI simply ignores the given options and the `limitToOptions=true` setting and lists all available things.

**Comment by htreu** [comment]
It seems that pre-given options with contexts `item` or `thing` will be ignored. You can however supply a list of `FilterCriteria` to the `ConfigDescriptionParameter`. This list will be matched against the list of things in Paper UI.

**Comment by kaikreuzer** [comment]
I'd agree with @triller-telekom that this should be considered a bug. If there is a provided option list, this should be taken into account.

**Comment by kaikreuzer** [comment]
FilterCriteria filters for certain types. Why should that be helpful here?
And why is it a missing feature and not a bug, if limitToOptions=true does not limit the values to the provided options?

**Comment by htreu** [comment]
> And why is it a missing feature

because the use of `context` as of now was not meant be be used with existing options. At least in the  code there is no sign of this behaviour.

> FilterCriteria filters for certain types

And if I'm not mistaken it filters for explicit values, like `UID=myThingId`. And given you provide a list of thingIds it should just work fine.

I will provide a PR which tests this behaviour for Paper UI.
