### ISSUE TITLE
Refresh parameter is not working for Classic UI

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#636]
migrated from Bugzilla [#473933](https://bugs.eclipse.org/bugs/show_bug.cgi?id=473933)
status NEW severity *normal* in component *UI* for *---*
Reported in version *0.8.0* on platform *PC*
Assigned to: Project Inbox

On 2015-07-30 09:48:43 -0400, Kai Kreuzer wrote:

> If a refresh is defined for a chart or an image widget in the sitemap, the ClassicUI does not update the chart/image as expected.
> 
> See also https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/openhab2/t-qMxFM7eLk/PmXzFJOrGQAJ

**Comment by watou** [comment]
Looking at this issue (similar to https://github.com/openhab/openhab/issues/1584), and hoping to apply changes similar to https://github.com/openhab/openhab/pull/3930, I can't find a non-minified version of Logic.js in ESH, making debugging very difficult.  Did the non-minified version get lost in the shuffle?

**Comment by kaikreuzer** [comment]
> Did the non-minified version get lost in the shuffle?

[Looking back in time](https://github.com/eclipse/smarthome/blob/0.7.0-release/bundles/ui/org.eclipse.smarthome.ui.webapp/web/WebApp/Action/Logic.js), there has never been a different version of Logic.js as there is now. As this is 3rd party code, we are also not supposed to touch it.

**Comment by watou** [comment]
[Looking back before the beginning of time](https://github.com/openhab/openhab/blob/1.8/bundles/ui/org.openhab.ui.webapp/web/WebApp/Action/Logic.js) :wink:, there was a non-minified version in openHAB 1.x that must not have made it to ESH.

**Comment by kaikreuzer** [comment]
The commit you reference is 8 days ago...

> that must not have made it to ESH.

Correct it would say: Which should never have been there. There was a lot of messing around in OH1 in the Classic UI, which went back and forth, introduced regressions and was never sync'ed to ESH...

**Comment by watou** [comment]
OK, so a non-minified Logic.js was first introduced into openHAB on [Feb 13, 2015](https://github.com/openhab/openhab/pull/2110), years after your initial commit of the minified version.  

I will see if this issue can be fixed relying only on the minified version, which is tricky since the JavaScript exceptions are logged from the minified version.

**Comment by watou** [comment]
The refresh parameter to chart and image widgets does not work on the initial page of the Classic UI because there is no "endslide" event that is needed to set the `imageRefresh` variable to a non-false value:
```javascript
			WA.AddEventListener("endslide", function(evt) {
				hash = document.location.hash;
				path = document.location.pathname;
				if(document.location.search) {
					search = document.location.search + "&";
				} else {
					search = "?";
				}
				search = search + "sitemap=%sitemap%&w=" + hash.substring(2) + "&poll=true";
				url = path + search; 
				WA.Request(url, null, -1, true, null);
				imageRefresh = imagesToRefreshOnPage;
				imagesToRefreshOnPage = 0;
			});
```
However, refresh does in fact work on other pages, since the "endslide" event occurs in those cases.  Should I endeavor to fix this very long-standing issue?

This issue is unrelated to why refresh is not working at all in openHAB 1 (https://github.com/openhab/openhab/issues/1584).
