### ISSUE TITLE
Default UI chart provider does not support OnOff type

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#642]
migrated from Bugzilla [#433143](https://bugs.eclipse.org/bugs/show_bug.cgi?id=433143)
status ASSIGNED severity _enhancement_ in component _UI_ for _---_
Reported in version _unspecified_ on platform _All_
Assigned to: Chris Jackson

On 2014-04-21 11:47:17 -0400, Chris Jackson wrote:

> https://github.com/openhab/openhab/issues/970

On 2014-10-09 10:51:28 -0400, Kai Kreuzer wrote:

> Currently on hold, see https://github.com/eclipse/smarthome/pull/16

**Comment by lolodomo** [comment]
Is it sill true ?
Just reading the code of the default chart provider, I have the feeling that it is handed by the convertData method ?
https://github.com/eclipse/smarthome/blob/master/bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/chart/DefaultChartProvider.java#L232

**Comment by triller-telekom** [comment]
I agree with @lolodomo that this issue is fixed. The code to add a value to the chart:

https://github.com/eclipse/smarthome/blob/35104b43028cd8a68f1359ee0fa2f6ca7c5eb355/bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/chart/defaultchartprovider/DefaultChartProvider.java#L358

converts the data if it is an `OnOffType` here:

https://github.com/eclipse/smarthome/blob/35104b43028cd8a68f1359ee0fa2f6ca7c5eb355/bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/chart/defaultchartprovider/DefaultChartProvider.java#L307-L308

@sjka @kaikreuzer @htreu Can you please close this issue?
