### ISSUE TITLE
[mqtt-things] Textual configuration of things do not work according to readme.md

### ISSUE THREAD

**Issue by chiefymuc** [eclipse/smarthome#6462]
My broker is this:
`mqtt:broker:127_0_0_1_1883`
and I can connect to it through other applications (using mqtt.fx) so that is OK too.

Then I copy-pasted from here: https://github.com/eclipse/smarthome/tree/master/extensions/binding/org.eclipse.smarthome.binding.mqtt.generic 4 and only replaced the broker:

```
Thing mqtt:127_0_0_1_1883:topic:mything {
Channels:
    Type Switch : lamp "Kitchen Lamp" [ mqttstate="lamp/enabled", mqttcommand="lamp/enabled/set" ]
    Type Switch : fancylamp "Fancy Lamp" [ mqttstate="fancy/lamp/state", mqttcommand="fancy/lamp/command", on="i-am-on", off="i-am-off" ]
    Type EnumSwitch : alarmpanel "Alarm system" [ mqttstate="alarm/panel/state", mqttcommand="alarm/panel/set", allowedStates="ARMED_HOME,ARMED_AWAY,UNARMED" ]
    Type Color : lampcolor "Kitchen Lamp color" [ mqttstate="lamp/color", mqttcommand="lamp/color/set", rgb=true ]
    Type Dimmer : blind "Blind" [ mqttstate="blind/state", mqttcommand="blind/set", min=0, max=5, step=1 ]
}
```

Now what I get in the log is this:

```
2018-10-31 11:18:22.951 [WARN ] [el.core.internal.ModelRepositoryImpl] - Configuration model 'mqtt.things' has errors, therefore ignoring it: 
[18,10]: mismatched input 'Switch' expecting RULE_ID
[19,10]: mismatched input 'Switch' expecting RULE_ID
[21,10]: mismatched input 'Color' expecting RULE_ID
[22,10]: mismatched input 'Dimmer' expecting RULE_ID
```

So either Readme.MD is incorrect or there is a bug in the code...

**Comment by kaikreuzer** [comment]
@davidgraeff to the rescue!

**Comment by davidgraeff** [comment]
@kaikreuzer Almost. Is there documentation about the dsl syntax for extendable things? 
PaperUI works, it is just the textual configuration that produces these **expecting RULE_ID** errors.

**Comment by kaikreuzer** [comment]
There is no explicit example for extendable things, because in the DSL it does not matter whether you define a channel of the thing type or any additional one. The KNX binding might be a good reference as its "generic" thing is also extendable - the example dsl can be seen here: https://www.openhab.org/addons/bindings/knx/#examples

**Comment by kaikreuzer** [comment]
Comparing it, it simply seems to be lacking the `Channels:` keyword - which is weird, because [in the docs](https://www.eclipse.org/smarthome/documentation/features/dsl.html#state-channels) I agree that it is expected there....

**Comment by htreu** [comment]
`Type EnumSwitch` seems to be okay and the `Channels:` keyword is optional. So I guess it's about the ID definition and `Switch`, `Color`, `Dimmer` not matching. But `EnumType` matches?

ID definition:

```
terminal ID: '^'?('a'..'z'|'A'..'Z'|'_'|'-'|'0'..'9') ('a'..'z'|'A'..'Z'|'_'|'-'|'0'..'9')*;
```

**Comment by htreu** [comment]
I did prefix Switch, Color & Dimmer by `My` and the model gets parsed as expected. I consider this a bug in the DSL.

**Comment by htreu** [comment]
I think I found the issue here:

This is the definition of `ModelChannel` in the DSL:

```
ModelChannel:
	(((channelKind= ('State' | 'Trigger'))? type=ModelItemType) | 'Type' channelType=UID_SEGMENT) ':' id=CHANNEL_ID
    (label=STRING)?
	('['
		properties+=ModelProperty? (',' properties+=ModelProperty)*
	']')?
;
```

The relevant parts are `type=ModelItemType` and the other option `'Type' channelType=UID_SEGMENT`. Here `ModelItemType` gets resolved first as it actually matches Switch, Color & Dimmer as those are also valid item types.

We could turn around the definition, so channelType gets resolved first. I will propose a PR.

**Comment by htreu** [comment]
Unfortunately the above said is wrong! The keyword `Type` should force Xtext to parse the `channelType` from a UID_SEGMENT.

**Comment by kaikreuzer** [comment]
So the issue is actually that the channel ids are identical to the item type names.

@davidgraeff May I suggest to rename the channels to lowercase, just as they are in KNX as well? Although we do not have any naming convention formally written down yet, almost all channel types are written in small caps in other bindings.

**Comment by htreu** [comment]
All small caps would actually solve the problem. But I don't understand why. The `Type` keyword should make the DSL unambiguous.

**Comment by davidgraeff** [comment]
Yeah, I'll change them to lowercase
