### ISSUE TITLE
Hue binding should cache color temperature and brightness in all cases

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#652]
migrated from Bugzilla [#479793](https://bugs.eclipse.org/bugs/show_bug.cgi?id=479793)
status UNCONFIRMED severity _minor_ in component _Binding_ for _---_
Reported in version _0.8.0_ on platform _All_
Assigned to: Project Inbox

On 2015-10-14 15:58:16 -0400, Dominic Lerbs wrote:

> As mentioned by Kai here (https://github.com/eclipse/smarthome/pull/342#issuecomment-112727297) the hue binding does not cache the color temperature and the brightness in case the values are changes using OnOffType or PercentType.
> 
> A clean solution to this problem probably needs some refactoring of the binding hence this seperate issue report.

**Comment by kaikreuzer** [comment]
Hi @dominicdesu, I am just doing some issue clean up - this one had been created as a follow-up of #342; is this still open and relevant (despite being pretty old)? If so, would you want to create a PR to address it?

**Comment by dominicdesu** [comment]
Hi @kaikreuzer, actually this issue was found by you, I've just created a seperate ticket because it was not really related to my last PR 😃 
I don't know what happened to the hue binding in the meanwhile. If it didn't change much, the issue probably persists, although it is IMHO a very minor issue. I can have a look, but probably not in the next few weeks... I'll put it on my list. Feel free to close it if you think it's not worth being fix.

**Comment by kaikreuzer** [comment]
Ok, thanks for your quick feedback. It isn't urgent at all, but probably worth to fix one day. So if you put it on your list for in a few weeks, that would be nice 👍

**Comment by dominicdesu** [comment]
@kaikreuzer I just had a look at this, there are two ways of approaching this issue:

1. Instead of setting brightess, saturation or color temp via absolute values, the binding could use an API method to increase these values by a certain amount. This API method has been introduced in hue API v1.7, which was published 09/04/2015. This solution is the cleanest and doesn't need caching of values. However, users who don't have a firmware with API < 1.7 cannot use the decrease/increase channels anymore. (The binding could at least log a warning to the console if the API is too old)
2. Improve the current approach of caching these values and stay compatible with hue bridges with API < 1.7.

So the question is, keep backwards compatibility at any cost or ignore users wo are using a 2.5+ years old firmware on their bridge?

**Comment by tavalin** [comment]
Does the bridge/hue API return the firmware version during discovery? Might be a bit more work but maybe you could new thing-types for firmware v1.7+ that has these new channels that aren't appropriate for the older firmware devices.

**Comment by dominicdesu** [comment]
@tavalin good point, I also thought about this. It is indeed possible to check the API version of the bridge, however it's not really about adding new channels, but rather what to do internally when a increaseDecrease command is received on an existing channel (brightness for example). With the old API, the binding needs to cache what the last sent value is, in order to calculate the incremented value (e.g. old 120 + increment 30 = new 150) on the next increaseDecrease command. For the new API, the binding can just send the increment to the bridge (increment 30). 
Even if I would implement different logic here depending on the firmware version, I still need to make sure old firmware bridges (<v1.7) are working correctly (by using/improving caching in the binding). And if I need to cache the values anyway, I can use this approach for bridges with API v1.7+ as well, so no need to implement the new API approach as well.
The code for using API v1.7 would be cleaner, but that doesn't help much if I still need to maintain the old approach...

**Comment by triller-telekom** [comment]
I just had a look at this old issue again, but I don't understand it. In the `HueLightHandler` I see this for color:

https://github.com/eclipse/smarthome/blob/35104b43028cd8a68f1359ee0fa2f6ca7c5eb355/extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueLightHandler.java#L303

and this for brightness:

https://github.com/eclipse/smarthome/blob/35104b43028cd8a68f1359ee0fa2f6ca7c5eb355/extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueLightHandler.java#L322

In both cases the value is cached in a variable on the handler. @dominicdesu What am I overlooking that is preventing us from closing this issue?

**Comment by dominicdesu** [comment]
@triller-telekom 
The linked methods are only called for IncreaseDecreaseType, not for OnOffType or PercentType.
