### ISSUE TITLE
[onewire] slave missing error for temperature thing

### ISSUE THREAD

**Issue by ggzengel** [eclipse/smarthome#6750]
@J-N-K I use your last jar from https://github.com/eclipse/smarthome/issues/6728#issuecomment-450370556

I get:
>23:06:12.846 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - 'onewire:temperature:server1:Ow_T_KG_DG_VL' changed from OFFLINE (COMMUNICATION_ERROR): slave missing to ONLINE

but this thing doesn't has slaves
> Thing temperature Ow_T_KG_DG_VL [ id="28.A26385050000", refresh=60 ] // Sensor 259

**Comment by J-N-K** [comment]
All good. OneWire has exactly one master (usually a DS9490 or something like that) and several slaves (iButtons, DS18B20, DS2413, ...). This message just says that the thing was offline because the sensor (the slave) was not detected on the bus before (i.e. the owserver reported it as „not present“). This is normal operation.

**Comment by J-N-K** [comment]
This is a bug. I‘ll check that.

**Comment by J-N-K** [comment]
Bug will be fixed with #6626.
