### ISSUE TITLE
[lsp] Inline validation works only using drive letter

### ISSUE THREAD

**Issue by hpd96** [eclipse/smarthome#6892]
OS: windows 10
VSCode: 1.32.1
openHAB Extension: 0.4.1 (latest)
openHAB: 2.4.0 Release Build

mapping openhab server "conf" folder (exported via SMB) to local drive letter the syntax validation working:
e.g.
Y:\conf  (drive mapped from \\\\openhabpi\\openhab240)

using URI directly on same openhab SMB share does **not** work
e.g.:
\\\\openhabpi\\openhab240\\conf

this is very irritating and a blocker for newbies because there is no hint or note that URI SMB path is not supported (even you are able to edit the rules files)

see also
https://github.com/eclipse/smarthome/issues/6430

**Comment by openhab-5iver** [comment]
@hpd96, OH reintegrated ESH into openhab-core, so your issue here will be overlooked and should be recreated in one of the OH repos. It sounds like you are requesting a documentation update... https://github.com/openhab/openhab-docs, or possibly a change to the VS Code extension... https://github.com/openhab/openhab-vscode. Hope this helps!

**Comment by hpd96** [comment]
duplicate of https://github.com/eclipse/smarthome/issues/6611
