### ISSUE TITLE
Adding units to config parameters

### ISSUE THREAD

**Issue by rodneyrehm** [eclipse/smarthome#741]
My issue lies with [configuration descriptions](https://github.com/eclipse/smarthome/blob/master/docs/documentation/development/bindings/xml-reference.md#xml-structure-for-configuration-descriptions), in particular with `<parameter>`. In our project we've seen a lot of parameters of the following form:

```xml
<parameter type="integer" …>
  <label>Duration</label>
  <description>Duration in seconds</description>
</parameter>
```

You'll notice how the `<description>` is abused to explain the *unit* the parameter's value is to be provided in. This is a problem because:

* a UI has to render the description, even though only the unit is required - this wastes space and can look confusing
* a UI cannot provide the means to convert between units

As I understand the `NumberItem` has similar problems and requirements.

I propose to add the `<unit>` element to `<parameter>`. The values should come from an index (Kai pointed me to [Units.java](https://github.com/unitsofmeasurement/unit-ri/blob/master/src/main/java/tec/units/ri/unit/Units.java) and [JSR 363 RI Supported Units](https://unitsofmeasurement.gitbooks.io/unit-ri-userguide/content/supported_units.html)) to allow upgrading to a "transparent measurements conversion service" later.

---

**Aside:** The example above uses an `type="integer"`, but could've been provided as:

```xml
<parameter type="text" …>
  <label>Duration</label>
  <context>time</context>
</parameter>
```

This would've allowed a UI to render a proper dial for `<hours>:<minutes>:<seconds>` (based on the time context's [ISO 8601](http://www.ecma-international.org/ecma-262/5.1/#sec-15.9.1.15) format). But to make things like this work - and be considered the default approach - ingestion of string parameters with a context needs to become simpler on the Java side. But that's a separate issue as the request for units holds true for non-time related units as well.

**Comment by kaikreuzer** [comment]
FTR: This is related to https://github.com/eclipse/smarthome/issues/601 in the sense that the unit definitions should be the same.

**Comment by rodneyrehm** [comment]
Having prototyped this locally, we realized that limiting the unit to actual measurements is not enough. We have the generic "seconds", "meters", … units, but we also have specific natural language units such as "iterations", "runs", etc..

I'd therefore like to extend my proposal to the following for defined measurements:

```xml
<parameter type="integer" …>
  <label>Duration</label>
  <unit>TIME.SECONDS</unit>
</parameter>
```
(with `TIME.SECONDS` being a placeholder-value for whatever scheme is going to be used for addressing the map of known measurements)

And the following structure for natural language units:

```xml
<parameter type="integer" …>
  <label>Threshold</label>
  <unit-label>Impulses</unit-label>
</parameter>
```

Both, `unit` and `unit-label` are optional, but mutually exclusive. They only apply for `type="integer"` and `type="decimal"`.

---

I'm not sure about how you feel about attributes (`foo=""`) vs. tags (`<foo>`). I've not understood the significance of `default` being a tag, but `step` being an attribute in [XML Structure for Configuration Descriptions](https://github.com/eclipse/smarthome/blob/master/docs/documentation/development/bindings/xml-reference.md#xml-structure-for-configuration-descriptions). Btw. `required` can apparently be defined either as attribute or as tag?!

**Comment by tomhoefer** [comment]
I would like to start with the implementation of this feature request. 

Furthermore I would like to make an additional proposal for the declaration of the config parameter unit. I prefer to introduce only one additional tag 'unit' instead of introducing both a tag for unit and a tag for unit label.
```xml
<parameter type="integer" …>
  ...
  <!-- declares the unit of the parameter -->
  <unit type="m"/>
</parameter>
```

Then the optional label of the unit can be declared as character node, e.g.
```xml
<parameter type="integer" …>
  ...
  <!-- can be internationalized -->
  <unit type="m">Meter</unit>
</parameter>
```

If the unit is one of the natural language units, then the declaration does not have a type element:
```xml
<parameter type="integer" …>
  ...
  <!-- can be internationalized -->
  <unit>Runs</unit>
</parameter>
```

Because the unit is only used in the UI as label at the moment I suggest for simplicity reasons to model the unit as String instead of the complex type `javax.measure.Unit`. 

The next question I would like to discuss is how to extend the Configuration Parameter class:
- Option 1: We add two String properties. One for unit type and one for unit label.
- Option 2: We add an Unit object that holds both String properties.
- Option 3: We add an unit property to the parameter class that holds the label of the unit. However this would lead to an API break if measurements conversion should be made later.
- Option 4: We add an unit label property to the parameter class. If no label is set for the unit then we will return the type as label. Then the config parameter consumer / caller can decide if the unit type or a solution based label definition is to be displayed.
```xml
<parameter type="integer" …>
  ...
  <unit type="m"/>
</parameter>
```
I prefer either option 1 or 2 (for all options the consumer / caller of the config parameter has to solve the singular / plural problem (one minute, two minutes, one metre, two metres, ...)

For the beginning I would start with the following units based on [Units.java](https://github.com/unitsofmeasurement/unit-ri/blob/master/src/main/java/tec/units/ri/unit/Units.java)

**Comment by tomhoefer** [comment]
After changing the XML schema I prefer now option 2

**Comment by tomhoefer** [comment]
Having already a domain object for the unit has also the advantage the we can reuse it later as kind of a facade / delegate for the actual ´javax.measure.Unit' interface

**Comment by tomhoefer** [comment]
During prototyping of my idea delaring an unit as follows
``` xml
<unit symbol="m">Meter</unit>
```
I recognized that this cannot be parsed because of the so-called ConverterValueMap. This map is only able to convert lists or simple text nodes. For this reason I suggest to model the unit as follows:
``` xml
<unit>>
  <symbol>m</symbol>
  <label>Meter</label>
</unit>
```
@kaikreuzer would this meet also your expecations?

**Comment by kaikreuzer** [comment]
@rodneyrehm:
> I'm not sure about how you feel about attributes (foo="") vs. tags (<foo>).

Afair, there was some good reason to do everything possible as an attribute. The "required" was only left as an element for backward compatibility reasons, but it was meant to be removed and only kept as an attribute.

So in general, I would also tend to treat "unit" as an attribute. Since "unit-label" has to be localizable, this would need to be an element. I wouldn't consider this a problem, though.

@tomhoefer:
I did not get your argument, why you do not want to follow the original suggestion, but put away the mutual exclusivity. "symbol" is imho a rather bad choice as it does not express that it is rather a reference to a unit than some symbolic text to be displayed. I'd vote to go for "unit" and I would define it as an (string) attribute.

@cdjackson:
Since you are a "heavy user" of the config descriptions for UIs yourself: Do you have any input on this request?

**Comment by tomhoefer** [comment]
I choosed symbol because of http://www.bipm.org/en/publications/si-brochure/table3.html, but using unit as attribute and unit-label as child node of parameter is also fine for me since this meet also our requirements. 

If a developer specifies both unit and unit-label then the unit label will be ignored.

**Comment by cdjackson** [comment]
I don't really have any comments - I like the suggestion. I don't mind if attributes or elements are used since once this is ingested from the XML into java / REST, it's all the same.  I also implemented a "units" field in the zwave database in anticipation of this feature :)

**Comment by kaikreuzer** [comment]
Implemented with https://github.com/eclipse/smarthome/pull/889
