### ISSUE TITLE
Paper UI must not do configuration updates through a thing update

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#771]
When editing the configuration of a Thing, the Paper UI currently PUTs an updated thing to `/things/{thingUID}`.
Instead, it should use the new configuration uri at '/things/{thingUID}/config', which will handle configuration updates nicer.

**Comment by maggu2810** [comment]
I think about the changes that needs to be done for the Paper UI.
The current configuration page also offers the option to change the name and the group(s).
I am not a web developer, so I do not know if it could be handled easily, but then the current site has to differ between a configuration change and a change of name or group membership.

**Comment by kaikreuzer** [comment]
The name&group handling anyhow has to be refactored; the whole management of Things should not have a direct impact on items. See also https://github.com/eclipse/smarthome/issues/710

**Comment by cdjackson** [comment]
Just a note on this - at the moment, the ZWave binding only configures the device as a result of the configuration update method - not as a result of a thing updated call. As has been discussed a long time ago on the Eclipse forum. this is necessary due to the diverse nature of configuration types in zwave - we can't just resend data every time the device starts.

This currently means that the PaperUI cant configure the ZWave binding.

**Comment by kaikreuzer** [comment]
Thanks for the notice, so this means the priority of this issue has risen :-)

**Comment by kaikreuzer** [comment]
Implemented with #963
