### ISSUE TITLE
JSONPATH transforms not compatible with OH1

### ISSUE THREAD

**Issue by watou** [eclipse/smarthome#781]
OH1 uses json-path-0.9.0, which is very old and different from json-path-2.0.0 that Eclipse SmartHome currently uses. (There is a json-path-2.1.0 available since 22 November which is probably worth upgrading to in ESH, give the [changelog description](https://github.com/jayway/JsonPath/blob/master/changelog.md).)  

A user [discovered a breaking change](https://community.openhab.org/t/jsonpath-transform-in-oh2-http-binding/4715) in how the JSONPATH transform is handled.

This is not to suggest that ESH should be changed to work like OH1, or that OH1 should be changed to work like ESH, but this would at least be an issue to add to a list of known wontfix incompatibilities between the two.  Or perhaps there is a different approach to preserving compatibility?

**Comment by kaikreuzer** [comment]
I think this is not an issue for ESH, because this project never had a different implementation and thus does not break any backward compatibility (for itself).

You might want instead create a PR for OH2 that adds this information to https://github.com/openhab/openhab2/blob/master/docs/sources/intro.md.
