### ISSUE TITLE
missing 'scale' parameter in ChartServlet

### ISSUE THREAD

**Issue by teichsta** [eclipse/smarthome#796]
it seems an enhancement got lost for the ChartServlet (see https://github.com/openhab/openhab/pull/3444 for more details)

**Comment by triller-telekom** [comment]
The `scale` parameter is back since 02.03.2017 in [the ChartServlet](https://github.com/eclipse/smarthome/blob/master/bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/chart/ChartServlet.java#L178)

And the fix from the referenced PR from openHAB has also been applied, i.e. `if(scale < 0.1) ` now vs `if(scale < 0.5)` as it was before.

@sjka @kaikreuzer Please close this issue.
