### ISSUE TITLE
Default sitemap for BasicUI on demo.openhab.org is not set

### ISSUE THREAD

**Issue by resetnow** [eclipse/smarthome#843]
I'm not sure whether or not this issue should be here, so please tell me if it should be filed elsewhere.

http://demo.openhab.org:9080/basicui/app shows an error because the default sitemap is `default` and not `demo`. Also, only first level of sitemap is available and all other levels are empty. This applies to ClassicUI too.

**Comment by kaikreuzer** [comment]
No, the issue does not belong here at all ;-)
@teichsta maintains the demo server and either he missed setting the configuration or somebody changed it - because currently, anybody can change the default sitemap name through http://demo.openhab.org:9080/ui/index.html#/configuration/services. This is a feature that should probably be deactivated on the demo server!

**Comment by kaikreuzer** [comment]
P.S.: I put "demo" in there, so the link from the dashboard works now. Thanks for noticing!
