### ISSUE TITLE
configuration update

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#860]
If I change configuration parameters using the Paper UI the <code>thingUpdated(Thing)</code> method of the thing handler is called.
I would expect that a configuration change will trigger a call of <code>handleConfigurationUpdate(Map&lt;String, Object&gt;)</code> of the thing handler.

Is the logic of the Paper UI correct and a thingUpdated call implies that the configuration could have been changed?

A configuration update could result in much stuff to be done, so I would assume that the function is handleConfigurationUpdate is called on a changed configuration (only).

**Comment by kaikreuzer** [comment]
Looks like a duplicate of https://github.com/eclipse/smarthome/issues/771, right?

**Comment by maggu2810** [comment]
Yes, but I have an additional question:

What "updates" should be handled in thingUpdated at all?

So, which function is called on which trigger?

Should the thingUpdated method calls the handleConfigurationUpdate?
States a thingUpdate method call, that the configuration has not been changed?

**Comment by kaikreuzer** [comment]
Well, thingUpdated is triggered, if someone replaces the Thing in the ThingRegistry, e.g. by PUTting a new JSON structure through REST. For the handler, it means that it should best completely re-initialize itself, because ANYTHING could have changed about the Thing, the only part that is guaranteed to be the same as before is the ThingUID.
@sbussweiler: Correct me, in case https://github.com/eclipse/smarthome/pull/769 changes something in my understanding.

**Comment by maggu2810** [comment]
We could close this issue as soon as we have a answer from @sbussweiler.

Further stuff could be discussed on the duplicated issue.

**Comment by sbussweiler** [comment]
The behavior is the one as mentioned by Kai. thingUpdated() is called for every thing that was updated in the ThingRegistry. PR #769 does not change thins behavior!

**Comment by maggu2810** [comment]
Further discussion should be addressed here: #771
