### ISSUE TITLE
[yahooweather] YahooWeatherDiscoveryService.getWoeidData() URL discontinued

### ISSUE THREAD

**Issue by watou** [eclipse/smarthome#907]
One can no longer query Yahoo! YQL with a lat,long to return a WOEID.  

References:
* [Yahoo! Developer forum post](https://developer.yahoo.com/forums/#/discussion/7838/tahoo-geo-placefinder-does-not-work%3D%3D%3D)
* [openHAB forum post regarding 1.x weather binding](https://community.openhab.org/t/yahoo-weather-service-issue-weather-binding-1-7-1/6528)
* https://github.com/openhab/openhab/pull/3888

**Comment by watou** [comment]
Possible changes to address the discontinued Yahoo! geo.placefinder service:

1. Write a trivial service that runs at a well known address and uses the [Flickr API to retrieve woeid from lat,long](https://www.flickr.com/services/api/flickr.places.findByLatLon.html), and caches the results to minimize queries.  This may conflict with Flickr terms of service, so that would need to be verified first.
2. Remove discovery from yahooweather binding.
3. Write a new binding using an alternative weather provider that does not require API keys and provides weather by public IP or lat,long (such as [met.no](http://api.met.no/weatherapi/locationforecast/1.9/documentation), whose data and API are excellent, from my experience).

I could implement 3 above if anyone is interested.

**Comment by kaikreuzer** [comment]
The main purpose for the YahooWeather binding was so far to serve as an example for [the tutorial](https://www.eclipse.org/smarthome/documentation/development/bindings/how-to.html). Luckily, this tutorial never covered the discovery part of the binding :-)
So in order to keep at least parts of the binding that are relevant for the tutorial, I would opt for option 2 above.
For option 3, I think we will sooner or later see the [openHAB Weather binding](https://github.com/openhab/openhab/wiki/Weather-Binding) being ported to the new APIs. But there is imho no rush to do this right now.

Could you prepare a PR for option 2?

**Comment by watou** [comment]
> Could you prepare a PR for option 2?

Yes; I will add it to my queue.  Feel free to assign this issue to me.

**Comment by kaikreuzer** [comment]
I would like to but I cannot, since only official committers are in the team list on Github and I do not have the rights to change that...

**Comment by watou** [comment]
No worries.
