### ISSUE TITLE
OSGI :  Preferred way to declare services

### ISSUE THREAD

**Issue by kgoderis** [eclipse/smarthome#908]
Just for achieving some code format consistency, what is the preferred way to declare OSGi services? 
DS or via the API ? And if the API, in the Activator class itself, or should the be delegated to the actual class consuming the service (e.g. doing it's own registration tracking etc)?

We have all of these approaches all over the code base, I am not sure all of them are intended the way they are. For example, BaseModuleHandlerFactory takes BundleContext as argument in its constructor, but does not do anything with it.

**Comment by kaikreuzer** [comment]
For ESH in general, the preferred way is DS and we do it almost everywhere this way.
For the automation component, we did an exception from this rule, because ProSyst (who implemented the major parts of it) asked us to not mandatorily depend on DS.
So the answer to your question depends on whether you work on code that is part of the "core" rule engine (go for service trackers) or if it is rather for integrating with other parts of ESH (like the Xbase scripts, go for DS).

**Comment by kgoderis** [comment]
Not ideal i guess, but it is what it is. BaseModuleHandlerFactory taking a BundleContext as argument in the constructor means that this is a no-no for DS. It is a pity they did not go for default constructors and add a setBundleContext(BundleContext bc)  instead.

**Comment by kaikreuzer** [comment]
Good point, let's have it fixed: https://github.com/eclipse/smarthome/issues/912

**Comment by marinmitev** [comment]
@kgoderis Could you confirm that pull request #912 works for you

**Comment by kgoderis** [comment]
Yep, all ok for me
