### ISSUE TITLE
Automation API should not prevent the use of Declarative Services

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#912]
The BaseModuleHandlerFactory expects the bundle context in its constructor. This prevents declaring handler factories through DS. This should be changed to a setBundleContext method, see https://github.com/eclipse/smarthome/issues/908#issuecomment-174288786.

@danchom Could you have a look at that, please?

**Comment by danchom** [comment]
1) I want mention that this change will be not backward compatible. All extended classes has to be changed, but the real problem is, it will break third party module handlers. May be there are not so many :).
2) Isn't be better,  the name of the method to be activate(BundleContext bc) instead of setBundleContext(bc) - in that way an implementer  hasn't change default activate name in the XML 
3) The moduleHandlerFactory will not be registered until the activate (setBundleContext) will be called.

**Comment by kaikreuzer** [comment]
1) Correct, so better do it now than later :-)
2) What happens, if the implementer prefers to pass the ComponentContext to activate() and thus ends up with two activate methods - do you know how DS will handle this?
3) makes sense

**Comment by danchom** [comment]
2) I'm not in depth in DS, but I think it must call super.activate(BundleContext bc) in case when it want to overwrite the activate method. This should be written in the java doc.

**Comment by marinmitev** [comment]
regarding activate method
Component implementation class can declare the following activate methods
```java
  public void activate(BundleContext bc) {
     super.activate(bc)
  }
```
or if it needs component context too then it can declare both:
``` java
  public void activate(ComponentContext cc, BundleContext bc) {
    System.out.println("component activate cc=" + cc + " bc=" + cc);
       super.activate(bc)
 }
```

**Comment by kaikreuzer** [comment]
@marinmitev: And if both are present, the second one is the one that gets called?

**Comment by marinmitev** [comment]
if both are present then only the first one is called - with BundleContext only

**Comment by marinmitev** [comment]
I have just checked that if the parent class has activate method with BundleContext 
and the extending class has activate(ComponentContext,BundleContext) then the second activate method is called which can then call super.activate(bc)

**Comment by kaikreuzer** [comment]
ok, perfect - thanks for checking, @marinmitev!

**Comment by maggu2810** [comment]
FYI

OSGi Compendium
Release 5


112.5.8 Activate Method

...

A suitable method is selected using the following priority:
1. The method takes a single argument and the type of the argument is
org.osgi.service.component.ComponentContext.
2. The method takes a single argument and the type of the argument is
org.osgi.framework.BundleContext.
3. The method takes a single argument and the type of the argument is the java.util.Map.
4. The method takes two or more arguments and the type of each argument must be
org.osgi.service.component.ComponentContext, org.osgi.framework.BundleContext or
java.util.Map. If multiple methods match this rule, this implies the method name is overloaded
and SCR may choose any of the methods to call.
5. The method takes zero arguments.

When searching for the activate method to call, SCR must locate a suitable method as specified
in Locating Component Methods on page 308.

...

112.9.4 Locating Component Methods
SCR will need to locate activate, deactivate, modified, bind, updated, and unbind methods for a com-
ponent instance. These methods will be located, and called, using reflection. The declared methods
of each class in the component implementation class' hierarchy are examined for a suitable method.
If a suitable method is found in a class, and it is accessible to the component implementation class,
then that method must be used. If suitable methods are found in a class but none of the suitable
methods are accessible by the component implementation class, then the search for suitable meth-
ods terminates with no suitable method having been located. If no suitable methods are found in a
class, the search continues in the superclass.
Only methods that are accessible to the component implementation class will be used. If the
method has the public or protected access modifier, then access is permitted. Otherwise, if the
method has the private access modifier, then access is permitted only if the method is declared in
the component implementation class. Otherwise, if the method has default access, also known as
package private access, then access is permitted only if the method is declared in the component
implementation class or if the method is declared in a superclass and all classes in the hierarchy
from the component implementation class to the superclass, inclusive, are in the same package and
loaded by the same class loader.
It is recommended that these methods should not be declared with the public access modifier so
that they do not appear as public methods on the component instance when it is used as a service
object. Having these methods declared public allows any code to call the methods with reflection,
even if a Security Manager is installed. These methods are generally intended to only be called by
SCR.

**Comment by kaikreuzer** [comment]
Fixed with https://github.com/eclipse/smarthome/pull/915
