### ISSUE TITLE
Paper UI fragment themeing changed

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#918]
It seems to me that #873 has broken my Paper UI overloading using a fragment bundle that contains a custom constants.js.

If I rename the constants.js to constants.min.js in my fragment the old behavior is working again.
Don't know if this has be done by intention.

For me this is solved after changing my fragment. I created this issue to leave some note for other ones.

* https://github.com/eclipse/smarthome/commit/bd2bab036da3ed9daaabaaeffdcabed0ea26910b#diff-8ca044496e7baf20d0dd0d00dd87c5d7L128
* https://github.com/eclipse/smarthome/commit/bd2bab036da3ed9daaabaaeffdcabed0ea26910b#diff-789470ff4163c4d9f36f14cc2afc03e4R122

**Comment by kaikreuzer** [comment]
Good point @maggu2810.
@GradyD Could you comment on how you suggest the fragment overloading is expected to look like with the new solution? I would actually like to avoid having to introduce the whole gulp+etc build chain in openHAB and other solutions as well - imho the fragment should be a simple set of files that do not need any further processing.
This is probably especially important for the CSS vs. SASS discussion as the CSS files are a major part where customization takes place.

**Comment by GradyD** [comment]
I'm not familiar with using fragments and I'm not 100% well versed when it comes to what options you have once the JAR is built.

In theory if the file is updated in the web-src and gulp is ran it should be the updated file.

Can you point me to some documentation or explain how fragments work? My guess is that we will need to make some update on the jetty side so that if a file exists in a special folder, fragments folder?, to serve that file instead.

How was this done before gulp came around? 

Let's move the CSS/sass discussion to the open PR as that one should be a slightly different approach.

**Comment by maggu2810** [comment]
You can use a fragment bundle to add stuff (e.g. files) to another bundle (the fragment host) at runtime.
If you have a look at the bundle classpath of the Paper UI, you will see, that it looks first in a directory patch (that does not exist in that bundle) and then it looks in "."
Now you can use a fragment that provides files in patch that will be used before the one in the fragment host is used.

Example:
* Paper UI bundle: web/js/constant.js
* Paper UI fragment: patch/web/js/constant.js
If the classloader try to get the resource web/js/contant.js it will look first at "patch" and if that fails on "."
So we can replace files on runtime.

This is done for disabling special sections (e.g. control, rules, ...) and to overwrite a css that defines colors etc.

**Comment by GradyD** [comment]
This makes sense. Rereading the original issue I believe this is happening because gulp is adding .min to the file. 

So the raw code is in `web-src` and the file is named `constants.js`. When you run gulp the file is minified and renamed to be `constants.min.js` and saved in `web`. It is easy enough to remove the `.min` and keep the same file name and just leave the 'core' version minified.

**Comment by kaikreuzer** [comment]
> It is easy enough to remove the .min and keep the same file name and just leave the 'core' version minified.

Yes, if this is easily possible, I prefer it this way. The constants.js is meant to be customized and it is small in size, so not minifying it sounds like the best option.

**Comment by GradyD** [comment]
Sounds good. I will minify the files without adding `.min` to the file name and create a PR for this tonight.

**Comment by kaikreuzer** [comment]
>  I will minify the files without adding .min to the file name and create a PR for this tonight.

As #921 is not merged, please go ahead!

**Comment by kaikreuzer** [comment]
fixed by #934
