### ISSUE TITLE
refactoring of ThingManager

### ISSUE THREAD

**Issue by dvanherbergen** [eclipse/smarthome#955]
After looking at both the [doc](http://www.eclipse.org/smarthome/documentation/development/bindings/thing-handler.html) and the [code](https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java), I've understood that the principle is

```
1. ThingManager calls registerHandler on ThingHandlerFactory, 
2. ThingHandlerFactory creates ThingHandler instance and registers it as an OSGI service,
3. ThingHandlerTracker receives the newly created OSGI service 
4. ThingHandlerTracker hands ThingHandler back to the ThingManager
```

What I don't understand, is why it doesn't just do:

```
1. ThingManager calls registerHandler on ThingHandlerFactory,
2. ThingHandlerFactory creates instance and returns it to the ThingManager.
```

Unless there is a real need to create both the ThingHandlerTracker and the ThingHandler OSGI services, the code should IMHO be simplified.

**Comment by dvanherbergen** [comment]
@kaikreuzer, what is your opinion on this? OK to simplify?

**Comment by kaikreuzer** [comment]
Sorry for not having answered yet - the reason is that I am not sure what to answer...
Your suggestion comes down to saying that we completely could get rid off registering the ThingHandlers as OSGi services, right? I am a bit uncertain what effects that might have (and where it might be important to have the OSGi services in place).
@sbussweiler, @sjka, do you have any feedback whether @dvanherbergen suggestion is feasible or not?

**Comment by dnobel** [comment]
Let me share some thoughts from the past:

We decided to have the ThingHandler as an OSGi service, which allows the binding to handle the registration and deregistration of it - independently of the thing lifecycle. You can always discuss the advantages and disadvantages of having service x as OSGi service or not. One good thing of the OSGi service is, that - whatever the binding does - the services will be unregistered if the binding is uninstalled/stopped. Otherwise you might hold invalid references to non-existing classes. And it gives you dynamics, so that the binding can decide to remove the handler at any point and the current logic keeps track of it via the service tracker. If you remove that, you need to build an own listener or event infrastructure. So for me having the handlers as OSGi services still makes sense.

As Kai said, even if you decide npot having OSGi services it will be massive effort to refactor everything, especially all the tests on that and there will be probably some new problems around the life-cycle.

However I agree, that some refactorings are needed for the ThingManager and the whole framework-binding communication, to simplify concepts and code. For the general lifecycle of a handler and the according framework methods I remember some discussions with @sbussweiler a few month ago.

**Comment by dvanherbergen** [comment]
> We decided to have the ThingHandler as an OSGi service, which allows the binding to handle the registration and deregistration of it - independently of the thing lifecycle. 

This is where I believe the biggest issue lies with the current implementation. There is no clear separation of concerns for the creation of a ThingHandler. This responsibility is currently shared by both the ThingManager and the ThingHandlerFactory. 

> You can always discuss the advantages and disadvantages of having service x as OSGi service or not. 

I'm not questioning the benefits of OSGI services. I'm a big fan of them.

> One good thing of the OSGi service is, that - whatever the binding does - the services will be unregistered if the binding is uninstalled/stopped. Otherwise you might hold invalid references to non-existing classes. 

The ThingHandlerFactory is already an OSGI service. You could easily remove all the references to the ThingHandlers that were created by a ThingHandlerFactory during the unregistration of that ThingHandlerFactory.

> And it gives you dynamics, so that the binding can decide to remove the handler at any point and the current logic keeps track of it via the service tracker. If you remove that, you need to build an own listener or event infrastructure. So for me having the handlers as OSGi services still makes sense.

Can you given an example use case, other than the stopping of a binding, where the binding would need to be able to unregister a handler? I'm finding it difficult to come up with one..

> As Kai said, even if you decide not having OSGi services it will be massive effort to refactor everything, especially all the tests on that and there will be probably some new problems around the life-cycle.

As far as I can tell, it should be rather easy to change the code. The test cases are indeed a bit more work, but the amount of work to fix something should not affect the decision, only the timeline ;-)

> However I agree, that some refactorings are needed for the ThingManager and the whole framework-binding communication, to simplify concepts and code. For the general lifecycle of a handler and the according framework methods I remember some discussions with @sbussweiler a few month ago.

Interesting, do you have a link to this discussion? Is there any work already planned?

**Comment by dnobel** [comment]
> This is where I believe the biggest issue lies with the current implementation. There is no clear separation of concerns for the creation of a ThingHandler. This responsibility is currently shared by both the ThingManager and the ThingHandlerFactory.

I don´t agree. The separation is clearly that the ThingManager asks the binding to register a handler for a thing. The ThingManages doesn´t create or manages handlers, it´s in the responsibility of the ThingHandlerFactory only.

> The ThingHandlerFactory is already an OSGI service. You could easily remove all the references to the ThingHandlers that were created by a ThingHandlerFactory during the unregistration of that ThingHandlerFactory.

That´s true

> Can you given an example use case, other than the stopping of a binding, where the binding would need to be able to unregister a handler? I'm finding it difficult to come up with one.

Seems as no binding is using it so far. Moreover with the refactoring of the handler lifecycle, that was already committed by @sbussweiler  a few weeks ago (see https://github.com/eclipse/smarthome/commit/06c4084d1e3a10e1258beb2bf5463a84f0860c31) it looks like that within the whole ESH repo no one besides the ThingManager is tracking ThingHandler OSGi services any more.

> As far as I can tell, it should be rather easy to change the code. The test cases are indeed a bit more work, but the amount of work to fix something should not affect the decision, only the timeline ;-)

Agreed. Probably it might be easier as I thought, especially as the mentioned lifecycle refactoring was already implemented by Stefan. But it still effort and implies some breaking changes as the method must be renamed from "registerThingHandler" to "createThingHandler", which might break some openHAB bindings. It also affects documentation.

However, I don´t have any strong argument for having the ThingHandler as OSGi service any more. In case it simplifies the code and doesn´t break anything I think it could probably be changed.

**Comment by sbussweiler** [comment]
I think this refactoring is done with #2087. 

@kaikreuzer  What do you think?

**Comment by kaikreuzer** [comment]
At least it won't get any better than this ;-)
